<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: keyspacepb.proto

namespace CrazyGoat\Proto\Keyspacepb;

use UnexpectedValueException;

/**
 * Protobuf type <code>keyspacepb.KeyspaceState</code>
 */
class KeyspaceState
{
    /**
     * Generated from protobuf enum <code>ENABLED = 0;</code>
     */
    const ENABLED = 0;
    /**
     * Generated from protobuf enum <code>DISABLED = 1;</code>
     */
    const DISABLED = 1;
    /**
     * Generated from protobuf enum <code>ARCHIVED = 2;</code>
     */
    const ARCHIVED = 2;
    /**
     * Generated from protobuf enum <code>TOMBSTONE = 3;</code>
     */
    const TOMBSTONE = 3;

    private static $valueToName = [
        self::ENABLED => 'ENABLED',
        self::DISABLED => 'DISABLED',
        self::ARCHIVED => 'ARCHIVED',
        self::TOMBSTONE => 'TOMBSTONE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

