<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: keyspacepb.proto

namespace CrazyGoat\Proto\Keyspacepb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>keyspacepb.LoadKeyspaceResponse</code>
 */
class LoadKeyspaceResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.pdpb.ResponseHeader header = 1;</code>
     */
    protected $header = null;
    /**
     * Generated from protobuf field <code>.keyspacepb.KeyspaceMeta keyspace = 2;</code>
     */
    protected $keyspace = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CrazyGoat\Proto\Pdpb\ResponseHeader $header
     *     @type \CrazyGoat\Proto\Keyspacepb\KeyspaceMeta $keyspace
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Keyspacepb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.pdpb.ResponseHeader header = 1;</code>
     * @return \CrazyGoat\Proto\Pdpb\ResponseHeader|null
     */
    public function getHeader()
    {
        return $this->header;
    }

    public function hasHeader()
    {
        return isset($this->header);
    }

    public function clearHeader()
    {
        unset($this->header);
    }

    /**
     * Generated from protobuf field <code>.pdpb.ResponseHeader header = 1;</code>
     * @param \CrazyGoat\Proto\Pdpb\ResponseHeader $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Pdpb\ResponseHeader::class);
        $this->header = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.keyspacepb.KeyspaceMeta keyspace = 2;</code>
     * @return \CrazyGoat\Proto\Keyspacepb\KeyspaceMeta|null
     */
    public function getKeyspace()
    {
        return $this->keyspace;
    }

    public function hasKeyspace()
    {
        return isset($this->keyspace);
    }

    public function clearKeyspace()
    {
        unset($this->keyspace);
    }

    /**
     * Generated from protobuf field <code>.keyspacepb.KeyspaceMeta keyspace = 2;</code>
     * @param \CrazyGoat\Proto\Keyspacepb\KeyspaceMeta $var
     * @return $this
     */
    public function setKeyspace($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Keyspacepb\KeyspaceMeta::class);
        $this->keyspace = $var;

        return $this;
    }

}

