<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: metapb.proto

namespace CrazyGoat\Proto\Metapb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>metapb.Peer</code>
 */
class Peer extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>uint64 store_id = 2;</code>
     */
    protected $store_id = 0;
    /**
     * Generated from protobuf field <code>.metapb.PeerRole role = 3;</code>
     */
    protected $role = 0;
    /**
     * Generated from protobuf field <code>bool is_witness = 4;</code>
     */
    protected $is_witness = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *     @type int|string $store_id
     *     @type int $role
     *     @type bool $is_witness
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Metapb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>uint64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 store_id = 2;</code>
     * @return int|string
     */
    public function getStoreId()
    {
        return $this->store_id;
    }

    /**
     * Generated from protobuf field <code>uint64 store_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStoreId(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->store_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.metapb.PeerRole role = 3;</code>
     * @return int one of the values in {@see \CrazyGoat\Proto\Metapb\PeerRole}
     */
    public function getRole()
    {
        return $this->role;
    }

    /**
     * Generated from protobuf field <code>.metapb.PeerRole role = 3;</code>
     * @param int $var one of the values in {@see \CrazyGoat\Proto\Metapb\PeerRole}
     * @return $this
     */
    public function setRole(int $var)
    {
        GPBUtil::checkEnum($var, \CrazyGoat\Proto\Metapb\PeerRole::class);
        $this->role = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_witness = 4;</code>
     * @return bool
     */
    public function getIsWitness()
    {
        return $this->is_witness;
    }

    /**
     * Generated from protobuf field <code>bool is_witness = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsWitness(bool $var)
    {
        $this->is_witness = $var;

        return $this;
    }

}

