<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: replication_modepb.proto

namespace CrazyGoat\Proto\ReplicationModepb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * The status of dr-autosync mode.
 *
 * Generated from protobuf message <code>replication_modepb.DRAutoSync</code>
 */
class DRAutoSync extends \Google\Protobuf\Internal\Message
{
    /**
     * The key of the label that used for distinguish different DC.
     *
     * Generated from protobuf field <code>string label_key = 1;</code>
     */
    protected $label_key = '';
    /**
     * Generated from protobuf field <code>.replication_modepb.DRAutoSyncState state = 2;</code>
     */
    protected $state = 0;
    /**
     * Unique ID of the state, it increases after each state transfer.
     *
     * Generated from protobuf field <code>uint64 state_id = 3;</code>
     */
    protected $state_id = 0;
    /**
     * Duration to wait before switching to SYNC by force (in seconds)
     *
     * Generated from protobuf field <code>int32 wait_sync_timeout_hint = 4;</code>
     */
    protected $wait_sync_timeout_hint = 0;
    /**
     * Stores should only sync messages with available stores when state is ASYNC or ASYNC_WAIT.
     *
     * Generated from protobuf field <code>repeated uint64 available_stores = 5;</code>
     */
    private $available_stores;
    /**
     * Stores should forbid region split.
     *
     * Generated from protobuf field <code>bool pause_region_split = 6;</code>
     */
    protected $pause_region_split = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $label_key
     *           The key of the label that used for distinguish different DC.
     *     @type int $state
     *     @type int|string $state_id
     *           Unique ID of the state, it increases after each state transfer.
     *     @type int $wait_sync_timeout_hint
     *           Duration to wait before switching to SYNC by force (in seconds)
     *     @type int[]|string[] $available_stores
     *           Stores should only sync messages with available stores when state is ASYNC or ASYNC_WAIT.
     *     @type bool $pause_region_split
     *           Stores should forbid region split.
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\ReplicationModepb::initOnce();
        parent::__construct($data);
    }

    /**
     * The key of the label that used for distinguish different DC.
     *
     * Generated from protobuf field <code>string label_key = 1;</code>
     * @return string
     */
    public function getLabelKey()
    {
        return $this->label_key;
    }

    /**
     * The key of the label that used for distinguish different DC.
     *
     * Generated from protobuf field <code>string label_key = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setLabelKey(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->label_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.replication_modepb.DRAutoSyncState state = 2;</code>
     * @return int one of the values in {@see \CrazyGoat\Proto\ReplicationModepb\DRAutoSyncState}
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * Generated from protobuf field <code>.replication_modepb.DRAutoSyncState state = 2;</code>
     * @param int $var one of the values in {@see \CrazyGoat\Proto\ReplicationModepb\DRAutoSyncState}
     * @return $this
     */
    public function setState(int $var)
    {
        GPBUtil::checkEnum($var, \CrazyGoat\Proto\ReplicationModepb\DRAutoSyncState::class);
        $this->state = $var;

        return $this;
    }

    /**
     * Unique ID of the state, it increases after each state transfer.
     *
     * Generated from protobuf field <code>uint64 state_id = 3;</code>
     * @return int|string
     */
    public function getStateId()
    {
        return $this->state_id;
    }

    /**
     * Unique ID of the state, it increases after each state transfer.
     *
     * Generated from protobuf field <code>uint64 state_id = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStateId(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->state_id = $var;

        return $this;
    }

    /**
     * Duration to wait before switching to SYNC by force (in seconds)
     *
     * Generated from protobuf field <code>int32 wait_sync_timeout_hint = 4;</code>
     * @return int
     */
    public function getWaitSyncTimeoutHint()
    {
        return $this->wait_sync_timeout_hint;
    }

    /**
     * Duration to wait before switching to SYNC by force (in seconds)
     *
     * Generated from protobuf field <code>int32 wait_sync_timeout_hint = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setWaitSyncTimeoutHint(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->wait_sync_timeout_hint = $var;

        return $this;
    }

    /**
     * Stores should only sync messages with available stores when state is ASYNC or ASYNC_WAIT.
     *
     * Generated from protobuf field <code>repeated uint64 available_stores = 5;</code>
     * @return RepeatedField<int>|RepeatedField<string>
     */
    public function getAvailableStores()
    {
        return $this->available_stores;
    }

    /**
     * Stores should only sync messages with available stores when state is ASYNC or ASYNC_WAIT.
     *
     * Generated from protobuf field <code>repeated uint64 available_stores = 5;</code>
     * @param int[]|string[] $var
     * @return $this
     */
    public function setAvailableStores(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT64);
        $this->available_stores = $arr;

        return $this;
    }

    /**
     * Stores should forbid region split.
     *
     * Generated from protobuf field <code>bool pause_region_split = 6;</code>
     * @return bool
     */
    public function getPauseRegionSplit()
    {
        return $this->pause_region_split;
    }

    /**
     * Stores should forbid region split.
     *
     * Generated from protobuf field <code>bool pause_region_split = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setPauseRegionSplit(bool $var)
    {
        $this->pause_region_split = $var;

        return $this;
    }

}

