<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: replication_modepb.proto

namespace CrazyGoat\Proto\ReplicationModepb;

use UnexpectedValueException;

/**
 * Protobuf type <code>replication_modepb.DRAutoSyncState</code>
 */
class DRAutoSyncState
{
    /**
     * Raft logs need to sync between different DCs
     *
     * Generated from protobuf enum <code>SYNC = 0;</code>
     */
    const SYNC = 0;
    /**
     * Wait for switching to ASYNC. Stop sync raft logs between DCs.
     *
     * Generated from protobuf enum <code>ASYNC_WAIT = 1;</code>
     */
    const ASYNC_WAIT = 1;
    /**
     * Raft logs need to sync to majority peers
     *
     * Generated from protobuf enum <code>ASYNC = 2;</code>
     */
    const ASYNC = 2;
    /**
     * Switching from ASYNC to SYNC mode
     *
     * Generated from protobuf enum <code>SYNC_RECOVER = 3;</code>
     */
    const SYNC_RECOVER = 3;

    private static $valueToName = [
        self::SYNC => 'SYNC',
        self::ASYNC_WAIT => 'ASYNC_WAIT',
        self::ASYNC => 'ASYNC',
        self::SYNC_RECOVER => 'SYNC_RECOVER',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

