<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: replication_modepb.proto

namespace CrazyGoat\Proto\ReplicationModepb;

use UnexpectedValueException;

/**
 * Protobuf type <code>replication_modepb.ReplicationMode</code>
 */
class ReplicationMode
{
    /**
     * The standard mode. Replicate logs to majority peer.
     *
     * Generated from protobuf enum <code>MAJORITY = 0;</code>
     */
    const MAJORITY = 0;
    /**
     * DR mode. Replicate logs among 2 DCs.
     *
     * Generated from protobuf enum <code>DR_AUTO_SYNC = 1;</code>
     */
    const DR_AUTO_SYNC = 1;

    private static $valueToName = [
        self::MAJORITY => 'MAJORITY',
        self::DR_AUTO_SYNC => 'DR_AUTO_SYNC',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

