<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: replication_modepb.proto

namespace CrazyGoat\Proto\GPBMetadata;

class ReplicationModepb
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xD9\x06\x0A\x18replication_modepb.proto\x12\x12replication_modepb\"\x84\x01\x0A\x11ReplicationStatus\x121\x0A\x04mode\x18\x01 \x01(\x0E2#.replication_modepb.ReplicationMode\x124\x0A\x0Cdr_auto_sync\x18\x02 \x01(\x0B2\x1E.replication_modepb.DRAutoSyncJ\x06\x08\xE8\x07\x10\xB0\x09\"\xBB\x01\x0A\x0ADRAutoSync\x12\x11\x0A\x09label_key\x18\x01 \x01(\x09\x122\x0A\x05state\x18\x02 \x01(\x0E2#.replication_modepb.DRAutoSyncState\x12\x10\x0A\x08state_id\x18\x03 \x01(\x04\x12\x1E\x0A\x16wait_sync_timeout_hint\x18\x04 \x01(\x05\x12\x18\x0A\x10available_stores\x18\x05 \x03(\x04\x12\x1A\x0A\x12pause_region_split\x18\x06 \x01(\x08\"f\x0A\x17RegionReplicationStatus\x129\x0A\x05state\x18\x01 \x01(\x0E2*.replication_modepb.RegionReplicationState\x12\x10\x0A\x08state_id\x18\x02 \x01(\x04\"]\x0A\x15StoreDRAutoSyncStatus\x122\x0A\x05state\x18\x01 \x01(\x0E2#.replication_modepb.DRAutoSyncState\x12\x10\x0A\x08state_id\x18\x02 \x01(\x04*1\x0A\x0FReplicationMode\x12\x0C\x0A\x08MAJORITY\x10\x00\x12\x10\x0A\x0CDR_AUTO_SYNC\x10\x01*H\x0A\x0FDRAutoSyncState\x12\x08\x0A\x04SYNC\x10\x00\x12\x0E\x0A\x0AASYNC_WAIT\x10\x01\x12\x09\x0A\x05ASYNC\x10\x02\x12\x10\x0A\x0CSYNC_RECOVER\x10\x03*T\x0A\x16RegionReplicationState\x12\x0B\x0A\x07UNKNOWN\x10\x00\x12\x13\x0A\x0FSIMPLE_MAJORITY\x10\x01\x12\x18\x0A\x14INTEGRITY_OVER_LABEL\x10\x02BB\xCA\x02!CrazyGoat\\Proto\\ReplicationModepb\xE2\x02\x1BCrazyGoat\\Proto\\GPBMetadatab\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

