<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pdpb.proto

namespace CrazyGoat\Proto\Pdpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pdpb.AskBatchSplitRequest</code>
 */
class AskBatchSplitRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.pdpb.RequestHeader header = 1;</code>
     */
    protected $header = null;
    /**
     * Generated from protobuf field <code>.metapb.Region region = 2;</code>
     */
    protected $region = null;
    /**
     * Generated from protobuf field <code>uint32 split_count = 3;</code>
     */
    protected $split_count = 0;
    /**
     * Generated from protobuf field <code>.pdpb.SplitReason reason = 4;</code>
     */
    protected $reason = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CrazyGoat\Proto\Pdpb\RequestHeader $header
     *     @type \CrazyGoat\Proto\Metapb\Region $region
     *     @type int $split_count
     *     @type int $reason
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Pdpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.pdpb.RequestHeader header = 1;</code>
     * @return \CrazyGoat\Proto\Pdpb\RequestHeader|null
     */
    public function getHeader()
    {
        return $this->header;
    }

    public function hasHeader()
    {
        return isset($this->header);
    }

    public function clearHeader()
    {
        unset($this->header);
    }

    /**
     * Generated from protobuf field <code>.pdpb.RequestHeader header = 1;</code>
     * @param \CrazyGoat\Proto\Pdpb\RequestHeader $var
     * @return $this
     */
    public function setHeader(\CrazyGoat\Proto\Pdpb\RequestHeader|null $var)
    {
        $this->header = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.metapb.Region region = 2;</code>
     * @return \CrazyGoat\Proto\Metapb\Region|null
     */
    public function getRegion()
    {
        return $this->region;
    }

    public function hasRegion()
    {
        return isset($this->region);
    }

    public function clearRegion()
    {
        unset($this->region);
    }

    /**
     * Generated from protobuf field <code>.metapb.Region region = 2;</code>
     * @param \CrazyGoat\Proto\Metapb\Region $var
     * @return $this
     */
    public function setRegion(\CrazyGoat\Proto\Metapb\Region|null $var)
    {
        $this->region = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 split_count = 3;</code>
     * @return int
     */
    public function getSplitCount()
    {
        return $this->split_count;
    }

    /**
     * Generated from protobuf field <code>uint32 split_count = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setSplitCount(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->split_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pdpb.SplitReason reason = 4;</code>
     * @return int one of the values in {@see \CrazyGoat\Proto\Pdpb\SplitReason}
     */
    public function getReason()
    {
        return $this->reason;
    }

    /**
     * Generated from protobuf field <code>.pdpb.SplitReason reason = 4;</code>
     * @param int $var one of the values in {@see \CrazyGoat\Proto\Pdpb\SplitReason}
     * @return $this
     */
    public function setReason(int $var)
    {
        GPBUtil::checkEnum($var, \CrazyGoat\Proto\Pdpb\SplitReason::class);
        $this->reason = $var;

        return $this;
    }

}

