<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pdpb.proto

namespace CrazyGoat\Proto\Pdpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pdpb.ChangePeer</code>
 */
class ChangePeer extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.metapb.Peer peer = 1;</code>
     */
    protected $peer = null;
    /**
     * Generated from protobuf field <code>.eraftpb.ConfChangeType change_type = 2;</code>
     */
    protected $change_type = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CrazyGoat\Proto\Metapb\Peer $peer
     *     @type int $change_type
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Pdpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.metapb.Peer peer = 1;</code>
     * @return \CrazyGoat\Proto\Metapb\Peer|null
     */
    public function getPeer()
    {
        return $this->peer;
    }

    public function hasPeer()
    {
        return isset($this->peer);
    }

    public function clearPeer()
    {
        unset($this->peer);
    }

    /**
     * Generated from protobuf field <code>.metapb.Peer peer = 1;</code>
     * @param \CrazyGoat\Proto\Metapb\Peer $var
     * @return $this
     */
    public function setPeer(\CrazyGoat\Proto\Metapb\Peer|null $var)
    {
        $this->peer = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.eraftpb.ConfChangeType change_type = 2;</code>
     * @return int one of the values in {@see \CrazyGoat\Proto\Eraftpb\ConfChangeType}
     */
    public function getChangeType()
    {
        return $this->change_type;
    }

    /**
     * Generated from protobuf field <code>.eraftpb.ConfChangeType change_type = 2;</code>
     * @param int $var one of the values in {@see \CrazyGoat\Proto\Eraftpb\ConfChangeType}
     * @return $this
     */
    public function setChangeType(int $var)
    {
        GPBUtil::checkEnum($var, \CrazyGoat\Proto\Eraftpb\ConfChangeType::class);
        $this->change_type = $var;

        return $this;
    }

}

