<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pdpb.proto

namespace CrazyGoat\Proto\Pdpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pdpb.GetClusterInfoResponse</code>
 */
class GetClusterInfoResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.pdpb.ResponseHeader header = 1;</code>
     */
    protected $header = null;
    /**
     * Generated from protobuf field <code>repeated .pdpb.ServiceMode serviceModes = 2;</code>
     */
    private $serviceModes;
    /**
     * If service mode is API_SVC_MODE, this field will be set to the
     * registered tso service addresses.
     *
     * Generated from protobuf field <code>repeated string tso_urls = 3;</code>
     */
    private $tso_urls;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CrazyGoat\Proto\Pdpb\ResponseHeader $header
     *     @type int[] $serviceModes
     *     @type string[] $tso_urls
     *           If service mode is API_SVC_MODE, this field will be set to the
     *           registered tso service addresses.
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Pdpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.pdpb.ResponseHeader header = 1;</code>
     * @return \CrazyGoat\Proto\Pdpb\ResponseHeader|null
     */
    public function getHeader()
    {
        return $this->header;
    }

    public function hasHeader()
    {
        return isset($this->header);
    }

    public function clearHeader()
    {
        unset($this->header);
    }

    /**
     * Generated from protobuf field <code>.pdpb.ResponseHeader header = 1;</code>
     * @param \CrazyGoat\Proto\Pdpb\ResponseHeader $var
     * @return $this
     */
    public function setHeader(\CrazyGoat\Proto\Pdpb\ResponseHeader|null $var)
    {
        $this->header = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pdpb.ServiceMode serviceModes = 2;</code>
     * @return RepeatedField<int> one of the values in {@see \CrazyGoat\Proto\Pdpb\ServiceMode}
     */
    public function getServiceModes()
    {
        return $this->serviceModes;
    }

    /**
     * Generated from protobuf field <code>repeated .pdpb.ServiceMode serviceModes = 2;</code>
     * @param int[] $var one of the values in {@see \CrazyGoat\Proto\Pdpb\ServiceMode}
     * @return $this
     */
    public function setServiceModes(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \CrazyGoat\Proto\Pdpb\ServiceMode::class);
        $this->serviceModes = $arr;

        return $this;
    }

    /**
     * If service mode is API_SVC_MODE, this field will be set to the
     * registered tso service addresses.
     *
     * Generated from protobuf field <code>repeated string tso_urls = 3;</code>
     * @return RepeatedField<string>
     */
    public function getTsoUrls()
    {
        return $this->tso_urls;
    }

    /**
     * If service mode is API_SVC_MODE, this field will be set to the
     * registered tso service addresses.
     *
     * Generated from protobuf field <code>repeated string tso_urls = 3;</code>
     * @param string[] $var
     * @return $this
     */
    public function setTsoUrls(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->tso_urls = $arr;

        return $this;
    }

}

