<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: resource_manager.proto

namespace CrazyGoat\Proto\ResourceManager;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>resource_manager.Participant</code>
 */
class Participant extends \Google\Protobuf\Internal\Message
{
    /**
     * name is the unique name of the resource manager participant.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * id is the unique id of the resource manager participant.
     *
     * Generated from protobuf field <code>uint64 id = 2;</code>
     */
    protected $id = 0;
    /**
     * listen_urls is the serivce endpoint list in the url format.
     * listen_urls[0] is primary service endpoint.
     *
     * Generated from protobuf field <code>repeated string listen_urls = 3;</code>
     */
    private $listen_urls;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           name is the unique name of the resource manager participant.
     *     @type int|string $id
     *           id is the unique id of the resource manager participant.
     *     @type string[] $listen_urls
     *           listen_urls is the serivce endpoint list in the url format.
     *           listen_urls[0] is primary service endpoint.
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\ResourceManager::initOnce();
        parent::__construct($data);
    }

    /**
     * name is the unique name of the resource manager participant.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * name is the unique name of the resource manager participant.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * id is the unique id of the resource manager participant.
     *
     * Generated from protobuf field <code>uint64 id = 2;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * id is the unique id of the resource manager participant.
     *
     * Generated from protobuf field <code>uint64 id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * listen_urls is the serivce endpoint list in the url format.
     * listen_urls[0] is primary service endpoint.
     *
     * Generated from protobuf field <code>repeated string listen_urls = 3;</code>
     * @return RepeatedField<string>
     */
    public function getListenUrls()
    {
        return $this->listen_urls;
    }

    /**
     * listen_urls is the serivce endpoint list in the url format.
     * listen_urls[0] is primary service endpoint.
     *
     * Generated from protobuf field <code>repeated string listen_urls = 3;</code>
     * @param string[] $var
     * @return $this
     */
    public function setListenUrls(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->listen_urls = $arr;

        return $this;
    }

}

