<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brpb.proto

namespace CrazyGoat\Proto\Backup;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * AzureBlobStorage storage backend saves files into azure blob storage.
 *
 * Generated from protobuf message <code>backup.AzureBlobStorage</code>
 */
class AzureBlobStorage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string endpoint = 1;</code>
     */
    protected $endpoint = '';
    /**
     * Alias: container
     *
     * Generated from protobuf field <code>string bucket = 2;</code>
     */
    protected $bucket = '';
    /**
     * Notice: prefix starts without `/`, otherwise the first directory's name is empty.
     *
     * Generated from protobuf field <code>string prefix = 3;</code>
     */
    protected $prefix = '';
    /**
     * Alias: access_tier.
     * See https://docs.microsoft.com/en-us/azure/storage/blobs/access-tiers-overview
     *
     * Generated from protobuf field <code>string storage_class = 4;</code>
     */
    protected $storage_class = '';
    /**
     * if empty, try to read account_name from the node's environment variable $AZURE_STORAGE_ACCOUNT.
     *
     * Generated from protobuf field <code>string account_name = 5;</code>
     */
    protected $account_name = '';
    /**
     * There are 3 kinds of credentials, and the priority order is
     *   `SAS > Shared key > Azure AD (env) > Shared key (env)`.
     * 1. Use shared key to access the azure blob
     * If the node's environment variables($AZURE_CLIENT_ID, $AZURE_TENANT_ID, $AZURE_CLIENT_SECRET) exist,
     * prefer to use token to access the azure blob.
     *   See https://learn.microsoft.com/en-us/rest/api/storageservices/authorize-with-shared-key
     * Otherwise, if empty, try to read shared key from the node's environment variable $AZURE_STORAGE_KEY.
     *
     * Generated from protobuf field <code>string shared_key = 6;</code>
     */
    protected $shared_key = '';
    /**
     * 2. Use Azure AD (Azure Active Directory) to access the azure blob
     *   See https://learn.microsoft.com/en-us/rest/api/storageservices/authorize-with-azure-active-directory
     * The Azure AD would generate the token, which tasks some time.
     * So it is not recommanded to generate the token in each request.
     * // AzureActiveDirectory azure_ad = #;
     * 3. Use SAS (shared access signature)
     *   See https://learn.microsoft.com/en-us/rest/api/storageservices/delegate-access-with-shared-access-signature
     *
     * Generated from protobuf field <code>string access_sig = 8;</code>
     */
    protected $access_sig = '';
    /**
     * Server Side Encryption, 2 types in total:
     * 1. Specify an encryption scope for uploaded blobs.
     *   See https://learn.microsoft.com/en-us/azure/storage/blobs/encryption-scope-manage?tabs=powershell#upload-a-blob-with-an-encryption-scope
     *
     * Generated from protobuf field <code>string encryption_scope = 9;</code>
     */
    protected $encryption_scope = '';
    /**
     * 2. Provide an encryption key on a request to blob storage.
     *   See https://learn.microsoft.com/en-us/azure/storage/blobs/encryption-customer-provided-keys
     *
     * Generated from protobuf field <code>.backup.AzureCustomerKey encryption_key = 10;</code>
     */
    protected $encryption_key = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $endpoint
     *     @type string $bucket
     *           Alias: container
     *     @type string $prefix
     *           Notice: prefix starts without `/`, otherwise the first directory's name is empty.
     *     @type string $storage_class
     *           Alias: access_tier.
     *           See https://docs.microsoft.com/en-us/azure/storage/blobs/access-tiers-overview
     *     @type string $account_name
     *           if empty, try to read account_name from the node's environment variable $AZURE_STORAGE_ACCOUNT.
     *     @type string $shared_key
     *           There are 3 kinds of credentials, and the priority order is
     *             `SAS > Shared key > Azure AD (env) > Shared key (env)`.
     *           1. Use shared key to access the azure blob
     *           If the node's environment variables($AZURE_CLIENT_ID, $AZURE_TENANT_ID, $AZURE_CLIENT_SECRET) exist,
     *           prefer to use token to access the azure blob.
     *             See https://learn.microsoft.com/en-us/rest/api/storageservices/authorize-with-shared-key
     *           Otherwise, if empty, try to read shared key from the node's environment variable $AZURE_STORAGE_KEY.
     *     @type string $access_sig
     *           2. Use Azure AD (Azure Active Directory) to access the azure blob
     *             See https://learn.microsoft.com/en-us/rest/api/storageservices/authorize-with-azure-active-directory
     *           The Azure AD would generate the token, which tasks some time.
     *           So it is not recommanded to generate the token in each request.
     *           // AzureActiveDirectory azure_ad = #;
     *           3. Use SAS (shared access signature)
     *             See https://learn.microsoft.com/en-us/rest/api/storageservices/delegate-access-with-shared-access-signature
     *     @type string $encryption_scope
     *           Server Side Encryption, 2 types in total:
     *           1. Specify an encryption scope for uploaded blobs.
     *             See https://learn.microsoft.com/en-us/azure/storage/blobs/encryption-scope-manage?tabs=powershell#upload-a-blob-with-an-encryption-scope
     *     @type \CrazyGoat\Proto\Backup\AzureCustomerKey $encryption_key
     *           2. Provide an encryption key on a request to blob storage.
     *             See https://learn.microsoft.com/en-us/azure/storage/blobs/encryption-customer-provided-keys
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Brpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string endpoint = 1;</code>
     * @return string
     */
    public function getEndpoint()
    {
        return $this->endpoint;
    }

    /**
     * Generated from protobuf field <code>string endpoint = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setEndpoint(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->endpoint = $var;

        return $this;
    }

    /**
     * Alias: container
     *
     * Generated from protobuf field <code>string bucket = 2;</code>
     * @return string
     */
    public function getBucket()
    {
        return $this->bucket;
    }

    /**
     * Alias: container
     *
     * Generated from protobuf field <code>string bucket = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setBucket(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->bucket = $var;

        return $this;
    }

    /**
     * Notice: prefix starts without `/`, otherwise the first directory's name is empty.
     *
     * Generated from protobuf field <code>string prefix = 3;</code>
     * @return string
     */
    public function getPrefix()
    {
        return $this->prefix;
    }

    /**
     * Notice: prefix starts without `/`, otherwise the first directory's name is empty.
     *
     * Generated from protobuf field <code>string prefix = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPrefix(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->prefix = $var;

        return $this;
    }

    /**
     * Alias: access_tier.
     * See https://docs.microsoft.com/en-us/azure/storage/blobs/access-tiers-overview
     *
     * Generated from protobuf field <code>string storage_class = 4;</code>
     * @return string
     */
    public function getStorageClass()
    {
        return $this->storage_class;
    }

    /**
     * Alias: access_tier.
     * See https://docs.microsoft.com/en-us/azure/storage/blobs/access-tiers-overview
     *
     * Generated from protobuf field <code>string storage_class = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setStorageClass(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->storage_class = $var;

        return $this;
    }

    /**
     * if empty, try to read account_name from the node's environment variable $AZURE_STORAGE_ACCOUNT.
     *
     * Generated from protobuf field <code>string account_name = 5;</code>
     * @return string
     */
    public function getAccountName()
    {
        return $this->account_name;
    }

    /**
     * if empty, try to read account_name from the node's environment variable $AZURE_STORAGE_ACCOUNT.
     *
     * Generated from protobuf field <code>string account_name = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setAccountName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->account_name = $var;

        return $this;
    }

    /**
     * There are 3 kinds of credentials, and the priority order is
     *   `SAS > Shared key > Azure AD (env) > Shared key (env)`.
     * 1. Use shared key to access the azure blob
     * If the node's environment variables($AZURE_CLIENT_ID, $AZURE_TENANT_ID, $AZURE_CLIENT_SECRET) exist,
     * prefer to use token to access the azure blob.
     *   See https://learn.microsoft.com/en-us/rest/api/storageservices/authorize-with-shared-key
     * Otherwise, if empty, try to read shared key from the node's environment variable $AZURE_STORAGE_KEY.
     *
     * Generated from protobuf field <code>string shared_key = 6;</code>
     * @return string
     */
    public function getSharedKey()
    {
        return $this->shared_key;
    }

    /**
     * There are 3 kinds of credentials, and the priority order is
     *   `SAS > Shared key > Azure AD (env) > Shared key (env)`.
     * 1. Use shared key to access the azure blob
     * If the node's environment variables($AZURE_CLIENT_ID, $AZURE_TENANT_ID, $AZURE_CLIENT_SECRET) exist,
     * prefer to use token to access the azure blob.
     *   See https://learn.microsoft.com/en-us/rest/api/storageservices/authorize-with-shared-key
     * Otherwise, if empty, try to read shared key from the node's environment variable $AZURE_STORAGE_KEY.
     *
     * Generated from protobuf field <code>string shared_key = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setSharedKey(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->shared_key = $var;

        return $this;
    }

    /**
     * 2. Use Azure AD (Azure Active Directory) to access the azure blob
     *   See https://learn.microsoft.com/en-us/rest/api/storageservices/authorize-with-azure-active-directory
     * The Azure AD would generate the token, which tasks some time.
     * So it is not recommanded to generate the token in each request.
     * // AzureActiveDirectory azure_ad = #;
     * 3. Use SAS (shared access signature)
     *   See https://learn.microsoft.com/en-us/rest/api/storageservices/delegate-access-with-shared-access-signature
     *
     * Generated from protobuf field <code>string access_sig = 8;</code>
     * @return string
     */
    public function getAccessSig()
    {
        return $this->access_sig;
    }

    /**
     * 2. Use Azure AD (Azure Active Directory) to access the azure blob
     *   See https://learn.microsoft.com/en-us/rest/api/storageservices/authorize-with-azure-active-directory
     * The Azure AD would generate the token, which tasks some time.
     * So it is not recommanded to generate the token in each request.
     * // AzureActiveDirectory azure_ad = #;
     * 3. Use SAS (shared access signature)
     *   See https://learn.microsoft.com/en-us/rest/api/storageservices/delegate-access-with-shared-access-signature
     *
     * Generated from protobuf field <code>string access_sig = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setAccessSig(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->access_sig = $var;

        return $this;
    }

    /**
     * Server Side Encryption, 2 types in total:
     * 1. Specify an encryption scope for uploaded blobs.
     *   See https://learn.microsoft.com/en-us/azure/storage/blobs/encryption-scope-manage?tabs=powershell#upload-a-blob-with-an-encryption-scope
     *
     * Generated from protobuf field <code>string encryption_scope = 9;</code>
     * @return string
     */
    public function getEncryptionScope()
    {
        return $this->encryption_scope;
    }

    /**
     * Server Side Encryption, 2 types in total:
     * 1. Specify an encryption scope for uploaded blobs.
     *   See https://learn.microsoft.com/en-us/azure/storage/blobs/encryption-scope-manage?tabs=powershell#upload-a-blob-with-an-encryption-scope
     *
     * Generated from protobuf field <code>string encryption_scope = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setEncryptionScope(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->encryption_scope = $var;

        return $this;
    }

    /**
     * 2. Provide an encryption key on a request to blob storage.
     *   See https://learn.microsoft.com/en-us/azure/storage/blobs/encryption-customer-provided-keys
     *
     * Generated from protobuf field <code>.backup.AzureCustomerKey encryption_key = 10;</code>
     * @return \CrazyGoat\Proto\Backup\AzureCustomerKey|null
     */
    public function getEncryptionKey()
    {
        return $this->encryption_key;
    }

    public function hasEncryptionKey()
    {
        return isset($this->encryption_key);
    }

    public function clearEncryptionKey()
    {
        unset($this->encryption_key);
    }

    /**
     * 2. Provide an encryption key on a request to blob storage.
     *   See https://learn.microsoft.com/en-us/azure/storage/blobs/encryption-customer-provided-keys
     *
     * Generated from protobuf field <code>.backup.AzureCustomerKey encryption_key = 10;</code>
     * @param \CrazyGoat\Proto\Backup\AzureCustomerKey $var
     * @return $this
     */
    public function setEncryptionKey(\CrazyGoat\Proto\Backup\AzureCustomerKey|null $var)
    {
        $this->encryption_key = $var;

        return $this;
    }

}

