<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brpb.proto

namespace CrazyGoat\Proto\Backup;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>backup.BackupRequest</code>
 */
class BackupRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 cluster_id = 1;</code>
     */
    protected $cluster_id = 0;
    /**
     * Generated from protobuf field <code>bytes start_key = 2;</code>
     */
    protected $start_key = '';
    /**
     * Generated from protobuf field <code>bytes end_key = 3;</code>
     */
    protected $end_key = '';
    /**
     * Generated from protobuf field <code>uint64 start_version = 4;</code>
     */
    protected $start_version = 0;
    /**
     * Generated from protobuf field <code>uint64 end_version = 5;</code>
     */
    protected $end_version = 0;
    /**
     * The I/O rate limit for backup request.
     *
     * Generated from protobuf field <code>uint64 rate_limit = 7;</code>
     */
    protected $rate_limit = 0;
    /**
     * The concurrency for executing the backup request in every tikv node.
     *
     * Generated from protobuf field <code>uint32 concurrency = 8;</code>
     */
    protected $concurrency = 0;
    /**
     * Generated from protobuf field <code>.backup.StorageBackend storage_backend = 9;</code>
     */
    protected $storage_backend = null;
    /**
     * If raw kv mode is enabled, `start_version` and `end_version` will be ignored, and `cf`
     * specifies which cf to backup.
     *
     * Generated from protobuf field <code>bool is_raw_kv = 10;</code>
     */
    protected $is_raw_kv = false;
    /**
     * Generated from protobuf field <code>string cf = 11;</code>
     */
    protected $cf = '';
    /**
     * algorithm used for compress sst files
     *
     * Generated from protobuf field <code>.backup.CompressionType compression_type = 12;</code>
     */
    protected $compression_type = 0;
    /**
     * sst compression level, some algorithms support negative compression levels
     *
     * Generated from protobuf field <code>int32 compression_level = 13;</code>
     */
    protected $compression_level = 0;
    /**
     * The cipher_info is Used to encrypt sst
     *
     * Generated from protobuf field <code>.backup.CipherInfo cipher_info = 14;</code>
     */
    protected $cipher_info = null;
    /**
     * dst_api_version indicates the key-value encoding version used by the
     * generated SST file. Accepted values:
     * 1. "v1": the generated SST files are encoded with api-v1, can be restored
     *    to TiKV clusters whose api version is set to v1.
     * 2. "v2": the generated SST files are encoded with api-v2, can be restored
     *    to TiKV clusters whose api version is set to v2.
     *
     * Generated from protobuf field <code>.kvrpcpb.APIVersion dst_api_version = 15;</code>
     */
    protected $dst_api_version = 0;
    /**
     * with checkpoint, some subintervals of the range have been backed up and recorded.
     * only the remaining sub ranges of the range need to be backed up this time.
     *
     * Generated from protobuf field <code>repeated .kvrpcpb.KeyRange sub_ranges = 16;</code>
     */
    private $sub_ranges;
    /**
     * only ranges in the same groups can be merged into one SST file.
     * the ranges in each groups are sorted.
     *
     * Generated from protobuf field <code>repeated .backup.SortedSubRanges sorted_sub_ranges_groups = 21;</code>
     */
    private $sorted_sub_ranges_groups;
    /**
     * replica_read indicates whether to use replica read for backup.
     * If it is false, the backup will only read data from leader.
     * If it is true, the backup will read data from both leader and follower.
     *
     * Generated from protobuf field <code>bool replica_read = 17;</code>
     */
    protected $replica_read = false;
    /**
     * Generated from protobuf field <code>.backup.BackupMode mode = 18;</code>
     */
    protected $mode = 0;
    /**
     * unique_id represents the handle of this backup. after we implement file-copy backup.
     * we need generate some internal states during the whole backup precedure.
     * this unique id is help to find the state effictively.
     *
     * Generated from protobuf field <code>string unique_id = 19;</code>
     */
    protected $unique_id = '';
    /**
     * Generated from protobuf field <code>.kvrpcpb.Context context = 20;</code>
     */
    protected $context = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $cluster_id
     *     @type string $start_key
     *     @type string $end_key
     *     @type int|string $start_version
     *     @type int|string $end_version
     *     @type int|string $rate_limit
     *           The I/O rate limit for backup request.
     *     @type int $concurrency
     *           The concurrency for executing the backup request in every tikv node.
     *     @type \CrazyGoat\Proto\Backup\StorageBackend $storage_backend
     *     @type bool $is_raw_kv
     *           If raw kv mode is enabled, `start_version` and `end_version` will be ignored, and `cf`
     *           specifies which cf to backup.
     *     @type string $cf
     *     @type int $compression_type
     *           algorithm used for compress sst files
     *     @type int $compression_level
     *           sst compression level, some algorithms support negative compression levels
     *     @type \CrazyGoat\Proto\Backup\CipherInfo $cipher_info
     *           The cipher_info is Used to encrypt sst
     *     @type int $dst_api_version
     *           dst_api_version indicates the key-value encoding version used by the
     *           generated SST file. Accepted values:
     *           1. "v1": the generated SST files are encoded with api-v1, can be restored
     *              to TiKV clusters whose api version is set to v1.
     *           2. "v2": the generated SST files are encoded with api-v2, can be restored
     *              to TiKV clusters whose api version is set to v2.
     *     @type \CrazyGoat\Proto\Kvrpcpb\KeyRange[] $sub_ranges
     *           with checkpoint, some subintervals of the range have been backed up and recorded.
     *           only the remaining sub ranges of the range need to be backed up this time.
     *     @type \CrazyGoat\Proto\Backup\SortedSubRanges[] $sorted_sub_ranges_groups
     *           only ranges in the same groups can be merged into one SST file.
     *           the ranges in each groups are sorted.
     *     @type bool $replica_read
     *           replica_read indicates whether to use replica read for backup.
     *           If it is false, the backup will only read data from leader.
     *           If it is true, the backup will read data from both leader and follower.
     *     @type int $mode
     *     @type string $unique_id
     *           unique_id represents the handle of this backup. after we implement file-copy backup.
     *           we need generate some internal states during the whole backup precedure.
     *           this unique id is help to find the state effictively.
     *     @type \CrazyGoat\Proto\Kvrpcpb\Context $context
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Brpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 cluster_id = 1;</code>
     * @return int|string
     */
    public function getClusterId()
    {
        return $this->cluster_id;
    }

    /**
     * Generated from protobuf field <code>uint64 cluster_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setClusterId(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->cluster_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes start_key = 2;</code>
     * @return string
     */
    public function getStartKey()
    {
        return $this->start_key;
    }

    /**
     * Generated from protobuf field <code>bytes start_key = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setStartKey(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->start_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes end_key = 3;</code>
     * @return string
     */
    public function getEndKey()
    {
        return $this->end_key;
    }

    /**
     * Generated from protobuf field <code>bytes end_key = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setEndKey(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->end_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 start_version = 4;</code>
     * @return int|string
     */
    public function getStartVersion()
    {
        return $this->start_version;
    }

    /**
     * Generated from protobuf field <code>uint64 start_version = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStartVersion(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->start_version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 end_version = 5;</code>
     * @return int|string
     */
    public function getEndVersion()
    {
        return $this->end_version;
    }

    /**
     * Generated from protobuf field <code>uint64 end_version = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEndVersion(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->end_version = $var;

        return $this;
    }

    /**
     * The I/O rate limit for backup request.
     *
     * Generated from protobuf field <code>uint64 rate_limit = 7;</code>
     * @return int|string
     */
    public function getRateLimit()
    {
        return $this->rate_limit;
    }

    /**
     * The I/O rate limit for backup request.
     *
     * Generated from protobuf field <code>uint64 rate_limit = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRateLimit(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->rate_limit = $var;

        return $this;
    }

    /**
     * The concurrency for executing the backup request in every tikv node.
     *
     * Generated from protobuf field <code>uint32 concurrency = 8;</code>
     * @return int
     */
    public function getConcurrency()
    {
        return $this->concurrency;
    }

    /**
     * The concurrency for executing the backup request in every tikv node.
     *
     * Generated from protobuf field <code>uint32 concurrency = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setConcurrency(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->concurrency = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.backup.StorageBackend storage_backend = 9;</code>
     * @return \CrazyGoat\Proto\Backup\StorageBackend|null
     */
    public function getStorageBackend()
    {
        return $this->storage_backend;
    }

    public function hasStorageBackend()
    {
        return isset($this->storage_backend);
    }

    public function clearStorageBackend()
    {
        unset($this->storage_backend);
    }

    /**
     * Generated from protobuf field <code>.backup.StorageBackend storage_backend = 9;</code>
     * @param \CrazyGoat\Proto\Backup\StorageBackend $var
     * @return $this
     */
    public function setStorageBackend(\CrazyGoat\Proto\Backup\StorageBackend|null $var)
    {
        $this->storage_backend = $var;

        return $this;
    }

    /**
     * If raw kv mode is enabled, `start_version` and `end_version` will be ignored, and `cf`
     * specifies which cf to backup.
     *
     * Generated from protobuf field <code>bool is_raw_kv = 10;</code>
     * @return bool
     */
    public function getIsRawKv()
    {
        return $this->is_raw_kv;
    }

    /**
     * If raw kv mode is enabled, `start_version` and `end_version` will be ignored, and `cf`
     * specifies which cf to backup.
     *
     * Generated from protobuf field <code>bool is_raw_kv = 10;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsRawKv(bool $var)
    {
        $this->is_raw_kv = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string cf = 11;</code>
     * @return string
     */
    public function getCf()
    {
        return $this->cf;
    }

    /**
     * Generated from protobuf field <code>string cf = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setCf(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->cf = $var;

        return $this;
    }

    /**
     * algorithm used for compress sst files
     *
     * Generated from protobuf field <code>.backup.CompressionType compression_type = 12;</code>
     * @return int one of the values in {@see \CrazyGoat\Proto\Backup\CompressionType}
     */
    public function getCompressionType()
    {
        return $this->compression_type;
    }

    /**
     * algorithm used for compress sst files
     *
     * Generated from protobuf field <code>.backup.CompressionType compression_type = 12;</code>
     * @param int $var one of the values in {@see \CrazyGoat\Proto\Backup\CompressionType}
     * @return $this
     */
    public function setCompressionType(int $var)
    {
        GPBUtil::checkEnum($var, \CrazyGoat\Proto\Backup\CompressionType::class);
        $this->compression_type = $var;

        return $this;
    }

    /**
     * sst compression level, some algorithms support negative compression levels
     *
     * Generated from protobuf field <code>int32 compression_level = 13;</code>
     * @return int
     */
    public function getCompressionLevel()
    {
        return $this->compression_level;
    }

    /**
     * sst compression level, some algorithms support negative compression levels
     *
     * Generated from protobuf field <code>int32 compression_level = 13;</code>
     * @param int $var
     * @return $this
     */
    public function setCompressionLevel(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->compression_level = $var;

        return $this;
    }

    /**
     * The cipher_info is Used to encrypt sst
     *
     * Generated from protobuf field <code>.backup.CipherInfo cipher_info = 14;</code>
     * @return \CrazyGoat\Proto\Backup\CipherInfo|null
     */
    public function getCipherInfo()
    {
        return $this->cipher_info;
    }

    public function hasCipherInfo()
    {
        return isset($this->cipher_info);
    }

    public function clearCipherInfo()
    {
        unset($this->cipher_info);
    }

    /**
     * The cipher_info is Used to encrypt sst
     *
     * Generated from protobuf field <code>.backup.CipherInfo cipher_info = 14;</code>
     * @param \CrazyGoat\Proto\Backup\CipherInfo $var
     * @return $this
     */
    public function setCipherInfo(\CrazyGoat\Proto\Backup\CipherInfo|null $var)
    {
        $this->cipher_info = $var;

        return $this;
    }

    /**
     * dst_api_version indicates the key-value encoding version used by the
     * generated SST file. Accepted values:
     * 1. "v1": the generated SST files are encoded with api-v1, can be restored
     *    to TiKV clusters whose api version is set to v1.
     * 2. "v2": the generated SST files are encoded with api-v2, can be restored
     *    to TiKV clusters whose api version is set to v2.
     *
     * Generated from protobuf field <code>.kvrpcpb.APIVersion dst_api_version = 15;</code>
     * @return int one of the values in {@see \CrazyGoat\Proto\Kvrpcpb\APIVersion}
     */
    public function getDstApiVersion()
    {
        return $this->dst_api_version;
    }

    /**
     * dst_api_version indicates the key-value encoding version used by the
     * generated SST file. Accepted values:
     * 1. "v1": the generated SST files are encoded with api-v1, can be restored
     *    to TiKV clusters whose api version is set to v1.
     * 2. "v2": the generated SST files are encoded with api-v2, can be restored
     *    to TiKV clusters whose api version is set to v2.
     *
     * Generated from protobuf field <code>.kvrpcpb.APIVersion dst_api_version = 15;</code>
     * @param int $var one of the values in {@see \CrazyGoat\Proto\Kvrpcpb\APIVersion}
     * @return $this
     */
    public function setDstApiVersion(int $var)
    {
        GPBUtil::checkEnum($var, \CrazyGoat\Proto\Kvrpcpb\APIVersion::class);
        $this->dst_api_version = $var;

        return $this;
    }

    /**
     * with checkpoint, some subintervals of the range have been backed up and recorded.
     * only the remaining sub ranges of the range need to be backed up this time.
     *
     * Generated from protobuf field <code>repeated .kvrpcpb.KeyRange sub_ranges = 16;</code>
     * @return RepeatedField<\CrazyGoat\Proto\Kvrpcpb\KeyRange>
     */
    public function getSubRanges()
    {
        return $this->sub_ranges;
    }

    /**
     * with checkpoint, some subintervals of the range have been backed up and recorded.
     * only the remaining sub ranges of the range need to be backed up this time.
     *
     * Generated from protobuf field <code>repeated .kvrpcpb.KeyRange sub_ranges = 16;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\KeyRange[] $var
     * @return $this
     */
    public function setSubRanges(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \CrazyGoat\Proto\Kvrpcpb\KeyRange::class);
        $this->sub_ranges = $arr;

        return $this;
    }

    /**
     * only ranges in the same groups can be merged into one SST file.
     * the ranges in each groups are sorted.
     *
     * Generated from protobuf field <code>repeated .backup.SortedSubRanges sorted_sub_ranges_groups = 21;</code>
     * @return RepeatedField<\CrazyGoat\Proto\Backup\SortedSubRanges>
     */
    public function getSortedSubRangesGroups()
    {
        return $this->sorted_sub_ranges_groups;
    }

    /**
     * only ranges in the same groups can be merged into one SST file.
     * the ranges in each groups are sorted.
     *
     * Generated from protobuf field <code>repeated .backup.SortedSubRanges sorted_sub_ranges_groups = 21;</code>
     * @param \CrazyGoat\Proto\Backup\SortedSubRanges[] $var
     * @return $this
     */
    public function setSortedSubRangesGroups(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \CrazyGoat\Proto\Backup\SortedSubRanges::class);
        $this->sorted_sub_ranges_groups = $arr;

        return $this;
    }

    /**
     * replica_read indicates whether to use replica read for backup.
     * If it is false, the backup will only read data from leader.
     * If it is true, the backup will read data from both leader and follower.
     *
     * Generated from protobuf field <code>bool replica_read = 17;</code>
     * @return bool
     */
    public function getReplicaRead()
    {
        return $this->replica_read;
    }

    /**
     * replica_read indicates whether to use replica read for backup.
     * If it is false, the backup will only read data from leader.
     * If it is true, the backup will read data from both leader and follower.
     *
     * Generated from protobuf field <code>bool replica_read = 17;</code>
     * @param bool $var
     * @return $this
     */
    public function setReplicaRead(bool $var)
    {
        $this->replica_read = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.backup.BackupMode mode = 18;</code>
     * @return int one of the values in {@see \CrazyGoat\Proto\Backup\BackupMode}
     */
    public function getMode()
    {
        return $this->mode;
    }

    /**
     * Generated from protobuf field <code>.backup.BackupMode mode = 18;</code>
     * @param int $var one of the values in {@see \CrazyGoat\Proto\Backup\BackupMode}
     * @return $this
     */
    public function setMode(int $var)
    {
        GPBUtil::checkEnum($var, \CrazyGoat\Proto\Backup\BackupMode::class);
        $this->mode = $var;

        return $this;
    }

    /**
     * unique_id represents the handle of this backup. after we implement file-copy backup.
     * we need generate some internal states during the whole backup precedure.
     * this unique id is help to find the state effictively.
     *
     * Generated from protobuf field <code>string unique_id = 19;</code>
     * @return string
     */
    public function getUniqueId()
    {
        return $this->unique_id;
    }

    /**
     * unique_id represents the handle of this backup. after we implement file-copy backup.
     * we need generate some internal states during the whole backup precedure.
     * this unique id is help to find the state effictively.
     *
     * Generated from protobuf field <code>string unique_id = 19;</code>
     * @param string $var
     * @return $this
     */
    public function setUniqueId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->unique_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.Context context = 20;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\Context|null
     */
    public function getContext()
    {
        return $this->context;
    }

    public function hasContext()
    {
        return isset($this->context);
    }

    public function clearContext()
    {
        unset($this->context);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.Context context = 20;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\Context $var
     * @return $this
     */
    public function setContext(\CrazyGoat\Proto\Kvrpcpb\Context|null $var)
    {
        $this->context = $var;

        return $this;
    }

}

