<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brpb.proto

namespace CrazyGoat\Proto\Backup;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>backup.BackupResponse</code>
 */
class BackupResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.backup.Error error = 1;</code>
     */
    protected $error = null;
    /**
     * Generated from protobuf field <code>bytes start_key = 2;</code>
     */
    protected $start_key = '';
    /**
     * Generated from protobuf field <code>bytes end_key = 3;</code>
     */
    protected $end_key = '';
    /**
     * Generated from protobuf field <code>repeated .backup.File files = 4;</code>
     */
    private $files;
    /**
     * API version implies the encode of the key and value.
     *
     * Generated from protobuf field <code>.kvrpcpb.APIVersion api_version = 5;</code>
     */
    protected $api_version = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CrazyGoat\Proto\Backup\Error $error
     *     @type string $start_key
     *     @type string $end_key
     *     @type \CrazyGoat\Proto\Backup\File[] $files
     *     @type int $api_version
     *           API version implies the encode of the key and value.
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Brpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.backup.Error error = 1;</code>
     * @return \CrazyGoat\Proto\Backup\Error|null
     */
    public function getError()
    {
        return $this->error;
    }

    public function hasError()
    {
        return isset($this->error);
    }

    public function clearError()
    {
        unset($this->error);
    }

    /**
     * Generated from protobuf field <code>.backup.Error error = 1;</code>
     * @param \CrazyGoat\Proto\Backup\Error $var
     * @return $this
     */
    public function setError(\CrazyGoat\Proto\Backup\Error|null $var)
    {
        $this->error = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes start_key = 2;</code>
     * @return string
     */
    public function getStartKey()
    {
        return $this->start_key;
    }

    /**
     * Generated from protobuf field <code>bytes start_key = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setStartKey(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->start_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes end_key = 3;</code>
     * @return string
     */
    public function getEndKey()
    {
        return $this->end_key;
    }

    /**
     * Generated from protobuf field <code>bytes end_key = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setEndKey(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->end_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .backup.File files = 4;</code>
     * @return RepeatedField<\CrazyGoat\Proto\Backup\File>
     */
    public function getFiles()
    {
        return $this->files;
    }

    /**
     * Generated from protobuf field <code>repeated .backup.File files = 4;</code>
     * @param \CrazyGoat\Proto\Backup\File[] $var
     * @return $this
     */
    public function setFiles(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \CrazyGoat\Proto\Backup\File::class);
        $this->files = $arr;

        return $this;
    }

    /**
     * API version implies the encode of the key and value.
     *
     * Generated from protobuf field <code>.kvrpcpb.APIVersion api_version = 5;</code>
     * @return int one of the values in {@see \CrazyGoat\Proto\Kvrpcpb\APIVersion}
     */
    public function getApiVersion()
    {
        return $this->api_version;
    }

    /**
     * API version implies the encode of the key and value.
     *
     * Generated from protobuf field <code>.kvrpcpb.APIVersion api_version = 5;</code>
     * @param int $var one of the values in {@see \CrazyGoat\Proto\Kvrpcpb\APIVersion}
     * @return $this
     */
    public function setApiVersion(int $var)
    {
        GPBUtil::checkEnum($var, \CrazyGoat\Proto\Kvrpcpb\APIVersion::class);
        $this->api_version = $var;

        return $this;
    }

}

