<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brpb.proto

namespace CrazyGoat\Proto\Backup;

use UnexpectedValueException;

/**
 * BackupMpde represents the mode of this whole backup request to the cluster.
 * and we need to store it in `backupmeta`.
 *
 * Protobuf type <code>backup.BackupMode</code>
 */
class BackupMode
{
    /**
     * scan and generate precise SST file of a backup range.
     * then we don't need to do anything in future restore.
     * Note: this mode will cost the CPU resource of TiKV.
     *
     * Generated from protobuf enum <code>SCAN = 0;</code>
     */
    const SCAN = 0;
    /**
     * check and upload the coarse overlap SST files of a backup range.
     * then we need to use a merge iterator to filter unexpected kv in future restore.
     * Note: this mode will save the CPU resource of TiKV.
     *
     * Generated from protobuf enum <code>FILE = 1;</code>
     */
    const FILE = 1;

    private static $valueToName = [
        self::SCAN => 'SCAN',
        self::FILE => 'FILE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

