<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brpb.proto

namespace CrazyGoat\Proto\Backup;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>backup.Bucket</code>
 */
class Bucket extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string endpoint = 1;</code>
     */
    protected $endpoint = '';
    /**
     * Generated from protobuf field <code>string region = 3;</code>
     */
    protected $region = '';
    /**
     * Generated from protobuf field <code>string bucket = 4;</code>
     */
    protected $bucket = '';
    /**
     * Generated from protobuf field <code>string prefix = 5;</code>
     */
    protected $prefix = '';
    /**
     * Generated from protobuf field <code>string storage_class = 6;</code>
     */
    protected $storage_class = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $endpoint
     *     @type string $region
     *     @type string $bucket
     *     @type string $prefix
     *     @type string $storage_class
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Brpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string endpoint = 1;</code>
     * @return string
     */
    public function getEndpoint()
    {
        return $this->endpoint;
    }

    /**
     * Generated from protobuf field <code>string endpoint = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setEndpoint(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->endpoint = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string region = 3;</code>
     * @return string
     */
    public function getRegion()
    {
        return $this->region;
    }

    /**
     * Generated from protobuf field <code>string region = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setRegion(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->region = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string bucket = 4;</code>
     * @return string
     */
    public function getBucket()
    {
        return $this->bucket;
    }

    /**
     * Generated from protobuf field <code>string bucket = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setBucket(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->bucket = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string prefix = 5;</code>
     * @return string
     */
    public function getPrefix()
    {
        return $this->prefix;
    }

    /**
     * Generated from protobuf field <code>string prefix = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setPrefix(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->prefix = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string storage_class = 6;</code>
     * @return string
     */
    public function getStorageClass()
    {
        return $this->storage_class;
    }

    /**
     * Generated from protobuf field <code>string storage_class = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setStorageClass(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->storage_class = $var;

        return $this;
    }

}

