<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brpb.proto

namespace CrazyGoat\Proto\Backup;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>backup.CheckAdminResponse</code>
 */
class CheckAdminResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.backup.Error error = 1;</code>
     */
    protected $error = null;
    /**
     * Generated from protobuf field <code>.metapb.Region region = 2;</code>
     */
    protected $region = null;
    /**
     * Generated from protobuf field <code>bool has_pending_admin = 3;</code>
     */
    protected $has_pending_admin = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CrazyGoat\Proto\Backup\Error $error
     *     @type \CrazyGoat\Proto\Metapb\Region $region
     *     @type bool $has_pending_admin
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Brpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.backup.Error error = 1;</code>
     * @return \CrazyGoat\Proto\Backup\Error|null
     */
    public function getError()
    {
        return $this->error;
    }

    public function hasError()
    {
        return isset($this->error);
    }

    public function clearError()
    {
        unset($this->error);
    }

    /**
     * Generated from protobuf field <code>.backup.Error error = 1;</code>
     * @param \CrazyGoat\Proto\Backup\Error $var
     * @return $this
     */
    public function setError(\CrazyGoat\Proto\Backup\Error|null $var)
    {
        $this->error = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.metapb.Region region = 2;</code>
     * @return \CrazyGoat\Proto\Metapb\Region|null
     */
    public function getRegion()
    {
        return $this->region;
    }

    public function hasRegion()
    {
        return isset($this->region);
    }

    public function clearRegion()
    {
        unset($this->region);
    }

    /**
     * Generated from protobuf field <code>.metapb.Region region = 2;</code>
     * @param \CrazyGoat\Proto\Metapb\Region $var
     * @return $this
     */
    public function setRegion(\CrazyGoat\Proto\Metapb\Region|null $var)
    {
        $this->region = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool has_pending_admin = 3;</code>
     * @return bool
     */
    public function getHasPendingAdmin()
    {
        return $this->has_pending_admin;
    }

    /**
     * Generated from protobuf field <code>bool has_pending_admin = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setHasPendingAdmin(bool $var)
    {
        $this->has_pending_admin = $var;

        return $this;
    }

}

