<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brpb.proto

namespace CrazyGoat\Proto\Backup;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>backup.CipherInfo</code>
 */
class CipherInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.encryptionpb.EncryptionMethod cipher_type = 1;</code>
     */
    protected $cipher_type = 0;
    /**
     * Generated from protobuf field <code>bytes cipher_key = 2;</code>
     */
    protected $cipher_key = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $cipher_type
     *     @type string $cipher_key
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Brpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.encryptionpb.EncryptionMethod cipher_type = 1;</code>
     * @return int one of the values in {@see \CrazyGoat\Proto\Encryptionpb\EncryptionMethod}
     */
    public function getCipherType()
    {
        return $this->cipher_type;
    }

    /**
     * Generated from protobuf field <code>.encryptionpb.EncryptionMethod cipher_type = 1;</code>
     * @param int $var one of the values in {@see \CrazyGoat\Proto\Encryptionpb\EncryptionMethod}
     * @return $this
     */
    public function setCipherType(int $var)
    {
        GPBUtil::checkEnum($var, \CrazyGoat\Proto\Encryptionpb\EncryptionMethod::class);
        $this->cipher_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes cipher_key = 2;</code>
     * @return string
     */
    public function getCipherKey()
    {
        return $this->cipher_key;
    }

    /**
     * Generated from protobuf field <code>bytes cipher_key = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCipherKey(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->cipher_key = $var;

        return $this;
    }

}

