<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brpb.proto

namespace CrazyGoat\Proto\Backup;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>backup.CleanupResponse</code>
 */
class CleanupResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.backup.Error error = 1;</code>
     */
    protected $error = null;
    /**
     * Generated from protobuf field <code>bool success = 2;</code>
     */
    protected $success = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CrazyGoat\Proto\Backup\Error $error
     *     @type bool $success
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Brpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.backup.Error error = 1;</code>
     * @return \CrazyGoat\Proto\Backup\Error|null
     */
    public function getError()
    {
        return $this->error;
    }

    public function hasError()
    {
        return isset($this->error);
    }

    public function clearError()
    {
        unset($this->error);
    }

    /**
     * Generated from protobuf field <code>.backup.Error error = 1;</code>
     * @param \CrazyGoat\Proto\Backup\Error $var
     * @return $this
     */
    public function setError(\CrazyGoat\Proto\Backup\Error|null $var)
    {
        $this->error = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool success = 2;</code>
     * @return bool
     */
    public function getSuccess()
    {
        return $this->success;
    }

    /**
     * Generated from protobuf field <code>bool success = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setSuccess(bool $var)
    {
        $this->success = $var;

        return $this;
    }

}

