<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brpb.proto

namespace CrazyGoat\Proto\Backup;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>backup.CleanupRequest</code>
 */
class CleanupRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * unique_id represents the unique handle of the whole backup predecure.
     * it generated in prepare request and corrosponed to one specific backup.
     *
     * Generated from protobuf field <code>string unique_id = 1;</code>
     */
    protected $unique_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $unique_id
     *           unique_id represents the unique handle of the whole backup predecure.
     *           it generated in prepare request and corrosponed to one specific backup.
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Brpb::initOnce();
        parent::__construct($data);
    }

    /**
     * unique_id represents the unique handle of the whole backup predecure.
     * it generated in prepare request and corrosponed to one specific backup.
     *
     * Generated from protobuf field <code>string unique_id = 1;</code>
     * @return string
     */
    public function getUniqueId()
    {
        return $this->unique_id;
    }

    /**
     * unique_id represents the unique handle of the whole backup predecure.
     * it generated in prepare request and corrosponed to one specific backup.
     *
     * Generated from protobuf field <code>string unique_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUniqueId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->unique_id = $var;

        return $this;
    }

}

