<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brpb.proto

namespace CrazyGoat\Proto\Backup;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * CloudDynamic allows testing new cloud providers and new fields without changing protobuf definitions
 *
 * Generated from protobuf message <code>backup.CloudDynamic</code>
 */
class CloudDynamic extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.backup.Bucket bucket = 1;</code>
     */
    protected $bucket = null;
    /**
     * s3, gcs and azureBlobStorage are supported
     *
     * Generated from protobuf field <code>string provider_name = 2;</code>
     */
    protected $provider_name = '';
    /**
     * Generated from protobuf field <code>map<string, string> attrs = 3;</code>
     */
    private $attrs;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CrazyGoat\Proto\Backup\Bucket $bucket
     *     @type string $provider_name
     *           s3, gcs and azureBlobStorage are supported
     *     @type array|\Google\Protobuf\Internal\MapField $attrs
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Brpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.backup.Bucket bucket = 1;</code>
     * @return \CrazyGoat\Proto\Backup\Bucket|null
     */
    public function getBucket()
    {
        return $this->bucket;
    }

    public function hasBucket()
    {
        return isset($this->bucket);
    }

    public function clearBucket()
    {
        unset($this->bucket);
    }

    /**
     * Generated from protobuf field <code>.backup.Bucket bucket = 1;</code>
     * @param \CrazyGoat\Proto\Backup\Bucket $var
     * @return $this
     */
    public function setBucket(\CrazyGoat\Proto\Backup\Bucket|null $var)
    {
        $this->bucket = $var;

        return $this;
    }

    /**
     * s3, gcs and azureBlobStorage are supported
     *
     * Generated from protobuf field <code>string provider_name = 2;</code>
     * @return string
     */
    public function getProviderName()
    {
        return $this->provider_name;
    }

    /**
     * s3, gcs and azureBlobStorage are supported
     *
     * Generated from protobuf field <code>string provider_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setProviderName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->provider_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> attrs = 3;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getAttrs()
    {
        return $this->attrs;
    }

    /**
     * Generated from protobuf field <code>map<string, string> attrs = 3;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setAttrs(array|\Google\Protobuf\Internal\MapField $var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->attrs = $arr;

        return $this;
    }

}

