<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brpb.proto

namespace CrazyGoat\Proto\Backup;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>backup.ClusterIDError</code>
 */
class ClusterIDError extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 current = 1;</code>
     */
    protected $current = 0;
    /**
     * Generated from protobuf field <code>uint64 request = 2;</code>
     */
    protected $request = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $current
     *     @type int|string $request
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Brpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 current = 1;</code>
     * @return int|string
     */
    public function getCurrent()
    {
        return $this->current;
    }

    /**
     * Generated from protobuf field <code>uint64 current = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCurrent(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->current = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 request = 2;</code>
     * @return int|string
     */
    public function getRequest()
    {
        return $this->request;
    }

    /**
     * Generated from protobuf field <code>uint64 request = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRequest(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->request = $var;

        return $this;
    }

}

