<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brpb.proto

namespace CrazyGoat\Proto\Backup;

use UnexpectedValueException;

/**
 * sst files or log files compression algorithm
 * for log files, unknown means not use compression algorithm
 *
 * Protobuf type <code>backup.CompressionType</code>
 */
class CompressionType
{
    /**
     * Generated from protobuf enum <code>UNKNOWN = 0;</code>
     */
    const UNKNOWN = 0;
    /**
     * Generated from protobuf enum <code>LZ4 = 1;</code>
     */
    const LZ4 = 1;
    /**
     * Generated from protobuf enum <code>SNAPPY = 2;</code>
     */
    const SNAPPY = 2;
    /**
     * Generated from protobuf enum <code>ZSTD = 3;</code>
     */
    const ZSTD = 3;

    private static $valueToName = [
        self::UNKNOWN => 'UNKNOWN',
        self::LZ4 => 'LZ4',
        self::SNAPPY => 'SNAPPY',
        self::ZSTD => 'ZSTD',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

