<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brpb.proto

namespace CrazyGoat\Proto\Backup;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * DataFileGroup is the merged file info in log-backup
 *
 * Generated from protobuf message <code>backup.DataFileGroup</code>
 */
class DataFileGroup extends \Google\Protobuf\Internal\Message
{
    /**
     * Path of the file.
     *
     * Generated from protobuf field <code>string path = 1;</code>
     */
    protected $path = '';
    /**
     * Partitions of the file.
     *
     * Generated from protobuf field <code>repeated .backup.DataFileInfo data_files_info = 2;</code>
     */
    private $data_files_info;
    /**
     * / Below are extra information of the file, for better filtering files.
     * The min ts of the keys in the file.
     *
     * Generated from protobuf field <code>uint64 min_ts = 3;</code>
     */
    protected $min_ts = 0;
    /**
     * The max ts of the keys in the file.
     *
     * Generated from protobuf field <code>uint64 max_ts = 4;</code>
     */
    protected $max_ts = 0;
    /**
     * The resolved ts of the region when saving the file.
     *
     * Generated from protobuf field <code>uint64 min_resolved_ts = 5;</code>
     */
    protected $min_resolved_ts = 0;
    /**
     * The file length after compressed.
     *
     * Generated from protobuf field <code>uint64 length = 6;</code>
     */
    protected $length = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $path
     *           Path of the file.
     *     @type \CrazyGoat\Proto\Backup\DataFileInfo[] $data_files_info
     *           Partitions of the file.
     *     @type int|string $min_ts
     *          / Below are extra information of the file, for better filtering files.
     *           The min ts of the keys in the file.
     *     @type int|string $max_ts
     *           The max ts of the keys in the file.
     *     @type int|string $min_resolved_ts
     *           The resolved ts of the region when saving the file.
     *     @type int|string $length
     *           The file length after compressed.
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Brpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Path of the file.
     *
     * Generated from protobuf field <code>string path = 1;</code>
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * Path of the file.
     *
     * Generated from protobuf field <code>string path = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPath(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->path = $var;

        return $this;
    }

    /**
     * Partitions of the file.
     *
     * Generated from protobuf field <code>repeated .backup.DataFileInfo data_files_info = 2;</code>
     * @return RepeatedField<\CrazyGoat\Proto\Backup\DataFileInfo>
     */
    public function getDataFilesInfo()
    {
        return $this->data_files_info;
    }

    /**
     * Partitions of the file.
     *
     * Generated from protobuf field <code>repeated .backup.DataFileInfo data_files_info = 2;</code>
     * @param \CrazyGoat\Proto\Backup\DataFileInfo[] $var
     * @return $this
     */
    public function setDataFilesInfo(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \CrazyGoat\Proto\Backup\DataFileInfo::class);
        $this->data_files_info = $arr;

        return $this;
    }

    /**
     * / Below are extra information of the file, for better filtering files.
     * The min ts of the keys in the file.
     *
     * Generated from protobuf field <code>uint64 min_ts = 3;</code>
     * @return int|string
     */
    public function getMinTs()
    {
        return $this->min_ts;
    }

    /**
     * / Below are extra information of the file, for better filtering files.
     * The min ts of the keys in the file.
     *
     * Generated from protobuf field <code>uint64 min_ts = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMinTs(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->min_ts = $var;

        return $this;
    }

    /**
     * The max ts of the keys in the file.
     *
     * Generated from protobuf field <code>uint64 max_ts = 4;</code>
     * @return int|string
     */
    public function getMaxTs()
    {
        return $this->max_ts;
    }

    /**
     * The max ts of the keys in the file.
     *
     * Generated from protobuf field <code>uint64 max_ts = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMaxTs(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->max_ts = $var;

        return $this;
    }

    /**
     * The resolved ts of the region when saving the file.
     *
     * Generated from protobuf field <code>uint64 min_resolved_ts = 5;</code>
     * @return int|string
     */
    public function getMinResolvedTs()
    {
        return $this->min_resolved_ts;
    }

    /**
     * The resolved ts of the region when saving the file.
     *
     * Generated from protobuf field <code>uint64 min_resolved_ts = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMinResolvedTs(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->min_resolved_ts = $var;

        return $this;
    }

    /**
     * The file length after compressed.
     *
     * Generated from protobuf field <code>uint64 length = 6;</code>
     * @return int|string
     */
    public function getLength()
    {
        return $this->length;
    }

    /**
     * The file length after compressed.
     *
     * Generated from protobuf field <code>uint64 length = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLength(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->length = $var;

        return $this;
    }

}

