<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brpb.proto

namespace CrazyGoat\Proto\Backup;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * An extended version of `SpansOfFile`, added more metadata for the
 * execution of delayed deletion.
 *
 * Generated from protobuf message <code>backup.DeleteSpansOfFile</code>
 */
class DeleteSpansOfFile extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string path = 1;</code>
     */
    protected $path = '';
    /**
     * Generated from protobuf field <code>repeated .backup.Span spans = 2;</code>
     */
    private $spans;
    /**
     * This is a hint for garbage collecting.
     * So we can easily check whether a set of spans consists the whole file.
     *
     * Generated from protobuf field <code>uint64 whole_file_length = 3;</code>
     */
    protected $whole_file_length = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $path
     *     @type \CrazyGoat\Proto\Backup\Span[] $spans
     *     @type int|string $whole_file_length
     *           This is a hint for garbage collecting.
     *           So we can easily check whether a set of spans consists the whole file.
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Brpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string path = 1;</code>
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * Generated from protobuf field <code>string path = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPath(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->path = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .backup.Span spans = 2;</code>
     * @return RepeatedField<\CrazyGoat\Proto\Backup\Span>
     */
    public function getSpans()
    {
        return $this->spans;
    }

    /**
     * Generated from protobuf field <code>repeated .backup.Span spans = 2;</code>
     * @param \CrazyGoat\Proto\Backup\Span[] $var
     * @return $this
     */
    public function setSpans(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \CrazyGoat\Proto\Backup\Span::class);
        $this->spans = $arr;

        return $this;
    }

    /**
     * This is a hint for garbage collecting.
     * So we can easily check whether a set of spans consists the whole file.
     *
     * Generated from protobuf field <code>uint64 whole_file_length = 3;</code>
     * @return int|string
     */
    public function getWholeFileLength()
    {
        return $this->whole_file_length;
    }

    /**
     * This is a hint for garbage collecting.
     * So we can easily check whether a set of spans consists the whole file.
     *
     * Generated from protobuf field <code>uint64 whole_file_length = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setWholeFileLength(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->whole_file_length = $var;

        return $this;
    }

}

