<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brpb.proto

namespace CrazyGoat\Proto\Backup;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>backup.Error</code>
 */
class Error extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string msg = 1;</code>
     */
    protected $msg = '';
    protected $detail;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $msg
     *     @type \CrazyGoat\Proto\Backup\ClusterIDError $cluster_id_error
     *     @type \CrazyGoat\Proto\Kvrpcpb\KeyError $kv_error
     *     @type \CrazyGoat\Proto\Errorpb\Error $region_error
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Brpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string msg = 1;</code>
     * @return string
     */
    public function getMsg()
    {
        return $this->msg;
    }

    /**
     * Generated from protobuf field <code>string msg = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMsg(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->msg = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.backup.ClusterIDError cluster_id_error = 3;</code>
     * @return \CrazyGoat\Proto\Backup\ClusterIDError|null
     */
    public function getClusterIdError()
    {
        return $this->readOneof(3);
    }

    public function hasClusterIdError()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.backup.ClusterIDError cluster_id_error = 3;</code>
     * @param \CrazyGoat\Proto\Backup\ClusterIDError $var
     * @return $this
     */
    public function setClusterIdError(\CrazyGoat\Proto\Backup\ClusterIDError|null $var)
    {
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.KeyError kv_error = 4;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\KeyError|null
     */
    public function getKvError()
    {
        return $this->readOneof(4);
    }

    public function hasKvError()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.KeyError kv_error = 4;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\KeyError $var
     * @return $this
     */
    public function setKvError(\CrazyGoat\Proto\Kvrpcpb\KeyError|null $var)
    {
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.errorpb.Error region_error = 5;</code>
     * @return \CrazyGoat\Proto\Errorpb\Error|null
     */
    public function getRegionError()
    {
        return $this->readOneof(5);
    }

    public function hasRegionError()
    {
        return $this->hasOneof(5);
    }

    /**
     * Generated from protobuf field <code>.errorpb.Error region_error = 5;</code>
     * @param \CrazyGoat\Proto\Errorpb\Error $var
     * @return $this
     */
    public function setRegionError(\CrazyGoat\Proto\Errorpb\Error|null $var)
    {
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getDetail()
    {
        return $this->whichOneof("detail");
    }

}

