<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brpb.proto

namespace CrazyGoat\Proto\Backup;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>backup.ExternalStorageSaveRequest</code>
 */
class ExternalStorageSaveRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.backup.StorageBackend storage_backend = 1;</code>
     */
    protected $storage_backend = null;
    /**
     * Generated from protobuf field <code>string object_name = 2;</code>
     */
    protected $object_name = '';
    /**
     * Generated from protobuf field <code>uint64 content_length = 3;</code>
     */
    protected $content_length = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CrazyGoat\Proto\Backup\StorageBackend $storage_backend
     *     @type string $object_name
     *     @type int|string $content_length
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Brpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.backup.StorageBackend storage_backend = 1;</code>
     * @return \CrazyGoat\Proto\Backup\StorageBackend|null
     */
    public function getStorageBackend()
    {
        return $this->storage_backend;
    }

    public function hasStorageBackend()
    {
        return isset($this->storage_backend);
    }

    public function clearStorageBackend()
    {
        unset($this->storage_backend);
    }

    /**
     * Generated from protobuf field <code>.backup.StorageBackend storage_backend = 1;</code>
     * @param \CrazyGoat\Proto\Backup\StorageBackend $var
     * @return $this
     */
    public function setStorageBackend(\CrazyGoat\Proto\Backup\StorageBackend|null $var)
    {
        $this->storage_backend = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string object_name = 2;</code>
     * @return string
     */
    public function getObjectName()
    {
        return $this->object_name;
    }

    /**
     * Generated from protobuf field <code>string object_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setObjectName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->object_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 content_length = 3;</code>
     * @return int|string
     */
    public function getContentLength()
    {
        return $this->content_length;
    }

    /**
     * Generated from protobuf field <code>uint64 content_length = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setContentLength(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->content_length = $var;

        return $this;
    }

}

