<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brpb.proto

namespace CrazyGoat\Proto\Backup;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>backup.File</code>
 */
class File extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>bytes sha256 = 2;</code>
     */
    protected $sha256 = '';
    /**
     * Generated from protobuf field <code>bytes start_key = 3;</code>
     */
    protected $start_key = '';
    /**
     * Generated from protobuf field <code>bytes end_key = 4;</code>
     */
    protected $end_key = '';
    /**
     * Generated from protobuf field <code>uint64 start_version = 5;</code>
     */
    protected $start_version = 0;
    /**
     * Generated from protobuf field <code>uint64 end_version = 6;</code>
     */
    protected $end_version = 0;
    /**
     * recorded the total statistics across multiple tables
     *
     * Generated from protobuf field <code>uint64 crc64xor = 7;</code>
     */
    protected $crc64xor = 0;
    /**
     * Generated from protobuf field <code>uint64 total_kvs = 8;</code>
     */
    protected $total_kvs = 0;
    /**
     * Generated from protobuf field <code>uint64 total_bytes = 9;</code>
     */
    protected $total_bytes = 0;
    /**
     * recorded when the SST kvs are from different tables
     *
     * Generated from protobuf field <code>repeated .backup.TableMeta table_metas = 13;</code>
     */
    private $table_metas;
    /**
     * Generated from protobuf field <code>string cf = 10;</code>
     */
    protected $cf = '';
    /**
     * Generated from protobuf field <code>uint64 size = 11;</code>
     */
    protected $size = 0;
    /**
     * cipher_iv is used for AES cipher
     *
     * Generated from protobuf field <code>bytes cipher_iv = 12;</code>
     */
    protected $cipher_iv = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type string $sha256
     *     @type string $start_key
     *     @type string $end_key
     *     @type int|string $start_version
     *     @type int|string $end_version
     *     @type int|string $crc64xor
     *           recorded the total statistics across multiple tables
     *     @type int|string $total_kvs
     *     @type int|string $total_bytes
     *     @type \CrazyGoat\Proto\Backup\TableMeta[] $table_metas
     *           recorded when the SST kvs are from different tables
     *     @type string $cf
     *     @type int|string $size
     *     @type string $cipher_iv
     *           cipher_iv is used for AES cipher
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Brpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes sha256 = 2;</code>
     * @return string
     */
    public function getSha256()
    {
        return $this->sha256;
    }

    /**
     * Generated from protobuf field <code>bytes sha256 = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSha256(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->sha256 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes start_key = 3;</code>
     * @return string
     */
    public function getStartKey()
    {
        return $this->start_key;
    }

    /**
     * Generated from protobuf field <code>bytes start_key = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setStartKey(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->start_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes end_key = 4;</code>
     * @return string
     */
    public function getEndKey()
    {
        return $this->end_key;
    }

    /**
     * Generated from protobuf field <code>bytes end_key = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setEndKey(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->end_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 start_version = 5;</code>
     * @return int|string
     */
    public function getStartVersion()
    {
        return $this->start_version;
    }

    /**
     * Generated from protobuf field <code>uint64 start_version = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStartVersion(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->start_version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 end_version = 6;</code>
     * @return int|string
     */
    public function getEndVersion()
    {
        return $this->end_version;
    }

    /**
     * Generated from protobuf field <code>uint64 end_version = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEndVersion(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->end_version = $var;

        return $this;
    }

    /**
     * recorded the total statistics across multiple tables
     *
     * Generated from protobuf field <code>uint64 crc64xor = 7;</code>
     * @return int|string
     */
    public function getCrc64Xor()
    {
        return $this->crc64xor;
    }

    /**
     * recorded the total statistics across multiple tables
     *
     * Generated from protobuf field <code>uint64 crc64xor = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCrc64Xor(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->crc64xor = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 total_kvs = 8;</code>
     * @return int|string
     */
    public function getTotalKvs()
    {
        return $this->total_kvs;
    }

    /**
     * Generated from protobuf field <code>uint64 total_kvs = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalKvs(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->total_kvs = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 total_bytes = 9;</code>
     * @return int|string
     */
    public function getTotalBytes()
    {
        return $this->total_bytes;
    }

    /**
     * Generated from protobuf field <code>uint64 total_bytes = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalBytes(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->total_bytes = $var;

        return $this;
    }

    /**
     * recorded when the SST kvs are from different tables
     *
     * Generated from protobuf field <code>repeated .backup.TableMeta table_metas = 13;</code>
     * @return RepeatedField<\CrazyGoat\Proto\Backup\TableMeta>
     */
    public function getTableMetas()
    {
        return $this->table_metas;
    }

    /**
     * recorded when the SST kvs are from different tables
     *
     * Generated from protobuf field <code>repeated .backup.TableMeta table_metas = 13;</code>
     * @param \CrazyGoat\Proto\Backup\TableMeta[] $var
     * @return $this
     */
    public function setTableMetas(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \CrazyGoat\Proto\Backup\TableMeta::class);
        $this->table_metas = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string cf = 10;</code>
     * @return string
     */
    public function getCf()
    {
        return $this->cf;
    }

    /**
     * Generated from protobuf field <code>string cf = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setCf(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->cf = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 size = 11;</code>
     * @return int|string
     */
    public function getSize()
    {
        return $this->size;
    }

    /**
     * Generated from protobuf field <code>uint64 size = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSize(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->size = $var;

        return $this;
    }

    /**
     * cipher_iv is used for AES cipher
     *
     * Generated from protobuf field <code>bytes cipher_iv = 12;</code>
     * @return string
     */
    public function getCipherIv()
    {
        return $this->cipher_iv;
    }

    /**
     * cipher_iv is used for AES cipher
     *
     * Generated from protobuf field <code>bytes cipher_iv = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setCipherIv(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->cipher_iv = $var;

        return $this;
    }

}

