<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brpb.proto

namespace CrazyGoat\Proto\Backup;

use UnexpectedValueException;

/**
 * Protobuf type <code>backup.FileType</code>
 */
class FileType
{
    /**
     * Generated from protobuf enum <code>Delete = 0;</code>
     */
    const Delete = 0;
    /**
     * Generated from protobuf enum <code>Put = 1;</code>
     */
    const Put = 1;

    private static $valueToName = [
        self::Delete => 'Delete',
        self::Put => 'Put',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

