<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brpb.proto

namespace CrazyGoat\Proto\Backup;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * GCS storage backend saves files into google cloud storage.
 *
 * Generated from protobuf message <code>backup.GCS</code>
 */
class GCS extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string endpoint = 1;</code>
     */
    protected $endpoint = '';
    /**
     * Generated from protobuf field <code>string bucket = 2;</code>
     */
    protected $bucket = '';
    /**
     * Generated from protobuf field <code>string prefix = 3;</code>
     */
    protected $prefix = '';
    /**
     * Generated from protobuf field <code>string storage_class = 4;</code>
     */
    protected $storage_class = '';
    /**
     * If not empty, applies a predefined set of access controls.
     * See https://cloud.google.com/storage/docs/access-control/lists#predefined-acl
     * for valid values.
     *
     * Generated from protobuf field <code>string predefined_acl = 5;</code>
     */
    protected $predefined_acl = '';
    /**
     * Service Account Credentials JSON blob
     * You can get one from https://console.cloud.google.com/apis/credentials, and
     * copy the content, set it as string here.
     *
     * Generated from protobuf field <code>string credentials_blob = 6;</code>
     */
    protected $credentials_blob = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $endpoint
     *     @type string $bucket
     *     @type string $prefix
     *     @type string $storage_class
     *     @type string $predefined_acl
     *           If not empty, applies a predefined set of access controls.
     *           See https://cloud.google.com/storage/docs/access-control/lists#predefined-acl
     *           for valid values.
     *     @type string $credentials_blob
     *           Service Account Credentials JSON blob
     *           You can get one from https://console.cloud.google.com/apis/credentials, and
     *           copy the content, set it as string here.
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Brpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string endpoint = 1;</code>
     * @return string
     */
    public function getEndpoint()
    {
        return $this->endpoint;
    }

    /**
     * Generated from protobuf field <code>string endpoint = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setEndpoint(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->endpoint = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string bucket = 2;</code>
     * @return string
     */
    public function getBucket()
    {
        return $this->bucket;
    }

    /**
     * Generated from protobuf field <code>string bucket = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setBucket(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->bucket = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string prefix = 3;</code>
     * @return string
     */
    public function getPrefix()
    {
        return $this->prefix;
    }

    /**
     * Generated from protobuf field <code>string prefix = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPrefix(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->prefix = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string storage_class = 4;</code>
     * @return string
     */
    public function getStorageClass()
    {
        return $this->storage_class;
    }

    /**
     * Generated from protobuf field <code>string storage_class = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setStorageClass(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->storage_class = $var;

        return $this;
    }

    /**
     * If not empty, applies a predefined set of access controls.
     * See https://cloud.google.com/storage/docs/access-control/lists#predefined-acl
     * for valid values.
     *
     * Generated from protobuf field <code>string predefined_acl = 5;</code>
     * @return string
     */
    public function getPredefinedAcl()
    {
        return $this->predefined_acl;
    }

    /**
     * If not empty, applies a predefined set of access controls.
     * See https://cloud.google.com/storage/docs/access-control/lists#predefined-acl
     * for valid values.
     *
     * Generated from protobuf field <code>string predefined_acl = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setPredefinedAcl(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->predefined_acl = $var;

        return $this;
    }

    /**
     * Service Account Credentials JSON blob
     * You can get one from https://console.cloud.google.com/apis/credentials, and
     * copy the content, set it as string here.
     *
     * Generated from protobuf field <code>string credentials_blob = 6;</code>
     * @return string
     */
    public function getCredentialsBlob()
    {
        return $this->credentials_blob;
    }

    /**
     * Service Account Credentials JSON blob
     * You can get one from https://console.cloud.google.com/apis/credentials, and
     * copy the content, set it as string here.
     *
     * Generated from protobuf field <code>string credentials_blob = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setCredentialsBlob(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->credentials_blob = $var;

        return $this;
    }

}

