<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brpb.proto

namespace CrazyGoat\Proto\Backup;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * HDFS storage backend saves file into HDFS compatible storages
 *
 * Generated from protobuf message <code>backup.HDFS</code>
 */
class HDFS extends \Google\Protobuf\Internal\Message
{
    /**
     *  a URL: hdfs:///some/path or hdfs://host:port/some/path
     *
     * Generated from protobuf field <code>string remote = 1;</code>
     */
    protected $remote = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $remote
     *            a URL: hdfs:///some/path or hdfs://host:port/some/path
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Brpb::initOnce();
        parent::__construct($data);
    }

    /**
     *  a URL: hdfs:///some/path or hdfs://host:port/some/path
     *
     * Generated from protobuf field <code>string remote = 1;</code>
     * @return string
     */
    public function getRemote()
    {
        return $this->remote;
    }

    /**
     *  a URL: hdfs:///some/path or hdfs://host:port/some/path
     *
     * Generated from protobuf field <code>string remote = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRemote(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->remote = $var;

        return $this;
    }

}

