<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brpb.proto

namespace CrazyGoat\Proto\Backup;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>backup.IDMap</code>
 */
class IDMap extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 upstream_id = 1;</code>
     */
    protected $upstream_id = 0;
    /**
     * Generated from protobuf field <code>int64 downstream_id = 2;</code>
     */
    protected $downstream_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $upstream_id
     *     @type int|string $downstream_id
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Brpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 upstream_id = 1;</code>
     * @return int|string
     */
    public function getUpstreamId()
    {
        return $this->upstream_id;
    }

    /**
     * Generated from protobuf field <code>int64 upstream_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUpstreamId(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->upstream_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 downstream_id = 2;</code>
     * @return int|string
     */
    public function getDownstreamId()
    {
        return $this->downstream_id;
    }

    /**
     * Generated from protobuf field <code>int64 downstream_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDownstreamId(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->downstream_id = $var;

        return $this;
    }

}

