<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brpb.proto

namespace CrazyGoat\Proto\Backup;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * IngestedSSTs is created by a client that wants to put data to the cluster by `Ingest` APIs,
 * these write cannot be directly recorded by log backup. The client should put a migration
 * that contains the SSTs it uploaded.
 *
 * Generated from protobuf message <code>backup.IngestedSSTs</code>
 */
class IngestedSSTs extends \Google\Protobuf\Internal\Message
{
    /**
     * The table IDs rewritten during restoring.
     *
     * Generated from protobuf field <code>repeated .backup.RewrittenTableID rewritten_tables = 1;</code>
     */
    private $rewritten_tables;
    /**
     * The SST files restored.
     *
     * Generated from protobuf field <code>repeated .backup.File files = 2;</code>
     */
    private $files;
    /**
     * Treating the whole batch of SSTs as an huge atomic
     * write as this timestamp.
     * That is, when user wants to PiTR to sometime after this,
     * everything restored will present after the PiTR.
     * Otherwise nothing will present.
     *
     * Generated from protobuf field <code>uint64 as_if_ts = 3;</code>
     */
    protected $as_if_ts = 0;
    /**
     * The hint of the common prefix of the files.
     * Used for speed up garbage collecting.
     *
     * Generated from protobuf field <code>string files_prefix_hint = 4;</code>
     */
    protected $files_prefix_hint = '';
    /**
     * Whether this batch have finished.
     * If not, `as_if_ts` should be ignored and this should only
     * be restored when there is a finished backup with the same
     * `backup_uuid`.
     *
     * Generated from protobuf field <code>bool finished = 5;</code>
     */
    protected $finished = false;
    /**
     * When checkpoint enabled, one restoration may be separated to many
     * of `IngestedSST`s.
     * `IngestedSST`s sharing the same UUID should be treated as one.
     * That is:
     * - The `as_if_ts` should be the largest one among all finished ingested SST batches.
     * - When restoring, all batches sharing the same uuid should be restored or not.
     *
     * Generated from protobuf field <code>bytes backup_uuid = 6;</code>
     */
    protected $backup_uuid = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CrazyGoat\Proto\Backup\RewrittenTableID[] $rewritten_tables
     *           The table IDs rewritten during restoring.
     *     @type \CrazyGoat\Proto\Backup\File[] $files
     *           The SST files restored.
     *     @type int|string $as_if_ts
     *           Treating the whole batch of SSTs as an huge atomic
     *           write as this timestamp.
     *           That is, when user wants to PiTR to sometime after this,
     *           everything restored will present after the PiTR.
     *           Otherwise nothing will present.
     *     @type string $files_prefix_hint
     *           The hint of the common prefix of the files.
     *           Used for speed up garbage collecting.
     *     @type bool $finished
     *           Whether this batch have finished.
     *           If not, `as_if_ts` should be ignored and this should only
     *           be restored when there is a finished backup with the same
     *           `backup_uuid`.
     *     @type string $backup_uuid
     *           When checkpoint enabled, one restoration may be separated to many
     *           of `IngestedSST`s.
     *           `IngestedSST`s sharing the same UUID should be treated as one.
     *           That is:
     *           - The `as_if_ts` should be the largest one among all finished ingested SST batches.
     *           - When restoring, all batches sharing the same uuid should be restored or not.
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Brpb::initOnce();
        parent::__construct($data);
    }

    /**
     * The table IDs rewritten during restoring.
     *
     * Generated from protobuf field <code>repeated .backup.RewrittenTableID rewritten_tables = 1;</code>
     * @return RepeatedField<\CrazyGoat\Proto\Backup\RewrittenTableID>
     */
    public function getRewrittenTables()
    {
        return $this->rewritten_tables;
    }

    /**
     * The table IDs rewritten during restoring.
     *
     * Generated from protobuf field <code>repeated .backup.RewrittenTableID rewritten_tables = 1;</code>
     * @param \CrazyGoat\Proto\Backup\RewrittenTableID[] $var
     * @return $this
     */
    public function setRewrittenTables(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \CrazyGoat\Proto\Backup\RewrittenTableID::class);
        $this->rewritten_tables = $arr;

        return $this;
    }

    /**
     * The SST files restored.
     *
     * Generated from protobuf field <code>repeated .backup.File files = 2;</code>
     * @return RepeatedField<\CrazyGoat\Proto\Backup\File>
     */
    public function getFiles()
    {
        return $this->files;
    }

    /**
     * The SST files restored.
     *
     * Generated from protobuf field <code>repeated .backup.File files = 2;</code>
     * @param \CrazyGoat\Proto\Backup\File[] $var
     * @return $this
     */
    public function setFiles(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \CrazyGoat\Proto\Backup\File::class);
        $this->files = $arr;

        return $this;
    }

    /**
     * Treating the whole batch of SSTs as an huge atomic
     * write as this timestamp.
     * That is, when user wants to PiTR to sometime after this,
     * everything restored will present after the PiTR.
     * Otherwise nothing will present.
     *
     * Generated from protobuf field <code>uint64 as_if_ts = 3;</code>
     * @return int|string
     */
    public function getAsIfTs()
    {
        return $this->as_if_ts;
    }

    /**
     * Treating the whole batch of SSTs as an huge atomic
     * write as this timestamp.
     * That is, when user wants to PiTR to sometime after this,
     * everything restored will present after the PiTR.
     * Otherwise nothing will present.
     *
     * Generated from protobuf field <code>uint64 as_if_ts = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAsIfTs(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->as_if_ts = $var;

        return $this;
    }

    /**
     * The hint of the common prefix of the files.
     * Used for speed up garbage collecting.
     *
     * Generated from protobuf field <code>string files_prefix_hint = 4;</code>
     * @return string
     */
    public function getFilesPrefixHint()
    {
        return $this->files_prefix_hint;
    }

    /**
     * The hint of the common prefix of the files.
     * Used for speed up garbage collecting.
     *
     * Generated from protobuf field <code>string files_prefix_hint = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setFilesPrefixHint(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->files_prefix_hint = $var;

        return $this;
    }

    /**
     * Whether this batch have finished.
     * If not, `as_if_ts` should be ignored and this should only
     * be restored when there is a finished backup with the same
     * `backup_uuid`.
     *
     * Generated from protobuf field <code>bool finished = 5;</code>
     * @return bool
     */
    public function getFinished()
    {
        return $this->finished;
    }

    /**
     * Whether this batch have finished.
     * If not, `as_if_ts` should be ignored and this should only
     * be restored when there is a finished backup with the same
     * `backup_uuid`.
     *
     * Generated from protobuf field <code>bool finished = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setFinished(bool $var)
    {
        $this->finished = $var;

        return $this;
    }

    /**
     * When checkpoint enabled, one restoration may be separated to many
     * of `IngestedSST`s.
     * `IngestedSST`s sharing the same UUID should be treated as one.
     * That is:
     * - The `as_if_ts` should be the largest one among all finished ingested SST batches.
     * - When restoring, all batches sharing the same uuid should be restored or not.
     *
     * Generated from protobuf field <code>bytes backup_uuid = 6;</code>
     * @return string
     */
    public function getBackupUuid()
    {
        return $this->backup_uuid;
    }

    /**
     * When checkpoint enabled, one restoration may be separated to many
     * of `IngestedSST`s.
     * `IngestedSST`s sharing the same UUID should be treated as one.
     * That is:
     * - The `as_if_ts` should be the largest one among all finished ingested SST batches.
     * - When restoring, all batches sharing the same uuid should be restored or not.
     *
     * Generated from protobuf field <code>bytes backup_uuid = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setBackupUuid(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->backup_uuid = $var;

        return $this;
    }

}

