<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brpb.proto

namespace CrazyGoat\Proto\Backup;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Batched version of `LogFileSubcompaction`.
 * So we can store many subcompactions to one file, to reduce the number of file.
 *
 * Generated from protobuf message <code>backup.LogFileSubcompactions</code>
 */
class LogFileSubcompactions extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .backup.LogFileSubcompaction subcompactions = 1;</code>
     */
    private $subcompactions;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CrazyGoat\Proto\Backup\LogFileSubcompaction[] $subcompactions
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Brpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .backup.LogFileSubcompaction subcompactions = 1;</code>
     * @return RepeatedField<\CrazyGoat\Proto\Backup\LogFileSubcompaction>
     */
    public function getSubcompactions()
    {
        return $this->subcompactions;
    }

    /**
     * Generated from protobuf field <code>repeated .backup.LogFileSubcompaction subcompactions = 1;</code>
     * @param \CrazyGoat\Proto\Backup\LogFileSubcompaction[] $var
     * @return $this
     */
    public function setSubcompactions(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \CrazyGoat\Proto\Backup\LogFileSubcompaction::class);
        $this->subcompactions = $arr;

        return $this;
    }

}

