<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brpb.proto

namespace CrazyGoat\Proto\Backup;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>backup.LogFileSubcompactionMeta</code>
 */
class LogFileSubcompactionMeta extends \Google\Protobuf\Internal\Message
{
    /**
     * The whole size of this subcompaction.
     * It should be the physical size of all input logs.
     *
     * Generated from protobuf field <code>uint64 size = 1;</code>
     */
    protected $size = 0;
    /**
     * The region that we perform the subcompaction.
     *
     * Generated from protobuf field <code>uint64 region_id = 2;</code>
     */
    protected $region_id = 0;
    /**
     * Generated from protobuf field <code>string cf = 3;</code>
     */
    protected $cf = '';
    /**
     * Generated from protobuf field <code>uint64 input_max_ts = 4;</code>
     */
    protected $input_max_ts = 0;
    /**
     * Generated from protobuf field <code>uint64 input_min_ts = 5;</code>
     */
    protected $input_min_ts = 0;
    /**
     * The whole compaction's configure.
     *
     * Generated from protobuf field <code>uint64 compact_from_ts = 6;</code>
     */
    protected $compact_from_ts = 0;
    /**
     * Generated from protobuf field <code>uint64 compact_until_ts = 7;</code>
     */
    protected $compact_until_ts = 0;
    /**
     * The key range of the input logs.
     * They are encoded user key. (i.e. mem-comparable, no 'z' prefix)
     *
     * Generated from protobuf field <code>bytes min_key = 8;</code>
     */
    protected $min_key = '';
    /**
     * The largest key from the input.
     *
     * Generated from protobuf field <code>bytes max_key = 9;</code>
     */
    protected $max_key = '';
    /**
     * The type of operations in the file. (Write or Delete)
     *
     * Generated from protobuf field <code>.backup.FileType ty = 10;</code>
     */
    protected $ty = 0;
    /**
     * Generated from protobuf field <code>int64 table_id = 11;</code>
     */
    protected $table_id = 0;
    /**
     * The input log files of this.
     *
     * Generated from protobuf field <code>repeated .backup.SpansOfFile sources = 12;</code>
     */
    private $sources;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $size
     *           The whole size of this subcompaction.
     *           It should be the physical size of all input logs.
     *     @type int|string $region_id
     *           The region that we perform the subcompaction.
     *     @type string $cf
     *     @type int|string $input_max_ts
     *     @type int|string $input_min_ts
     *     @type int|string $compact_from_ts
     *           The whole compaction's configure.
     *     @type int|string $compact_until_ts
     *     @type string $min_key
     *           The key range of the input logs.
     *           They are encoded user key. (i.e. mem-comparable, no 'z' prefix)
     *     @type string $max_key
     *           The largest key from the input.
     *     @type int $ty
     *           The type of operations in the file. (Write or Delete)
     *     @type int|string $table_id
     *     @type \CrazyGoat\Proto\Backup\SpansOfFile[] $sources
     *           The input log files of this.
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Brpb::initOnce();
        parent::__construct($data);
    }

    /**
     * The whole size of this subcompaction.
     * It should be the physical size of all input logs.
     *
     * Generated from protobuf field <code>uint64 size = 1;</code>
     * @return int|string
     */
    public function getSize()
    {
        return $this->size;
    }

    /**
     * The whole size of this subcompaction.
     * It should be the physical size of all input logs.
     *
     * Generated from protobuf field <code>uint64 size = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSize(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->size = $var;

        return $this;
    }

    /**
     * The region that we perform the subcompaction.
     *
     * Generated from protobuf field <code>uint64 region_id = 2;</code>
     * @return int|string
     */
    public function getRegionId()
    {
        return $this->region_id;
    }

    /**
     * The region that we perform the subcompaction.
     *
     * Generated from protobuf field <code>uint64 region_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRegionId(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->region_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string cf = 3;</code>
     * @return string
     */
    public function getCf()
    {
        return $this->cf;
    }

    /**
     * Generated from protobuf field <code>string cf = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCf(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->cf = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 input_max_ts = 4;</code>
     * @return int|string
     */
    public function getInputMaxTs()
    {
        return $this->input_max_ts;
    }

    /**
     * Generated from protobuf field <code>uint64 input_max_ts = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setInputMaxTs(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->input_max_ts = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 input_min_ts = 5;</code>
     * @return int|string
     */
    public function getInputMinTs()
    {
        return $this->input_min_ts;
    }

    /**
     * Generated from protobuf field <code>uint64 input_min_ts = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setInputMinTs(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->input_min_ts = $var;

        return $this;
    }

    /**
     * The whole compaction's configure.
     *
     * Generated from protobuf field <code>uint64 compact_from_ts = 6;</code>
     * @return int|string
     */
    public function getCompactFromTs()
    {
        return $this->compact_from_ts;
    }

    /**
     * The whole compaction's configure.
     *
     * Generated from protobuf field <code>uint64 compact_from_ts = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCompactFromTs(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->compact_from_ts = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 compact_until_ts = 7;</code>
     * @return int|string
     */
    public function getCompactUntilTs()
    {
        return $this->compact_until_ts;
    }

    /**
     * Generated from protobuf field <code>uint64 compact_until_ts = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCompactUntilTs(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->compact_until_ts = $var;

        return $this;
    }

    /**
     * The key range of the input logs.
     * They are encoded user key. (i.e. mem-comparable, no 'z' prefix)
     *
     * Generated from protobuf field <code>bytes min_key = 8;</code>
     * @return string
     */
    public function getMinKey()
    {
        return $this->min_key;
    }

    /**
     * The key range of the input logs.
     * They are encoded user key. (i.e. mem-comparable, no 'z' prefix)
     *
     * Generated from protobuf field <code>bytes min_key = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setMinKey(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->min_key = $var;

        return $this;
    }

    /**
     * The largest key from the input.
     *
     * Generated from protobuf field <code>bytes max_key = 9;</code>
     * @return string
     */
    public function getMaxKey()
    {
        return $this->max_key;
    }

    /**
     * The largest key from the input.
     *
     * Generated from protobuf field <code>bytes max_key = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setMaxKey(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->max_key = $var;

        return $this;
    }

    /**
     * The type of operations in the file. (Write or Delete)
     *
     * Generated from protobuf field <code>.backup.FileType ty = 10;</code>
     * @return int one of the values in {@see \CrazyGoat\Proto\Backup\FileType}
     */
    public function getTy()
    {
        return $this->ty;
    }

    /**
     * The type of operations in the file. (Write or Delete)
     *
     * Generated from protobuf field <code>.backup.FileType ty = 10;</code>
     * @param int $var one of the values in {@see \CrazyGoat\Proto\Backup\FileType}
     * @return $this
     */
    public function setTy(int $var)
    {
        GPBUtil::checkEnum($var, \CrazyGoat\Proto\Backup\FileType::class);
        $this->ty = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 table_id = 11;</code>
     * @return int|string
     */
    public function getTableId()
    {
        return $this->table_id;
    }

    /**
     * Generated from protobuf field <code>int64 table_id = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTableId(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->table_id = $var;

        return $this;
    }

    /**
     * The input log files of this.
     *
     * Generated from protobuf field <code>repeated .backup.SpansOfFile sources = 12;</code>
     * @return RepeatedField<\CrazyGoat\Proto\Backup\SpansOfFile>
     */
    public function getSources()
    {
        return $this->sources;
    }

    /**
     * The input log files of this.
     *
     * Generated from protobuf field <code>repeated .backup.SpansOfFile sources = 12;</code>
     * @param \CrazyGoat\Proto\Backup\SpansOfFile[] $var
     * @return $this
     */
    public function setSources(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \CrazyGoat\Proto\Backup\SpansOfFile::class);
        $this->sources = $arr;

        return $this;
    }

}

