<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brpb.proto

namespace CrazyGoat\Proto\Backup;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>backup.LogFileCompaction</code>
 */
class LogFileCompaction extends \Google\Protobuf\Internal\Message
{
    /**
     * The selector of compaction source.
     * Files contains ANY record greater than this (and less than `until_ts`) will be selected.
     * The source and artificats may contain records out of the `from_ts` and `until_ts` range.
     * When restoring, please use `input_min_ts` to filter out not needed compactions instead.
     *
     * Generated from protobuf field <code>uint64 compaction_from_ts = 1;</code>
     */
    protected $compaction_from_ts = 0;
    /**
     * The selector of compaction source.
     * Files contains ANY record less than this (and not less than `from_ts`) will be selected.
     * The source and artificats may contain records out of the `from_ts` and `until_ts` range.
     * When restoring, please use `input_max_ts` to filter out not needed compactions instead.
     *
     * Generated from protobuf field <code>uint64 compaction_until_ts = 2;</code>
     */
    protected $compaction_until_ts = 0;
    /**
     * The user provided name for the compaction.
     *
     * Generated from protobuf field <code>string name = 3;</code>
     */
    protected $name = '';
    /**
     * The statistics or other useful information for human.
     *
     * Generated from protobuf field <code>string comments = 4;</code>
     */
    protected $comments = '';
    /**
     * relative path to the generated subcompaction metas. ("artificates")
     *
     * Generated from protobuf field <code>string artifacts = 5;</code>
     */
    protected $artifacts = '';
    /**
     * the XOR of all artificate's hash.
     *
     * Generated from protobuf field <code>uint64 artifacts_hash = 6;</code>
     */
    protected $artifacts_hash = 0;
    /**
     * relative path to the subcompaction generated SST files.
     * this is a hint for garbage-collecting, so we don't need to read the metas one by one.
     * Those SSTs cannot be directly used, what you need is probably in `artificates`.
     *
     * Generated from protobuf field <code>string generated_files = 7;</code>
     */
    protected $generated_files = '';
    /**
     * The smallest TS of record contained among all selected files of this compaction.
     *
     * Generated from protobuf field <code>uint64 input_min_ts = 8;</code>
     */
    protected $input_min_ts = 0;
    /**
     * The largest TS of record contained among all selected files of this compaction.
     *
     * Generated from protobuf field <code>uint64 input_max_ts = 9;</code>
     */
    protected $input_max_ts = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $compaction_from_ts
     *           The selector of compaction source.
     *           Files contains ANY record greater than this (and less than `until_ts`) will be selected.
     *           The source and artificats may contain records out of the `from_ts` and `until_ts` range.
     *           When restoring, please use `input_min_ts` to filter out not needed compactions instead.
     *     @type int|string $compaction_until_ts
     *           The selector of compaction source.
     *           Files contains ANY record less than this (and not less than `from_ts`) will be selected.
     *           The source and artificats may contain records out of the `from_ts` and `until_ts` range.
     *           When restoring, please use `input_max_ts` to filter out not needed compactions instead.
     *     @type string $name
     *           The user provided name for the compaction.
     *     @type string $comments
     *           The statistics or other useful information for human.
     *     @type string $artifacts
     *           relative path to the generated subcompaction metas. ("artificates")
     *     @type int|string $artifacts_hash
     *           the XOR of all artificate's hash.
     *     @type string $generated_files
     *           relative path to the subcompaction generated SST files.
     *           this is a hint for garbage-collecting, so we don't need to read the metas one by one.
     *           Those SSTs cannot be directly used, what you need is probably in `artificates`.
     *     @type int|string $input_min_ts
     *           The smallest TS of record contained among all selected files of this compaction.
     *     @type int|string $input_max_ts
     *           The largest TS of record contained among all selected files of this compaction.
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Brpb::initOnce();
        parent::__construct($data);
    }

    /**
     * The selector of compaction source.
     * Files contains ANY record greater than this (and less than `until_ts`) will be selected.
     * The source and artificats may contain records out of the `from_ts` and `until_ts` range.
     * When restoring, please use `input_min_ts` to filter out not needed compactions instead.
     *
     * Generated from protobuf field <code>uint64 compaction_from_ts = 1;</code>
     * @return int|string
     */
    public function getCompactionFromTs()
    {
        return $this->compaction_from_ts;
    }

    /**
     * The selector of compaction source.
     * Files contains ANY record greater than this (and less than `until_ts`) will be selected.
     * The source and artificats may contain records out of the `from_ts` and `until_ts` range.
     * When restoring, please use `input_min_ts` to filter out not needed compactions instead.
     *
     * Generated from protobuf field <code>uint64 compaction_from_ts = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCompactionFromTs(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->compaction_from_ts = $var;

        return $this;
    }

    /**
     * The selector of compaction source.
     * Files contains ANY record less than this (and not less than `from_ts`) will be selected.
     * The source and artificats may contain records out of the `from_ts` and `until_ts` range.
     * When restoring, please use `input_max_ts` to filter out not needed compactions instead.
     *
     * Generated from protobuf field <code>uint64 compaction_until_ts = 2;</code>
     * @return int|string
     */
    public function getCompactionUntilTs()
    {
        return $this->compaction_until_ts;
    }

    /**
     * The selector of compaction source.
     * Files contains ANY record less than this (and not less than `from_ts`) will be selected.
     * The source and artificats may contain records out of the `from_ts` and `until_ts` range.
     * When restoring, please use `input_max_ts` to filter out not needed compactions instead.
     *
     * Generated from protobuf field <code>uint64 compaction_until_ts = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCompactionUntilTs(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->compaction_until_ts = $var;

        return $this;
    }

    /**
     * The user provided name for the compaction.
     *
     * Generated from protobuf field <code>string name = 3;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * The user provided name for the compaction.
     *
     * Generated from protobuf field <code>string name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * The statistics or other useful information for human.
     *
     * Generated from protobuf field <code>string comments = 4;</code>
     * @return string
     */
    public function getComments()
    {
        return $this->comments;
    }

    /**
     * The statistics or other useful information for human.
     *
     * Generated from protobuf field <code>string comments = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setComments(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->comments = $var;

        return $this;
    }

    /**
     * relative path to the generated subcompaction metas. ("artificates")
     *
     * Generated from protobuf field <code>string artifacts = 5;</code>
     * @return string
     */
    public function getArtifacts()
    {
        return $this->artifacts;
    }

    /**
     * relative path to the generated subcompaction metas. ("artificates")
     *
     * Generated from protobuf field <code>string artifacts = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setArtifacts(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->artifacts = $var;

        return $this;
    }

    /**
     * the XOR of all artificate's hash.
     *
     * Generated from protobuf field <code>uint64 artifacts_hash = 6;</code>
     * @return int|string
     */
    public function getArtifactsHash()
    {
        return $this->artifacts_hash;
    }

    /**
     * the XOR of all artificate's hash.
     *
     * Generated from protobuf field <code>uint64 artifacts_hash = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setArtifactsHash(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->artifacts_hash = $var;

        return $this;
    }

    /**
     * relative path to the subcompaction generated SST files.
     * this is a hint for garbage-collecting, so we don't need to read the metas one by one.
     * Those SSTs cannot be directly used, what you need is probably in `artificates`.
     *
     * Generated from protobuf field <code>string generated_files = 7;</code>
     * @return string
     */
    public function getGeneratedFiles()
    {
        return $this->generated_files;
    }

    /**
     * relative path to the subcompaction generated SST files.
     * this is a hint for garbage-collecting, so we don't need to read the metas one by one.
     * Those SSTs cannot be directly used, what you need is probably in `artificates`.
     *
     * Generated from protobuf field <code>string generated_files = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setGeneratedFiles(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->generated_files = $var;

        return $this;
    }

    /**
     * The smallest TS of record contained among all selected files of this compaction.
     *
     * Generated from protobuf field <code>uint64 input_min_ts = 8;</code>
     * @return int|string
     */
    public function getInputMinTs()
    {
        return $this->input_min_ts;
    }

    /**
     * The smallest TS of record contained among all selected files of this compaction.
     *
     * Generated from protobuf field <code>uint64 input_min_ts = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setInputMinTs(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->input_min_ts = $var;

        return $this;
    }

    /**
     * The largest TS of record contained among all selected files of this compaction.
     *
     * Generated from protobuf field <code>uint64 input_max_ts = 9;</code>
     * @return int|string
     */
    public function getInputMaxTs()
    {
        return $this->input_max_ts;
    }

    /**
     * The largest TS of record contained among all selected files of this compaction.
     *
     * Generated from protobuf field <code>uint64 input_max_ts = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setInputMaxTs(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->input_max_ts = $var;

        return $this;
    }

}

