<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brpb.proto

namespace CrazyGoat\Proto\Backup;

use UnexpectedValueException;

/**
 * Protobuf type <code>backup.MetaVersion</code>
 */
class MetaVersion
{
    /**
     * Generated from protobuf enum <code>V1 = 0;</code>
     */
    const V1 = 0;
    /**
     * Generated from protobuf enum <code>V2 = 1;</code>
     */
    const V2 = 1;

    private static $valueToName = [
        self::V1 => 'V1',
        self::V2 => 'V2',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

