<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brpb.proto

namespace CrazyGoat\Proto\Backup;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>backup.MetaEdit</code>
 */
class MetaEdit extends \Google\Protobuf\Internal\Message
{
    /**
     * Path to the meta file.
     *
     * Generated from protobuf field <code>string path = 1;</code>
     */
    protected $path = '';
    /**
     * Delete the physical files (MetaFileGroup) in the meta file.
     *
     * Generated from protobuf field <code>repeated string delete_physical_files = 2;</code>
     */
    private $delete_physical_files;
    /**
     * Delete the logical files (MetaFileInfo) in the meta file.
     * Note: Even the operation have been performed in the meta,
     * this modification should be kept as long as the corresponding physical
     * file not deleted. Or we may cannot know when to delete the physical file.
     * Then the file will be leak until truncated.
     *
     * Generated from protobuf field <code>repeated .backup.DeleteSpansOfFile delete_logical_files = 3;</code>
     */
    private $delete_logical_files;
    /**
     * Whether to delete the metadata itself.
     *
     * Generated from protobuf field <code>bool destruct_self = 4;</code>
     */
    protected $destruct_self = false;
    /**
     * Whether all data kv files have been compacted but meta kv file still remains.
     * this field used to determine whether we can ignore the physical data kv log files in a compaction.
     *
     * Generated from protobuf field <code>bool all_data_files_compacted = 5;</code>
     */
    protected $all_data_files_compacted = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $path
     *           Path to the meta file.
     *     @type string[] $delete_physical_files
     *           Delete the physical files (MetaFileGroup) in the meta file.
     *     @type \CrazyGoat\Proto\Backup\DeleteSpansOfFile[] $delete_logical_files
     *           Delete the logical files (MetaFileInfo) in the meta file.
     *           Note: Even the operation have been performed in the meta,
     *           this modification should be kept as long as the corresponding physical
     *           file not deleted. Or we may cannot know when to delete the physical file.
     *           Then the file will be leak until truncated.
     *     @type bool $destruct_self
     *           Whether to delete the metadata itself.
     *     @type bool $all_data_files_compacted
     *           Whether all data kv files have been compacted but meta kv file still remains.
     *           this field used to determine whether we can ignore the physical data kv log files in a compaction.
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Brpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Path to the meta file.
     *
     * Generated from protobuf field <code>string path = 1;</code>
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * Path to the meta file.
     *
     * Generated from protobuf field <code>string path = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPath(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->path = $var;

        return $this;
    }

    /**
     * Delete the physical files (MetaFileGroup) in the meta file.
     *
     * Generated from protobuf field <code>repeated string delete_physical_files = 2;</code>
     * @return RepeatedField<string>
     */
    public function getDeletePhysicalFiles()
    {
        return $this->delete_physical_files;
    }

    /**
     * Delete the physical files (MetaFileGroup) in the meta file.
     *
     * Generated from protobuf field <code>repeated string delete_physical_files = 2;</code>
     * @param string[] $var
     * @return $this
     */
    public function setDeletePhysicalFiles(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->delete_physical_files = $arr;

        return $this;
    }

    /**
     * Delete the logical files (MetaFileInfo) in the meta file.
     * Note: Even the operation have been performed in the meta,
     * this modification should be kept as long as the corresponding physical
     * file not deleted. Or we may cannot know when to delete the physical file.
     * Then the file will be leak until truncated.
     *
     * Generated from protobuf field <code>repeated .backup.DeleteSpansOfFile delete_logical_files = 3;</code>
     * @return RepeatedField<\CrazyGoat\Proto\Backup\DeleteSpansOfFile>
     */
    public function getDeleteLogicalFiles()
    {
        return $this->delete_logical_files;
    }

    /**
     * Delete the logical files (MetaFileInfo) in the meta file.
     * Note: Even the operation have been performed in the meta,
     * this modification should be kept as long as the corresponding physical
     * file not deleted. Or we may cannot know when to delete the physical file.
     * Then the file will be leak until truncated.
     *
     * Generated from protobuf field <code>repeated .backup.DeleteSpansOfFile delete_logical_files = 3;</code>
     * @param \CrazyGoat\Proto\Backup\DeleteSpansOfFile[] $var
     * @return $this
     */
    public function setDeleteLogicalFiles(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \CrazyGoat\Proto\Backup\DeleteSpansOfFile::class);
        $this->delete_logical_files = $arr;

        return $this;
    }

    /**
     * Whether to delete the metadata itself.
     *
     * Generated from protobuf field <code>bool destruct_self = 4;</code>
     * @return bool
     */
    public function getDestructSelf()
    {
        return $this->destruct_self;
    }

    /**
     * Whether to delete the metadata itself.
     *
     * Generated from protobuf field <code>bool destruct_self = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setDestructSelf(bool $var)
    {
        $this->destruct_self = $var;

        return $this;
    }

    /**
     * Whether all data kv files have been compacted but meta kv file still remains.
     * this field used to determine whether we can ignore the physical data kv log files in a compaction.
     *
     * Generated from protobuf field <code>bool all_data_files_compacted = 5;</code>
     * @return bool
     */
    public function getAllDataFilesCompacted()
    {
        return $this->all_data_files_compacted;
    }

    /**
     * Whether all data kv files have been compacted but meta kv file still remains.
     * this field used to determine whether we can ignore the physical data kv log files in a compaction.
     *
     * Generated from protobuf field <code>bool all_data_files_compacted = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setAllDataFilesCompacted(bool $var)
    {
        $this->all_data_files_compacted = $var;

        return $this;
    }

}

