<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brpb.proto

namespace CrazyGoat\Proto\Backup;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>backup.Metadata</code>
 */
class Metadata extends \Google\Protobuf\Internal\Message
{
    /**
     * deprecated after(in) v6.3.0 TiKV cluster
     *
     * Generated from protobuf field <code>repeated .backup.DataFileInfo files = 1;</code>
     */
    private $files;
    /**
     * Generated from protobuf field <code>repeated .backup.DataFileGroup file_groups = 6;</code>
     */
    private $file_groups;
    /**
     * Generated from protobuf field <code>int64 store_id = 2;</code>
     */
    protected $store_id = 0;
    /**
     * Generated from protobuf field <code>uint64 resolved_ts = 3;</code>
     */
    protected $resolved_ts = 0;
    /**
     * Generated from protobuf field <code>uint64 max_ts = 4;</code>
     */
    protected $max_ts = 0;
    /**
     * Generated from protobuf field <code>uint64 min_ts = 5;</code>
     */
    protected $min_ts = 0;
    /**
     * Generated from protobuf field <code>.backup.MetaVersion meta_version = 7;</code>
     */
    protected $meta_version = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CrazyGoat\Proto\Backup\DataFileInfo[] $files
     *           deprecated after(in) v6.3.0 TiKV cluster
     *     @type \CrazyGoat\Proto\Backup\DataFileGroup[] $file_groups
     *     @type int|string $store_id
     *     @type int|string $resolved_ts
     *     @type int|string $max_ts
     *     @type int|string $min_ts
     *     @type int $meta_version
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Brpb::initOnce();
        parent::__construct($data);
    }

    /**
     * deprecated after(in) v6.3.0 TiKV cluster
     *
     * Generated from protobuf field <code>repeated .backup.DataFileInfo files = 1;</code>
     * @return RepeatedField<\CrazyGoat\Proto\Backup\DataFileInfo>
     */
    public function getFiles()
    {
        return $this->files;
    }

    /**
     * deprecated after(in) v6.3.0 TiKV cluster
     *
     * Generated from protobuf field <code>repeated .backup.DataFileInfo files = 1;</code>
     * @param \CrazyGoat\Proto\Backup\DataFileInfo[] $var
     * @return $this
     */
    public function setFiles(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \CrazyGoat\Proto\Backup\DataFileInfo::class);
        $this->files = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .backup.DataFileGroup file_groups = 6;</code>
     * @return RepeatedField<\CrazyGoat\Proto\Backup\DataFileGroup>
     */
    public function getFileGroups()
    {
        return $this->file_groups;
    }

    /**
     * Generated from protobuf field <code>repeated .backup.DataFileGroup file_groups = 6;</code>
     * @param \CrazyGoat\Proto\Backup\DataFileGroup[] $var
     * @return $this
     */
    public function setFileGroups(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \CrazyGoat\Proto\Backup\DataFileGroup::class);
        $this->file_groups = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 store_id = 2;</code>
     * @return int|string
     */
    public function getStoreId()
    {
        return $this->store_id;
    }

    /**
     * Generated from protobuf field <code>int64 store_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStoreId(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->store_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 resolved_ts = 3;</code>
     * @return int|string
     */
    public function getResolvedTs()
    {
        return $this->resolved_ts;
    }

    /**
     * Generated from protobuf field <code>uint64 resolved_ts = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setResolvedTs(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->resolved_ts = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 max_ts = 4;</code>
     * @return int|string
     */
    public function getMaxTs()
    {
        return $this->max_ts;
    }

    /**
     * Generated from protobuf field <code>uint64 max_ts = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMaxTs(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->max_ts = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 min_ts = 5;</code>
     * @return int|string
     */
    public function getMinTs()
    {
        return $this->min_ts;
    }

    /**
     * Generated from protobuf field <code>uint64 min_ts = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMinTs(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->min_ts = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.backup.MetaVersion meta_version = 7;</code>
     * @return int one of the values in {@see \CrazyGoat\Proto\Backup\MetaVersion}
     */
    public function getMetaVersion()
    {
        return $this->meta_version;
    }

    /**
     * Generated from protobuf field <code>.backup.MetaVersion meta_version = 7;</code>
     * @param int $var one of the values in {@see \CrazyGoat\Proto\Backup\MetaVersion}
     * @return $this
     */
    public function setMetaVersion(int $var)
    {
        GPBUtil::checkEnum($var, \CrazyGoat\Proto\Backup\MetaVersion::class);
        $this->meta_version = $var;

        return $this;
    }

}

