<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brpb.proto

namespace CrazyGoat\Proto\Backup;

use UnexpectedValueException;

/**
 * Protobuf type <code>backup.MigrationVersion</code>
 */
class MigrationVersion
{
    /**
     * The initial version. Somehow "UNKNOWN".
     *
     * Generated from protobuf enum <code>M0 = 0;</code>
     */
    const M0 = 0;
    /**
     * Added `creator` and `version`.
     *
     * Generated from protobuf enum <code>M1 = 1;</code>
     */
    const M1 = 1;
    /**
     * Added `ingested_sst_paths`.
     *
     * Generated from protobuf enum <code>M2 = 2;</code>
     */
    const M2 = 2;

    private static $valueToName = [
        self::M0 => 'M0',
        self::M1 => 'M1',
        self::M2 => 'M2',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

