<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brpb.proto

namespace CrazyGoat\Proto\Backup;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>backup.PitrDBMap</code>
 */
class PitrDBMap extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>.backup.IDMap id_map = 2;</code>
     */
    protected $id_map = null;
    /**
     * Generated from protobuf field <code>repeated .backup.PitrTableMap tables = 3;</code>
     */
    private $tables;
    /**
     * whether this db has been filtered out
     *
     * Generated from protobuf field <code>bool filtered_out = 4;</code>
     */
    protected $filtered_out = false;
    /**
     * whether this db has been reused
     * skip restoring the metakv of database in log restore if it is true
     *
     * Generated from protobuf field <code>bool reused = 5;</code>
     */
    protected $reused = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type \CrazyGoat\Proto\Backup\IDMap $id_map
     *     @type \CrazyGoat\Proto\Backup\PitrTableMap[] $tables
     *     @type bool $filtered_out
     *           whether this db has been filtered out
     *     @type bool $reused
     *           whether this db has been reused
     *           skip restoring the metakv of database in log restore if it is true
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Brpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.backup.IDMap id_map = 2;</code>
     * @return \CrazyGoat\Proto\Backup\IDMap|null
     */
    public function getIdMap()
    {
        return $this->id_map;
    }

    public function hasIdMap()
    {
        return isset($this->id_map);
    }

    public function clearIdMap()
    {
        unset($this->id_map);
    }

    /**
     * Generated from protobuf field <code>.backup.IDMap id_map = 2;</code>
     * @param \CrazyGoat\Proto\Backup\IDMap $var
     * @return $this
     */
    public function setIdMap(\CrazyGoat\Proto\Backup\IDMap|null $var)
    {
        $this->id_map = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .backup.PitrTableMap tables = 3;</code>
     * @return RepeatedField<\CrazyGoat\Proto\Backup\PitrTableMap>
     */
    public function getTables()
    {
        return $this->tables;
    }

    /**
     * Generated from protobuf field <code>repeated .backup.PitrTableMap tables = 3;</code>
     * @param \CrazyGoat\Proto\Backup\PitrTableMap[] $var
     * @return $this
     */
    public function setTables(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \CrazyGoat\Proto\Backup\PitrTableMap::class);
        $this->tables = $arr;

        return $this;
    }

    /**
     * whether this db has been filtered out
     *
     * Generated from protobuf field <code>bool filtered_out = 4;</code>
     * @return bool
     */
    public function getFilteredOut()
    {
        return $this->filtered_out;
    }

    /**
     * whether this db has been filtered out
     *
     * Generated from protobuf field <code>bool filtered_out = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setFilteredOut(bool $var)
    {
        $this->filtered_out = $var;

        return $this;
    }

    /**
     * whether this db has been reused
     * skip restoring the metakv of database in log restore if it is true
     *
     * Generated from protobuf field <code>bool reused = 5;</code>
     * @return bool
     */
    public function getReused()
    {
        return $this->reused;
    }

    /**
     * whether this db has been reused
     * skip restoring the metakv of database in log restore if it is true
     *
     * Generated from protobuf field <code>bool reused = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setReused(bool $var)
    {
        $this->reused = $var;

        return $this;
    }

}

