<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brpb.proto

namespace CrazyGoat\Proto\Backup;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>backup.PrepareSnapshotBackupRequest</code>
 */
class PrepareSnapshotBackupRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The type of the request.
     *
     * Generated from protobuf field <code>.backup.PrepareSnapshotBackupRequestType ty = 1;</code>
     */
    protected $ty = 0;
    /**
     * The regions related to the request.
     * If the request is "UpdateLease" or "Finish", it should be empty.
     *
     * Generated from protobuf field <code>repeated .metapb.Region regions = 2;</code>
     */
    private $regions;
    /**
     * The lease duration for "UpdateLease" request.
     *
     * Generated from protobuf field <code>uint64 lease_in_seconds = 3;</code>
     */
    protected $lease_in_seconds = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $ty
     *           The type of the request.
     *     @type \CrazyGoat\Proto\Metapb\Region[] $regions
     *           The regions related to the request.
     *           If the request is "UpdateLease" or "Finish", it should be empty.
     *     @type int|string $lease_in_seconds
     *           The lease duration for "UpdateLease" request.
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Brpb::initOnce();
        parent::__construct($data);
    }

    /**
     * The type of the request.
     *
     * Generated from protobuf field <code>.backup.PrepareSnapshotBackupRequestType ty = 1;</code>
     * @return int one of the values in {@see \CrazyGoat\Proto\Backup\PrepareSnapshotBackupRequestType}
     */
    public function getTy()
    {
        return $this->ty;
    }

    /**
     * The type of the request.
     *
     * Generated from protobuf field <code>.backup.PrepareSnapshotBackupRequestType ty = 1;</code>
     * @param int $var one of the values in {@see \CrazyGoat\Proto\Backup\PrepareSnapshotBackupRequestType}
     * @return $this
     */
    public function setTy(int $var)
    {
        GPBUtil::checkEnum($var, \CrazyGoat\Proto\Backup\PrepareSnapshotBackupRequestType::class);
        $this->ty = $var;

        return $this;
    }

    /**
     * The regions related to the request.
     * If the request is "UpdateLease" or "Finish", it should be empty.
     *
     * Generated from protobuf field <code>repeated .metapb.Region regions = 2;</code>
     * @return RepeatedField<\CrazyGoat\Proto\Metapb\Region>
     */
    public function getRegions()
    {
        return $this->regions;
    }

    /**
     * The regions related to the request.
     * If the request is "UpdateLease" or "Finish", it should be empty.
     *
     * Generated from protobuf field <code>repeated .metapb.Region regions = 2;</code>
     * @param \CrazyGoat\Proto\Metapb\Region[] $var
     * @return $this
     */
    public function setRegions(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \CrazyGoat\Proto\Metapb\Region::class);
        $this->regions = $arr;

        return $this;
    }

    /**
     * The lease duration for "UpdateLease" request.
     *
     * Generated from protobuf field <code>uint64 lease_in_seconds = 3;</code>
     * @return int|string
     */
    public function getLeaseInSeconds()
    {
        return $this->lease_in_seconds;
    }

    /**
     * The lease duration for "UpdateLease" request.
     *
     * Generated from protobuf field <code>uint64 lease_in_seconds = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLeaseInSeconds(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->lease_in_seconds = $var;

        return $this;
    }

}

