<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brpb.proto

namespace CrazyGoat\Proto\Backup;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>backup.PrepareSnapshotBackupResponse</code>
 */
class PrepareSnapshotBackupResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The type of the event.
     *
     * Generated from protobuf field <code>.backup.PrepareSnapshotBackupEventType ty = 1;</code>
     */
    protected $ty = 0;
    /**
     * The region bind to the type.
     * For "WaitApplyDone".
     *
     * Generated from protobuf field <code>.metapb.Region region = 2;</code>
     */
    protected $region = null;
    /**
     * The error of the execution.
     *
     * Generated from protobuf field <code>.errorpb.Error error = 3;</code>
     */
    protected $error = null;
    /**
     * Whether the last lease is valid.
     * For "UpdateLease" and "Finish".
     *
     * Generated from protobuf field <code>bool last_lease_is_valid = 4;</code>
     */
    protected $last_lease_is_valid = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $ty
     *           The type of the event.
     *     @type \CrazyGoat\Proto\Metapb\Region $region
     *           The region bind to the type.
     *           For "WaitApplyDone".
     *     @type \CrazyGoat\Proto\Errorpb\Error $error
     *           The error of the execution.
     *     @type bool $last_lease_is_valid
     *           Whether the last lease is valid.
     *           For "UpdateLease" and "Finish".
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Brpb::initOnce();
        parent::__construct($data);
    }

    /**
     * The type of the event.
     *
     * Generated from protobuf field <code>.backup.PrepareSnapshotBackupEventType ty = 1;</code>
     * @return int one of the values in {@see \CrazyGoat\Proto\Backup\PrepareSnapshotBackupEventType}
     */
    public function getTy()
    {
        return $this->ty;
    }

    /**
     * The type of the event.
     *
     * Generated from protobuf field <code>.backup.PrepareSnapshotBackupEventType ty = 1;</code>
     * @param int $var one of the values in {@see \CrazyGoat\Proto\Backup\PrepareSnapshotBackupEventType}
     * @return $this
     */
    public function setTy(int $var)
    {
        GPBUtil::checkEnum($var, \CrazyGoat\Proto\Backup\PrepareSnapshotBackupEventType::class);
        $this->ty = $var;

        return $this;
    }

    /**
     * The region bind to the type.
     * For "WaitApplyDone".
     *
     * Generated from protobuf field <code>.metapb.Region region = 2;</code>
     * @return \CrazyGoat\Proto\Metapb\Region|null
     */
    public function getRegion()
    {
        return $this->region;
    }

    public function hasRegion()
    {
        return isset($this->region);
    }

    public function clearRegion()
    {
        unset($this->region);
    }

    /**
     * The region bind to the type.
     * For "WaitApplyDone".
     *
     * Generated from protobuf field <code>.metapb.Region region = 2;</code>
     * @param \CrazyGoat\Proto\Metapb\Region $var
     * @return $this
     */
    public function setRegion(\CrazyGoat\Proto\Metapb\Region|null $var)
    {
        $this->region = $var;

        return $this;
    }

    /**
     * The error of the execution.
     *
     * Generated from protobuf field <code>.errorpb.Error error = 3;</code>
     * @return \CrazyGoat\Proto\Errorpb\Error|null
     */
    public function getError()
    {
        return $this->error;
    }

    public function hasError()
    {
        return isset($this->error);
    }

    public function clearError()
    {
        unset($this->error);
    }

    /**
     * The error of the execution.
     *
     * Generated from protobuf field <code>.errorpb.Error error = 3;</code>
     * @param \CrazyGoat\Proto\Errorpb\Error $var
     * @return $this
     */
    public function setError(\CrazyGoat\Proto\Errorpb\Error|null $var)
    {
        $this->error = $var;

        return $this;
    }

    /**
     * Whether the last lease is valid.
     * For "UpdateLease" and "Finish".
     *
     * Generated from protobuf field <code>bool last_lease_is_valid = 4;</code>
     * @return bool
     */
    public function getLastLeaseIsValid()
    {
        return $this->last_lease_is_valid;
    }

    /**
     * Whether the last lease is valid.
     * For "UpdateLease" and "Finish".
     *
     * Generated from protobuf field <code>bool last_lease_is_valid = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setLastLeaseIsValid(bool $var)
    {
        $this->last_lease_is_valid = $var;

        return $this;
    }

}

