<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brpb.proto

namespace CrazyGoat\Proto\Backup;

use UnexpectedValueException;

/**
 * Protobuf type <code>backup.PrepareSnapshotBackupRequestType</code>
 */
class PrepareSnapshotBackupRequestType
{
    /**
     * Update the lease of suspending some commands (Which may impact the
     * disk snapshot backup) to be proposed.
     * As long as the lease is kept, those commands may not be proposed.
     * If the client has gone, the lease will be destroyed after its TTL.
     *
     * Generated from protobuf enum <code>UpdateLease = 0;</code>
     */
    const UpdateLease = 0;
    /**
     * Wait a region apply to the last index.
     *
     * Generated from protobuf enum <code>WaitApply = 1;</code>
     */
    const WaitApply = 1;
    /**
     * Hint before closing the stream. Server will go back to normal after this.
     * This should also return a final "UpdateLeaseResult" to the client, which
     * indices whether the last lease is valid.
     *
     * Generated from protobuf enum <code>Finish = 2;</code>
     */
    const Finish = 2;

    private static $valueToName = [
        self::UpdateLease => 'UpdateLease',
        self::WaitApply => 'WaitApply',
        self::Finish => 'Finish',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

