<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brpb.proto

namespace CrazyGoat\Proto\Backup;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>backup.PrepareResponse</code>
 */
class PrepareResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.backup.Error error = 1;</code>
     */
    protected $error = null;
    /**
     * unique_id represents the unique handle of the whole backup predecure.
     * if unique_id = 0 means prepare failed.
     * if unique_id > 0 means prepare success and all states saved with this unique info.
     *
     * Generated from protobuf field <code>string unique_id = 2;</code>
     */
    protected $unique_id = '';
    /**
     * Generated from protobuf field <code>uint64 collect_file_count = 3;</code>
     */
    protected $collect_file_count = 0;
    /**
     * Generated from protobuf field <code>uint64 collect_file_size = 4;</code>
     */
    protected $collect_file_size = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CrazyGoat\Proto\Backup\Error $error
     *     @type string $unique_id
     *           unique_id represents the unique handle of the whole backup predecure.
     *           if unique_id = 0 means prepare failed.
     *           if unique_id > 0 means prepare success and all states saved with this unique info.
     *     @type int|string $collect_file_count
     *     @type int|string $collect_file_size
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Brpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.backup.Error error = 1;</code>
     * @return \CrazyGoat\Proto\Backup\Error|null
     */
    public function getError()
    {
        return $this->error;
    }

    public function hasError()
    {
        return isset($this->error);
    }

    public function clearError()
    {
        unset($this->error);
    }

    /**
     * Generated from protobuf field <code>.backup.Error error = 1;</code>
     * @param \CrazyGoat\Proto\Backup\Error $var
     * @return $this
     */
    public function setError(\CrazyGoat\Proto\Backup\Error|null $var)
    {
        $this->error = $var;

        return $this;
    }

    /**
     * unique_id represents the unique handle of the whole backup predecure.
     * if unique_id = 0 means prepare failed.
     * if unique_id > 0 means prepare success and all states saved with this unique info.
     *
     * Generated from protobuf field <code>string unique_id = 2;</code>
     * @return string
     */
    public function getUniqueId()
    {
        return $this->unique_id;
    }

    /**
     * unique_id represents the unique handle of the whole backup predecure.
     * if unique_id = 0 means prepare failed.
     * if unique_id > 0 means prepare success and all states saved with this unique info.
     *
     * Generated from protobuf field <code>string unique_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setUniqueId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->unique_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 collect_file_count = 3;</code>
     * @return int|string
     */
    public function getCollectFileCount()
    {
        return $this->collect_file_count;
    }

    /**
     * Generated from protobuf field <code>uint64 collect_file_count = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCollectFileCount(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->collect_file_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 collect_file_size = 4;</code>
     * @return int|string
     */
    public function getCollectFileSize()
    {
        return $this->collect_file_size;
    }

    /**
     * Generated from protobuf field <code>uint64 collect_file_size = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCollectFileSize(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->collect_file_size = $var;

        return $this;
    }

}

