<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brpb.proto

namespace CrazyGoat\Proto\Backup;

use UnexpectedValueException;

/**
 * Protobuf type <code>backup.PrepareSnapshotBackupEventType</code>
 */
class PrepareSnapshotBackupEventType
{
    /**
     * A region has finished wait apply.
     *
     * Generated from protobuf enum <code>WaitApplyDone = 0;</code>
     */
    const WaitApplyDone = 0;
    /**
     * A lease has been updated.
     *
     * Generated from protobuf enum <code>UpdateLeaseResult = 1;</code>
     */
    const UpdateLeaseResult = 1;

    private static $valueToName = [
        self::WaitApplyDone => 'WaitApplyDone',
        self::UpdateLeaseResult => 'UpdateLeaseResult',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

