<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brpb.proto

namespace CrazyGoat\Proto\Backup;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>backup.RawRange</code>
 */
class RawRange extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes start_key = 1;</code>
     */
    protected $start_key = '';
    /**
     * Generated from protobuf field <code>bytes end_key = 2;</code>
     */
    protected $end_key = '';
    /**
     * Generated from protobuf field <code>string cf = 3;</code>
     */
    protected $cf = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $start_key
     *     @type string $end_key
     *     @type string $cf
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Brpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes start_key = 1;</code>
     * @return string
     */
    public function getStartKey()
    {
        return $this->start_key;
    }

    /**
     * Generated from protobuf field <code>bytes start_key = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setStartKey(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->start_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes end_key = 2;</code>
     * @return string
     */
    public function getEndKey()
    {
        return $this->end_key;
    }

    /**
     * Generated from protobuf field <code>bytes end_key = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setEndKey(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->end_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string cf = 3;</code>
     * @return string
     */
    public function getCf()
    {
        return $this->cf;
    }

    /**
     * Generated from protobuf field <code>string cf = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCf(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->cf = $var;

        return $this;
    }

}

