<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brpb.proto

namespace CrazyGoat\Proto\Backup;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * You may get region id from `LogFileSubcompactionMeta`.
 *
 * Generated from protobuf message <code>backup.RegionMetaHint</code>
 */
class RegionMetaHint extends \Google\Protobuf\Internal\Message
{
    /**
     * The left boundary of the region of this epoch.
     * It is an byte-comparable encoded key without TS.
     *
     * Generated from protobuf field <code>bytes start_key = 1;</code>
     */
    protected $start_key = '';
    /**
     * The right boundary of the region of the epoch.
     *
     * Generated from protobuf field <code>bytes end_key = 2;</code>
     */
    protected $end_key = '';
    /**
     * The region epoch.
     *
     * Generated from protobuf field <code>.metapb.RegionEpoch region_epoch = 3;</code>
     */
    protected $region_epoch = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $start_key
     *           The left boundary of the region of this epoch.
     *           It is an byte-comparable encoded key without TS.
     *     @type string $end_key
     *           The right boundary of the region of the epoch.
     *     @type \CrazyGoat\Proto\Metapb\RegionEpoch $region_epoch
     *           The region epoch.
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Brpb::initOnce();
        parent::__construct($data);
    }

    /**
     * The left boundary of the region of this epoch.
     * It is an byte-comparable encoded key without TS.
     *
     * Generated from protobuf field <code>bytes start_key = 1;</code>
     * @return string
     */
    public function getStartKey()
    {
        return $this->start_key;
    }

    /**
     * The left boundary of the region of this epoch.
     * It is an byte-comparable encoded key without TS.
     *
     * Generated from protobuf field <code>bytes start_key = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setStartKey(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->start_key = $var;

        return $this;
    }

    /**
     * The right boundary of the region of the epoch.
     *
     * Generated from protobuf field <code>bytes end_key = 2;</code>
     * @return string
     */
    public function getEndKey()
    {
        return $this->end_key;
    }

    /**
     * The right boundary of the region of the epoch.
     *
     * Generated from protobuf field <code>bytes end_key = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setEndKey(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->end_key = $var;

        return $this;
    }

    /**
     * The region epoch.
     *
     * Generated from protobuf field <code>.metapb.RegionEpoch region_epoch = 3;</code>
     * @return \CrazyGoat\Proto\Metapb\RegionEpoch|null
     */
    public function getRegionEpoch()
    {
        return $this->region_epoch;
    }

    public function hasRegionEpoch()
    {
        return isset($this->region_epoch);
    }

    public function clearRegionEpoch()
    {
        unset($this->region_epoch);
    }

    /**
     * The region epoch.
     *
     * Generated from protobuf field <code>.metapb.RegionEpoch region_epoch = 3;</code>
     * @param \CrazyGoat\Proto\Metapb\RegionEpoch $var
     * @return $this
     */
    public function setRegionEpoch(\CrazyGoat\Proto\Metapb\RegionEpoch|null $var)
    {
        $this->region_epoch = $var;

        return $this;
    }

}

