<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brpb.proto

namespace CrazyGoat\Proto\Backup;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * S3 storage backend saves files into S3 compatible storages
 * For non-aws providers, endpoint must be provided
 *
 * Generated from protobuf message <code>backup.S3</code>
 */
class S3 extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string endpoint = 1;</code>
     */
    protected $endpoint = '';
    /**
     * Generated from protobuf field <code>string region = 2;</code>
     */
    protected $region = '';
    /**
     * Generated from protobuf field <code>string bucket = 3;</code>
     */
    protected $bucket = '';
    /**
     * Generated from protobuf field <code>string prefix = 4;</code>
     */
    protected $prefix = '';
    /**
     * Generated from protobuf field <code>string storage_class = 5;</code>
     */
    protected $storage_class = '';
    /**
     * server side encryption
     *
     * Generated from protobuf field <code>string sse = 6;</code>
     */
    protected $sse = '';
    /**
     * Generated from protobuf field <code>string acl = 7;</code>
     */
    protected $acl = '';
    /**
     * Generated from protobuf field <code>string access_key = 8;</code>
     */
    protected $access_key = '';
    /**
     * Generated from protobuf field <code>string secret_access_key = 9;</code>
     */
    protected $secret_access_key = '';
    /**
     * Generated from protobuf field <code>bool force_path_style = 10;</code>
     */
    protected $force_path_style = false;
    /**
     * Generated from protobuf field <code>string sse_kms_key_id = 11;</code>
     */
    protected $sse_kms_key_id = '';
    /**
     * Generated from protobuf field <code>string role_arn = 12;</code>
     */
    protected $role_arn = '';
    /**
     * Generated from protobuf field <code>string external_id = 13;</code>
     */
    protected $external_id = '';
    /**
     * Generated from protobuf field <code>bool object_lock_enabled = 14;</code>
     */
    protected $object_lock_enabled = false;
    /**
     * Generated from protobuf field <code>string session_token = 15;</code>
     */
    protected $session_token = '';
    /**
     * Generated from protobuf field <code>string provider = 16;</code>
     */
    protected $provider = '';
    /**
     * Generated from protobuf field <code>string profile = 17;</code>
     */
    protected $profile = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $endpoint
     *     @type string $region
     *     @type string $bucket
     *     @type string $prefix
     *     @type string $storage_class
     *     @type string $sse
     *           server side encryption
     *     @type string $acl
     *     @type string $access_key
     *     @type string $secret_access_key
     *     @type bool $force_path_style
     *     @type string $sse_kms_key_id
     *     @type string $role_arn
     *     @type string $external_id
     *     @type bool $object_lock_enabled
     *     @type string $session_token
     *     @type string $provider
     *     @type string $profile
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Brpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string endpoint = 1;</code>
     * @return string
     */
    public function getEndpoint()
    {
        return $this->endpoint;
    }

    /**
     * Generated from protobuf field <code>string endpoint = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setEndpoint(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->endpoint = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string region = 2;</code>
     * @return string
     */
    public function getRegion()
    {
        return $this->region;
    }

    /**
     * Generated from protobuf field <code>string region = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRegion(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->region = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string bucket = 3;</code>
     * @return string
     */
    public function getBucket()
    {
        return $this->bucket;
    }

    /**
     * Generated from protobuf field <code>string bucket = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setBucket(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->bucket = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string prefix = 4;</code>
     * @return string
     */
    public function getPrefix()
    {
        return $this->prefix;
    }

    /**
     * Generated from protobuf field <code>string prefix = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPrefix(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->prefix = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string storage_class = 5;</code>
     * @return string
     */
    public function getStorageClass()
    {
        return $this->storage_class;
    }

    /**
     * Generated from protobuf field <code>string storage_class = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setStorageClass(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->storage_class = $var;

        return $this;
    }

    /**
     * server side encryption
     *
     * Generated from protobuf field <code>string sse = 6;</code>
     * @return string
     */
    public function getSse()
    {
        return $this->sse;
    }

    /**
     * server side encryption
     *
     * Generated from protobuf field <code>string sse = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setSse(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->sse = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string acl = 7;</code>
     * @return string
     */
    public function getAcl()
    {
        return $this->acl;
    }

    /**
     * Generated from protobuf field <code>string acl = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setAcl(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->acl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string access_key = 8;</code>
     * @return string
     */
    public function getAccessKey()
    {
        return $this->access_key;
    }

    /**
     * Generated from protobuf field <code>string access_key = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setAccessKey(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->access_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string secret_access_key = 9;</code>
     * @return string
     */
    public function getSecretAccessKey()
    {
        return $this->secret_access_key;
    }

    /**
     * Generated from protobuf field <code>string secret_access_key = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setSecretAccessKey(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->secret_access_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool force_path_style = 10;</code>
     * @return bool
     */
    public function getForcePathStyle()
    {
        return $this->force_path_style;
    }

    /**
     * Generated from protobuf field <code>bool force_path_style = 10;</code>
     * @param bool $var
     * @return $this
     */
    public function setForcePathStyle(bool $var)
    {
        $this->force_path_style = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string sse_kms_key_id = 11;</code>
     * @return string
     */
    public function getSseKmsKeyId()
    {
        return $this->sse_kms_key_id;
    }

    /**
     * Generated from protobuf field <code>string sse_kms_key_id = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setSseKmsKeyId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->sse_kms_key_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string role_arn = 12;</code>
     * @return string
     */
    public function getRoleArn()
    {
        return $this->role_arn;
    }

    /**
     * Generated from protobuf field <code>string role_arn = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setRoleArn(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->role_arn = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string external_id = 13;</code>
     * @return string
     */
    public function getExternalId()
    {
        return $this->external_id;
    }

    /**
     * Generated from protobuf field <code>string external_id = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setExternalId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->external_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool object_lock_enabled = 14;</code>
     * @return bool
     */
    public function getObjectLockEnabled()
    {
        return $this->object_lock_enabled;
    }

    /**
     * Generated from protobuf field <code>bool object_lock_enabled = 14;</code>
     * @param bool $var
     * @return $this
     */
    public function setObjectLockEnabled(bool $var)
    {
        $this->object_lock_enabled = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string session_token = 15;</code>
     * @return string
     */
    public function getSessionToken()
    {
        return $this->session_token;
    }

    /**
     * Generated from protobuf field <code>string session_token = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setSessionToken(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->session_token = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string provider = 16;</code>
     * @return string
     */
    public function getProvider()
    {
        return $this->provider;
    }

    /**
     * Generated from protobuf field <code>string provider = 16;</code>
     * @param string $var
     * @return $this
     */
    public function setProvider(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->provider = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string profile = 17;</code>
     * @return string
     */
    public function getProfile()
    {
        return $this->profile;
    }

    /**
     * Generated from protobuf field <code>string profile = 17;</code>
     * @param string $var
     * @return $this
     */
    public function setProfile(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->profile = $var;

        return $this;
    }

}

