<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brpb.proto

namespace CrazyGoat\Proto\Backup;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>backup.Schema</code>
 */
class Schema extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes db = 1;</code>
     */
    protected $db = '';
    /**
     * Generated from protobuf field <code>bytes table = 2;</code>
     */
    protected $table = '';
    /**
     * Generated from protobuf field <code>uint64 crc64xor = 3;</code>
     */
    protected $crc64xor = 0;
    /**
     * Generated from protobuf field <code>uint64 total_kvs = 4;</code>
     */
    protected $total_kvs = 0;
    /**
     * Generated from protobuf field <code>uint64 total_bytes = 5;</code>
     */
    protected $total_bytes = 0;
    /**
     * Generated from protobuf field <code>uint32 tiflash_replicas = 6;</code>
     */
    protected $tiflash_replicas = 0;
    /**
     * stats represents the dump stats for a analyzed table, which generate by DumpStatsToJSON
     * https://github.com/pingcap/tidb/blob/e136429d8dc5d70f43cd3f94179b0b9f47595097/statistics/handle/dump.go#L116
     *
     * Generated from protobuf field <code>bytes stats = 7;</code>
     */
    protected $stats = '';
    /**
     * An index of files that contains stats data
     *
     * Generated from protobuf field <code>repeated .backup.StatsFileIndex stats_index = 8;</code>
     */
    private $stats_index;
    /**
     * is_merge_option_allowed indicates whether merge option is allowed for this schema.
     * For backward compatibility, this field defaults to false when not present.
     *
     * Generated from protobuf field <code>bool is_merge_option_allowed = 9;</code>
     */
    protected $is_merge_option_allowed = false;
    /**
     * partition_merge_option_allowed indicates whether merge option is allowed for each partition.
     * is_merge_option_allowed is table level, and the partition_merge_option_allowed is partition level.
     *
     * Generated from protobuf field <code>map<string, bool> partition_merge_option_allowed = 10;</code>
     */
    private $partition_merge_option_allowed;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $db
     *     @type string $table
     *     @type int|string $crc64xor
     *     @type int|string $total_kvs
     *     @type int|string $total_bytes
     *     @type int $tiflash_replicas
     *     @type string $stats
     *           stats represents the dump stats for a analyzed table, which generate by DumpStatsToJSON
     *           https://github.com/pingcap/tidb/blob/e136429d8dc5d70f43cd3f94179b0b9f47595097/statistics/handle/dump.go#L116
     *     @type \CrazyGoat\Proto\Backup\StatsFileIndex[] $stats_index
     *           An index of files that contains stats data
     *     @type bool $is_merge_option_allowed
     *           is_merge_option_allowed indicates whether merge option is allowed for this schema.
     *           For backward compatibility, this field defaults to false when not present.
     *     @type array|\Google\Protobuf\Internal\MapField $partition_merge_option_allowed
     *           partition_merge_option_allowed indicates whether merge option is allowed for each partition.
     *           is_merge_option_allowed is table level, and the partition_merge_option_allowed is partition level.
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Brpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes db = 1;</code>
     * @return string
     */
    public function getDb()
    {
        return $this->db;
    }

    /**
     * Generated from protobuf field <code>bytes db = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDb(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->db = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes table = 2;</code>
     * @return string
     */
    public function getTable()
    {
        return $this->table;
    }

    /**
     * Generated from protobuf field <code>bytes table = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTable(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->table = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 crc64xor = 3;</code>
     * @return int|string
     */
    public function getCrc64Xor()
    {
        return $this->crc64xor;
    }

    /**
     * Generated from protobuf field <code>uint64 crc64xor = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCrc64Xor(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->crc64xor = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 total_kvs = 4;</code>
     * @return int|string
     */
    public function getTotalKvs()
    {
        return $this->total_kvs;
    }

    /**
     * Generated from protobuf field <code>uint64 total_kvs = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalKvs(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->total_kvs = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 total_bytes = 5;</code>
     * @return int|string
     */
    public function getTotalBytes()
    {
        return $this->total_bytes;
    }

    /**
     * Generated from protobuf field <code>uint64 total_bytes = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalBytes(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->total_bytes = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 tiflash_replicas = 6;</code>
     * @return int
     */
    public function getTiflashReplicas()
    {
        return $this->tiflash_replicas;
    }

    /**
     * Generated from protobuf field <code>uint32 tiflash_replicas = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setTiflashReplicas(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->tiflash_replicas = $var;

        return $this;
    }

    /**
     * stats represents the dump stats for a analyzed table, which generate by DumpStatsToJSON
     * https://github.com/pingcap/tidb/blob/e136429d8dc5d70f43cd3f94179b0b9f47595097/statistics/handle/dump.go#L116
     *
     * Generated from protobuf field <code>bytes stats = 7;</code>
     * @return string
     */
    public function getStats()
    {
        return $this->stats;
    }

    /**
     * stats represents the dump stats for a analyzed table, which generate by DumpStatsToJSON
     * https://github.com/pingcap/tidb/blob/e136429d8dc5d70f43cd3f94179b0b9f47595097/statistics/handle/dump.go#L116
     *
     * Generated from protobuf field <code>bytes stats = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setStats(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->stats = $var;

        return $this;
    }

    /**
     * An index of files that contains stats data
     *
     * Generated from protobuf field <code>repeated .backup.StatsFileIndex stats_index = 8;</code>
     * @return RepeatedField<\CrazyGoat\Proto\Backup\StatsFileIndex>
     */
    public function getStatsIndex()
    {
        return $this->stats_index;
    }

    /**
     * An index of files that contains stats data
     *
     * Generated from protobuf field <code>repeated .backup.StatsFileIndex stats_index = 8;</code>
     * @param \CrazyGoat\Proto\Backup\StatsFileIndex[] $var
     * @return $this
     */
    public function setStatsIndex(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \CrazyGoat\Proto\Backup\StatsFileIndex::class);
        $this->stats_index = $arr;

        return $this;
    }

    /**
     * is_merge_option_allowed indicates whether merge option is allowed for this schema.
     * For backward compatibility, this field defaults to false when not present.
     *
     * Generated from protobuf field <code>bool is_merge_option_allowed = 9;</code>
     * @return bool
     */
    public function getIsMergeOptionAllowed()
    {
        return $this->is_merge_option_allowed;
    }

    /**
     * is_merge_option_allowed indicates whether merge option is allowed for this schema.
     * For backward compatibility, this field defaults to false when not present.
     *
     * Generated from protobuf field <code>bool is_merge_option_allowed = 9;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsMergeOptionAllowed(bool $var)
    {
        $this->is_merge_option_allowed = $var;

        return $this;
    }

    /**
     * partition_merge_option_allowed indicates whether merge option is allowed for each partition.
     * is_merge_option_allowed is table level, and the partition_merge_option_allowed is partition level.
     *
     * Generated from protobuf field <code>map<string, bool> partition_merge_option_allowed = 10;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getPartitionMergeOptionAllowed()
    {
        return $this->partition_merge_option_allowed;
    }

    /**
     * partition_merge_option_allowed indicates whether merge option is allowed for each partition.
     * is_merge_option_allowed is table level, and the partition_merge_option_allowed is partition level.
     *
     * Generated from protobuf field <code>map<string, bool> partition_merge_option_allowed = 10;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setPartitionMergeOptionAllowed(array|\Google\Protobuf\Internal\MapField $var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::BOOL);
        $this->partition_merge_option_allowed = $arr;

        return $this;
    }

}

