<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brpb.proto

namespace CrazyGoat\Proto\Backup;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>backup.SortedSubRanges</code>
 */
class SortedSubRanges extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .kvrpcpb.KeyRange sub_ranges = 1;</code>
     */
    private $sub_ranges;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CrazyGoat\Proto\Kvrpcpb\KeyRange[] $sub_ranges
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Brpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .kvrpcpb.KeyRange sub_ranges = 1;</code>
     * @return RepeatedField<\CrazyGoat\Proto\Kvrpcpb\KeyRange>
     */
    public function getSubRanges()
    {
        return $this->sub_ranges;
    }

    /**
     * Generated from protobuf field <code>repeated .kvrpcpb.KeyRange sub_ranges = 1;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\KeyRange[] $var
     * @return $this
     */
    public function setSubRanges(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \CrazyGoat\Proto\Kvrpcpb\KeyRange::class);
        $this->sub_ranges = $arr;

        return $this;
    }

}

