<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brpb.proto

namespace CrazyGoat\Proto\Backup;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>backup.Span</code>
 */
class Span extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 offset = 1;</code>
     */
    protected $offset = 0;
    /**
     * Generated from protobuf field <code>uint64 length = 2;</code>
     */
    protected $length = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $offset
     *     @type int|string $length
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Brpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 offset = 1;</code>
     * @return int|string
     */
    public function getOffset()
    {
        return $this->offset;
    }

    /**
     * Generated from protobuf field <code>uint64 offset = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOffset(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->offset = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 length = 2;</code>
     * @return int|string
     */
    public function getLength()
    {
        return $this->length;
    }

    /**
     * Generated from protobuf field <code>uint64 length = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLength(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->length = $var;

        return $this;
    }

}

