<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brpb.proto

namespace CrazyGoat\Proto\Backup;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>backup.StatsFile</code>
 */
class StatsFile extends \Google\Protobuf\Internal\Message
{
    /**
     * A set of files that contains json_tables.
     *
     * Generated from protobuf field <code>repeated .backup.StatsBlock blocks = 1;</code>
     */
    private $blocks;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CrazyGoat\Proto\Backup\StatsBlock[] $blocks
     *           A set of files that contains json_tables.
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Brpb::initOnce();
        parent::__construct($data);
    }

    /**
     * A set of files that contains json_tables.
     *
     * Generated from protobuf field <code>repeated .backup.StatsBlock blocks = 1;</code>
     * @return RepeatedField<\CrazyGoat\Proto\Backup\StatsBlock>
     */
    public function getBlocks()
    {
        return $this->blocks;
    }

    /**
     * A set of files that contains json_tables.
     *
     * Generated from protobuf field <code>repeated .backup.StatsBlock blocks = 1;</code>
     * @param \CrazyGoat\Proto\Backup\StatsBlock[] $var
     * @return $this
     */
    public function setBlocks(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \CrazyGoat\Proto\Backup\StatsBlock::class);
        $this->blocks = $arr;

        return $this;
    }

}

