<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brpb.proto

namespace CrazyGoat\Proto\Backup;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>backup.StatsFileIndex</code>
 */
class StatsFileIndex extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>bytes sha256 = 2;</code>
     */
    protected $sha256 = '';
    /**
     * the size of the file content encrypted
     *
     * Generated from protobuf field <code>uint64 size_enc = 3;</code>
     */
    protected $size_enc = 0;
    /**
     * the size of the original file content
     *
     * Generated from protobuf field <code>uint64 size_ori = 4;</code>
     */
    protected $size_ori = 0;
    /**
     * cipher_iv is used for AES cipher
     *
     * Generated from protobuf field <code>bytes cipher_iv = 5;</code>
     */
    protected $cipher_iv = '';
    /**
     * If the size of the stats is very small, save the data into the metafile
     *
     * Generated from protobuf field <code>bytes inline_data = 6;</code>
     */
    protected $inline_data = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type string $sha256
     *     @type int|string $size_enc
     *           the size of the file content encrypted
     *     @type int|string $size_ori
     *           the size of the original file content
     *     @type string $cipher_iv
     *           cipher_iv is used for AES cipher
     *     @type string $inline_data
     *           If the size of the stats is very small, save the data into the metafile
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Brpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes sha256 = 2;</code>
     * @return string
     */
    public function getSha256()
    {
        return $this->sha256;
    }

    /**
     * Generated from protobuf field <code>bytes sha256 = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSha256(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->sha256 = $var;

        return $this;
    }

    /**
     * the size of the file content encrypted
     *
     * Generated from protobuf field <code>uint64 size_enc = 3;</code>
     * @return int|string
     */
    public function getSizeEnc()
    {
        return $this->size_enc;
    }

    /**
     * the size of the file content encrypted
     *
     * Generated from protobuf field <code>uint64 size_enc = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSizeEnc(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->size_enc = $var;

        return $this;
    }

    /**
     * the size of the original file content
     *
     * Generated from protobuf field <code>uint64 size_ori = 4;</code>
     * @return int|string
     */
    public function getSizeOri()
    {
        return $this->size_ori;
    }

    /**
     * the size of the original file content
     *
     * Generated from protobuf field <code>uint64 size_ori = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSizeOri(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->size_ori = $var;

        return $this;
    }

    /**
     * cipher_iv is used for AES cipher
     *
     * Generated from protobuf field <code>bytes cipher_iv = 5;</code>
     * @return string
     */
    public function getCipherIv()
    {
        return $this->cipher_iv;
    }

    /**
     * cipher_iv is used for AES cipher
     *
     * Generated from protobuf field <code>bytes cipher_iv = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setCipherIv(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->cipher_iv = $var;

        return $this;
    }

    /**
     * If the size of the stats is very small, save the data into the metafile
     *
     * Generated from protobuf field <code>bytes inline_data = 6;</code>
     * @return string
     */
    public function getInlineData()
    {
        return $this->inline_data;
    }

    /**
     * If the size of the stats is very small, save the data into the metafile
     *
     * Generated from protobuf field <code>bytes inline_data = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setInlineData(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->inline_data = $var;

        return $this;
    }

}

