<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brpb.proto

namespace CrazyGoat\Proto\Backup;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>backup.StorageBackend</code>
 */
class StorageBackend extends \Google\Protobuf\Internal\Message
{
    protected $backend;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CrazyGoat\Proto\Backup\Noop $noop
     *     @type \CrazyGoat\Proto\Backup\Local $local
     *     @type \CrazyGoat\Proto\Backup\S3 $s3
     *     @type \CrazyGoat\Proto\Backup\GCS $gcs
     *     @type \CrazyGoat\Proto\Backup\CloudDynamic $cloud_dynamic
     *     @type \CrazyGoat\Proto\Backup\HDFS $hdfs
     *     @type \CrazyGoat\Proto\Backup\AzureBlobStorage $azure_blob_storage
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Brpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.backup.Noop noop = 1;</code>
     * @return \CrazyGoat\Proto\Backup\Noop|null
     */
    public function getNoop()
    {
        return $this->readOneof(1);
    }

    public function hasNoop()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.backup.Noop noop = 1;</code>
     * @param \CrazyGoat\Proto\Backup\Noop $var
     * @return $this
     */
    public function setNoop(\CrazyGoat\Proto\Backup\Noop|null $var)
    {
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.backup.Local local = 2;</code>
     * @return \CrazyGoat\Proto\Backup\Local|null
     */
    public function getLocal()
    {
        return $this->readOneof(2);
    }

    public function hasLocal()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.backup.Local local = 2;</code>
     * @param \CrazyGoat\Proto\Backup\Local $var
     * @return $this
     */
    public function setLocal(\CrazyGoat\Proto\Backup\Local|null $var)
    {
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.backup.S3 s3 = 3;</code>
     * @return \CrazyGoat\Proto\Backup\S3|null
     */
    public function getS3()
    {
        return $this->readOneof(3);
    }

    public function hasS3()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.backup.S3 s3 = 3;</code>
     * @param \CrazyGoat\Proto\Backup\S3 $var
     * @return $this
     */
    public function setS3(\CrazyGoat\Proto\Backup\S3|null $var)
    {
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.backup.GCS gcs = 4;</code>
     * @return \CrazyGoat\Proto\Backup\GCS|null
     */
    public function getGcs()
    {
        return $this->readOneof(4);
    }

    public function hasGcs()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>.backup.GCS gcs = 4;</code>
     * @param \CrazyGoat\Proto\Backup\GCS $var
     * @return $this
     */
    public function setGcs(\CrazyGoat\Proto\Backup\GCS|null $var)
    {
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.backup.CloudDynamic cloud_dynamic = 5;</code>
     * @return \CrazyGoat\Proto\Backup\CloudDynamic|null
     */
    public function getCloudDynamic()
    {
        return $this->readOneof(5);
    }

    public function hasCloudDynamic()
    {
        return $this->hasOneof(5);
    }

    /**
     * Generated from protobuf field <code>.backup.CloudDynamic cloud_dynamic = 5;</code>
     * @param \CrazyGoat\Proto\Backup\CloudDynamic $var
     * @return $this
     */
    public function setCloudDynamic(\CrazyGoat\Proto\Backup\CloudDynamic|null $var)
    {
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.backup.HDFS hdfs = 6;</code>
     * @return \CrazyGoat\Proto\Backup\HDFS|null
     */
    public function getHdfs()
    {
        return $this->readOneof(6);
    }

    public function hasHdfs()
    {
        return $this->hasOneof(6);
    }

    /**
     * Generated from protobuf field <code>.backup.HDFS hdfs = 6;</code>
     * @param \CrazyGoat\Proto\Backup\HDFS $var
     * @return $this
     */
    public function setHdfs(\CrazyGoat\Proto\Backup\HDFS|null $var)
    {
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.backup.AzureBlobStorage azure_blob_storage = 7;</code>
     * @return \CrazyGoat\Proto\Backup\AzureBlobStorage|null
     */
    public function getAzureBlobStorage()
    {
        return $this->readOneof(7);
    }

    public function hasAzureBlobStorage()
    {
        return $this->hasOneof(7);
    }

    /**
     * Generated from protobuf field <code>.backup.AzureBlobStorage azure_blob_storage = 7;</code>
     * @param \CrazyGoat\Proto\Backup\AzureBlobStorage $var
     * @return $this
     */
    public function setAzureBlobStorage(\CrazyGoat\Proto\Backup\AzureBlobStorage|null $var)
    {
        $this->writeOneof(7, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getBackend()
    {
        return $this->whichOneof("backend");
    }

}

