<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brpb.proto

namespace CrazyGoat\Proto\Backup;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>backup.StreamBackupTaskSecurityConfig</code>
 */
class StreamBackupTaskSecurityConfig extends \Google\Protobuf\Internal\Message
{
    protected $encryption;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CrazyGoat\Proto\Backup\CipherInfo $plaintext_data_key
     *           not recommended in production. configure KMS based or locally managed master key instead in TiKV StreamBackupConfig
     *     @type \CrazyGoat\Proto\Backup\MasterKeyConfig $master_key_config
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Brpb::initOnce();
        parent::__construct($data);
    }

    /**
     * not recommended in production. configure KMS based or locally managed master key instead in TiKV StreamBackupConfig
     *
     * Generated from protobuf field <code>.backup.CipherInfo plaintext_data_key = 1;</code>
     * @return \CrazyGoat\Proto\Backup\CipherInfo|null
     */
    public function getPlaintextDataKey()
    {
        return $this->readOneof(1);
    }

    public function hasPlaintextDataKey()
    {
        return $this->hasOneof(1);
    }

    /**
     * not recommended in production. configure KMS based or locally managed master key instead in TiKV StreamBackupConfig
     *
     * Generated from protobuf field <code>.backup.CipherInfo plaintext_data_key = 1;</code>
     * @param \CrazyGoat\Proto\Backup\CipherInfo $var
     * @return $this
     */
    public function setPlaintextDataKey(\CrazyGoat\Proto\Backup\CipherInfo|null $var)
    {
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.backup.MasterKeyConfig master_key_config = 2;</code>
     * @return \CrazyGoat\Proto\Backup\MasterKeyConfig|null
     */
    public function getMasterKeyConfig()
    {
        return $this->readOneof(2);
    }

    public function hasMasterKeyConfig()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.backup.MasterKeyConfig master_key_config = 2;</code>
     * @param \CrazyGoat\Proto\Backup\MasterKeyConfig $var
     * @return $this
     */
    public function setMasterKeyConfig(\CrazyGoat\Proto\Backup\MasterKeyConfig|null $var)
    {
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getEncryption()
    {
        return $this->whichOneof("encryption");
    }

}

