<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brpb.proto

namespace CrazyGoat\Proto\Backup;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * The message saves the physical table checksum
 *
 * Generated from protobuf message <code>backup.TableMeta</code>
 */
class TableMeta extends \Google\Protobuf\Internal\Message
{
    /**
     * physical id is either table id or partition id
     *
     * Generated from protobuf field <code>int64 physical_id = 1;</code>
     */
    protected $physical_id = 0;
    /**
     * Generated from protobuf field <code>uint64 crc64xor = 2;</code>
     */
    protected $crc64xor = 0;
    /**
     * Generated from protobuf field <code>uint64 total_kvs = 3;</code>
     */
    protected $total_kvs = 0;
    /**
     * Generated from protobuf field <code>uint64 total_bytes = 4;</code>
     */
    protected $total_bytes = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $physical_id
     *           physical id is either table id or partition id
     *     @type int|string $crc64xor
     *     @type int|string $total_kvs
     *     @type int|string $total_bytes
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Brpb::initOnce();
        parent::__construct($data);
    }

    /**
     * physical id is either table id or partition id
     *
     * Generated from protobuf field <code>int64 physical_id = 1;</code>
     * @return int|string
     */
    public function getPhysicalId()
    {
        return $this->physical_id;
    }

    /**
     * physical id is either table id or partition id
     *
     * Generated from protobuf field <code>int64 physical_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPhysicalId(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->physical_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 crc64xor = 2;</code>
     * @return int|string
     */
    public function getCrc64Xor()
    {
        return $this->crc64xor;
    }

    /**
     * Generated from protobuf field <code>uint64 crc64xor = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCrc64Xor(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->crc64xor = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 total_kvs = 3;</code>
     * @return int|string
     */
    public function getTotalKvs()
    {
        return $this->total_kvs;
    }

    /**
     * Generated from protobuf field <code>uint64 total_kvs = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalKvs(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->total_kvs = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 total_bytes = 4;</code>
     * @return int|string
     */
    public function getTotalBytes()
    {
        return $this->total_bytes;
    }

    /**
     * Generated from protobuf field <code>uint64 total_bytes = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalBytes(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->total_bytes = $var;

        return $this;
    }

}

