<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: encryptionpb.proto

namespace CrazyGoat\Proto\Encryptionpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>encryptionpb.AzureKms</code>
 */
class AzureKms extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string tenant_id = 1;</code>
     */
    protected $tenant_id = '';
    /**
     * Generated from protobuf field <code>string client_id = 2;</code>
     */
    protected $client_id = '';
    /**
     * Generated from protobuf field <code>string client_secret = 3;</code>
     */
    protected $client_secret = '';
    /**
     * Key vault to encrypt/decrypt data key.
     *
     * Generated from protobuf field <code>string key_vault_url = 4;</code>
     */
    protected $key_vault_url = '';
    /**
     * optional hsm used to generate data key
     *
     * Generated from protobuf field <code>string hsm_name = 5;</code>
     */
    protected $hsm_name = '';
    /**
     * Generated from protobuf field <code>string hsm_url = 6;</code>
     */
    protected $hsm_url = '';
    /**
     * Generated from protobuf field <code>string client_certificate = 7;</code>
     */
    protected $client_certificate = '';
    /**
     * Generated from protobuf field <code>string client_certificate_path = 8;</code>
     */
    protected $client_certificate_path = '';
    /**
     * Generated from protobuf field <code>string client_certificate_password = 9;</code>
     */
    protected $client_certificate_password = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $tenant_id
     *     @type string $client_id
     *     @type string $client_secret
     *     @type string $key_vault_url
     *           Key vault to encrypt/decrypt data key.
     *     @type string $hsm_name
     *           optional hsm used to generate data key
     *     @type string $hsm_url
     *     @type string $client_certificate
     *     @type string $client_certificate_path
     *     @type string $client_certificate_password
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Encryptionpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string tenant_id = 1;</code>
     * @return string
     */
    public function getTenantId()
    {
        return $this->tenant_id;
    }

    /**
     * Generated from protobuf field <code>string tenant_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTenantId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->tenant_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string client_id = 2;</code>
     * @return string
     */
    public function getClientId()
    {
        return $this->client_id;
    }

    /**
     * Generated from protobuf field <code>string client_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setClientId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->client_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string client_secret = 3;</code>
     * @return string
     */
    public function getClientSecret()
    {
        return $this->client_secret;
    }

    /**
     * Generated from protobuf field <code>string client_secret = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setClientSecret(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->client_secret = $var;

        return $this;
    }

    /**
     * Key vault to encrypt/decrypt data key.
     *
     * Generated from protobuf field <code>string key_vault_url = 4;</code>
     * @return string
     */
    public function getKeyVaultUrl()
    {
        return $this->key_vault_url;
    }

    /**
     * Key vault to encrypt/decrypt data key.
     *
     * Generated from protobuf field <code>string key_vault_url = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setKeyVaultUrl(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->key_vault_url = $var;

        return $this;
    }

    /**
     * optional hsm used to generate data key
     *
     * Generated from protobuf field <code>string hsm_name = 5;</code>
     * @return string
     */
    public function getHsmName()
    {
        return $this->hsm_name;
    }

    /**
     * optional hsm used to generate data key
     *
     * Generated from protobuf field <code>string hsm_name = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setHsmName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->hsm_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string hsm_url = 6;</code>
     * @return string
     */
    public function getHsmUrl()
    {
        return $this->hsm_url;
    }

    /**
     * Generated from protobuf field <code>string hsm_url = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setHsmUrl(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->hsm_url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string client_certificate = 7;</code>
     * @return string
     */
    public function getClientCertificate()
    {
        return $this->client_certificate;
    }

    /**
     * Generated from protobuf field <code>string client_certificate = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setClientCertificate(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->client_certificate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string client_certificate_path = 8;</code>
     * @return string
     */
    public function getClientCertificatePath()
    {
        return $this->client_certificate_path;
    }

    /**
     * Generated from protobuf field <code>string client_certificate_path = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setClientCertificatePath(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->client_certificate_path = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string client_certificate_password = 9;</code>
     * @return string
     */
    public function getClientCertificatePassword()
    {
        return $this->client_certificate_password;
    }

    /**
     * Generated from protobuf field <code>string client_certificate_password = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setClientCertificatePassword(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->client_certificate_password = $var;

        return $this;
    }

}

