<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: encryptionpb.proto

namespace CrazyGoat\Proto\Encryptionpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>encryptionpb.EncryptedContent</code>
 */
class EncryptedContent extends \Google\Protobuf\Internal\Message
{
    /**
     * Metadata of the encrypted content.
     * Eg. IV, method and KMS key ID
     * It is preferred to define new fields for extra metadata than using this metadata map.
     *
     * Generated from protobuf field <code>map<string, bytes> metadata = 1;</code>
     */
    private $metadata;
    /**
     * Encrypted content.
     *
     * Generated from protobuf field <code>bytes content = 2;</code>
     */
    protected $content = '';
    /**
     * Master key used to encrypt the content.
     *
     * Generated from protobuf field <code>.encryptionpb.MasterKey master_key = 3;</code>
     */
    protected $master_key = null;
    /**
     * Initilization vector (IV) used.
     *
     * Generated from protobuf field <code>bytes iv = 4;</code>
     */
    protected $iv = '';
    /**
     * Encrypted data key generated by KMS and used to actually encrypt data.
     * Valid only when KMS is used.
     *
     * Generated from protobuf field <code>bytes ciphertext_key = 5;</code>
     */
    protected $ciphertext_key = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $metadata
     *           Metadata of the encrypted content.
     *           Eg. IV, method and KMS key ID
     *           It is preferred to define new fields for extra metadata than using this metadata map.
     *     @type string $content
     *           Encrypted content.
     *     @type \CrazyGoat\Proto\Encryptionpb\MasterKey $master_key
     *           Master key used to encrypt the content.
     *     @type string $iv
     *           Initilization vector (IV) used.
     *     @type string $ciphertext_key
     *           Encrypted data key generated by KMS and used to actually encrypt data.
     *           Valid only when KMS is used.
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Encryptionpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Metadata of the encrypted content.
     * Eg. IV, method and KMS key ID
     * It is preferred to define new fields for extra metadata than using this metadata map.
     *
     * Generated from protobuf field <code>map<string, bytes> metadata = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    /**
     * Metadata of the encrypted content.
     * Eg. IV, method and KMS key ID
     * It is preferred to define new fields for extra metadata than using this metadata map.
     *
     * Generated from protobuf field <code>map<string, bytes> metadata = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setMetadata(array|\Google\Protobuf\Internal\MapField $var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->metadata = $arr;

        return $this;
    }

    /**
     * Encrypted content.
     *
     * Generated from protobuf field <code>bytes content = 2;</code>
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * Encrypted content.
     *
     * Generated from protobuf field <code>bytes content = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setContent(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->content = $var;

        return $this;
    }

    /**
     * Master key used to encrypt the content.
     *
     * Generated from protobuf field <code>.encryptionpb.MasterKey master_key = 3;</code>
     * @return \CrazyGoat\Proto\Encryptionpb\MasterKey|null
     */
    public function getMasterKey()
    {
        return $this->master_key;
    }

    public function hasMasterKey()
    {
        return isset($this->master_key);
    }

    public function clearMasterKey()
    {
        unset($this->master_key);
    }

    /**
     * Master key used to encrypt the content.
     *
     * Generated from protobuf field <code>.encryptionpb.MasterKey master_key = 3;</code>
     * @param \CrazyGoat\Proto\Encryptionpb\MasterKey $var
     * @return $this
     */
    public function setMasterKey(\CrazyGoat\Proto\Encryptionpb\MasterKey|null $var)
    {
        $this->master_key = $var;

        return $this;
    }

    /**
     * Initilization vector (IV) used.
     *
     * Generated from protobuf field <code>bytes iv = 4;</code>
     * @return string
     */
    public function getIv()
    {
        return $this->iv;
    }

    /**
     * Initilization vector (IV) used.
     *
     * Generated from protobuf field <code>bytes iv = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setIv(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->iv = $var;

        return $this;
    }

    /**
     * Encrypted data key generated by KMS and used to actually encrypt data.
     * Valid only when KMS is used.
     *
     * Generated from protobuf field <code>bytes ciphertext_key = 5;</code>
     * @return string
     */
    public function getCiphertextKey()
    {
        return $this->ciphertext_key;
    }

    /**
     * Encrypted data key generated by KMS and used to actually encrypt data.
     * Valid only when KMS is used.
     *
     * Generated from protobuf field <code>bytes ciphertext_key = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setCiphertextKey(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->ciphertext_key = $var;

        return $this;
    }

}

