<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: encryptionpb.proto

namespace CrazyGoat\Proto\Encryptionpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>encryptionpb.KeyDictionary</code>
 */
class KeyDictionary extends \Google\Protobuf\Internal\Message
{
    /**
     * A map of key ID to dat key.
     *
     * Generated from protobuf field <code>map<uint64, .encryptionpb.DataKey> keys = 1;</code>
     */
    private $keys;
    /**
     * ID of a key currently in use.
     *
     * Generated from protobuf field <code>uint64 current_key_id = 2;</code>
     */
    protected $current_key_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $keys
     *           A map of key ID to dat key.
     *     @type int|string $current_key_id
     *           ID of a key currently in use.
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Encryptionpb::initOnce();
        parent::__construct($data);
    }

    /**
     * A map of key ID to dat key.
     *
     * Generated from protobuf field <code>map<uint64, .encryptionpb.DataKey> keys = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getKeys()
    {
        return $this->keys;
    }

    /**
     * A map of key ID to dat key.
     *
     * Generated from protobuf field <code>map<uint64, .encryptionpb.DataKey> keys = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setKeys(array|\Google\Protobuf\Internal\MapField $var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::UINT64, \Google\Protobuf\Internal\GPBType::MESSAGE, \CrazyGoat\Proto\Encryptionpb\DataKey::class);
        $this->keys = $arr;

        return $this;
    }

    /**
     * ID of a key currently in use.
     *
     * Generated from protobuf field <code>uint64 current_key_id = 2;</code>
     * @return int|string
     */
    public function getCurrentKeyId()
    {
        return $this->current_key_id;
    }

    /**
     * ID of a key currently in use.
     *
     * Generated from protobuf field <code>uint64 current_key_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCurrentKeyId(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->current_key_id = $var;

        return $this;
    }

}

