<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: encryptionpb.proto

namespace CrazyGoat\Proto\Encryptionpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * MasterKeyFile is a master key backed by a file containing encryption key in human-readable
 * hex format.
 *
 * Generated from protobuf message <code>encryptionpb.MasterKeyFile</code>
 */
class MasterKeyFile extends \Google\Protobuf\Internal\Message
{
    /**
     * Local file path.
     *
     * Generated from protobuf field <code>string path = 1;</code>
     */
    protected $path = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $path
     *           Local file path.
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Encryptionpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Local file path.
     *
     * Generated from protobuf field <code>string path = 1;</code>
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * Local file path.
     *
     * Generated from protobuf field <code>string path = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPath(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->path = $var;

        return $this;
    }

}

