<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: encryptionpb.proto

namespace CrazyGoat\Proto\Encryptionpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * MasterKeyKms is a master key backed by KMS service that manages the encryption key,
 * and provide API to encrypt and decrypt a data key, which is used to encrypt the content.
 *
 * Generated from protobuf message <code>encryptionpb.MasterKeyKms</code>
 */
class MasterKeyKms extends \Google\Protobuf\Internal\Message
{
    /**
     * KMS vendor.
     *
     * Generated from protobuf field <code>string vendor = 1;</code>
     */
    protected $vendor = '';
    /**
     * KMS key id.
     *
     * Generated from protobuf field <code>string key_id = 2;</code>
     */
    protected $key_id = '';
    /**
     * KMS region.
     *
     * Generated from protobuf field <code>string region = 3;</code>
     */
    protected $region = '';
    /**
     * KMS endpoint. Normally not needed.
     *
     * Generated from protobuf field <code>string endpoint = 4;</code>
     */
    protected $endpoint = '';
    /**
     * optional, used to set up azure master key backend
     *
     * Generated from protobuf field <code>.encryptionpb.AzureKms azure_kms = 5;</code>
     */
    protected $azure_kms = null;
    /**
     * optional, used to set up gcp master key backend
     *
     * Generated from protobuf field <code>.encryptionpb.GcpKms gcp_kms = 6;</code>
     */
    protected $gcp_kms = null;
    /**
     * optional, used to set up aws master key backend
     *
     * Generated from protobuf field <code>.encryptionpb.AwsKms aws_kms = 7;</code>
     */
    protected $aws_kms = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $vendor
     *           KMS vendor.
     *     @type string $key_id
     *           KMS key id.
     *     @type string $region
     *           KMS region.
     *     @type string $endpoint
     *           KMS endpoint. Normally not needed.
     *     @type \CrazyGoat\Proto\Encryptionpb\AzureKms $azure_kms
     *           optional, used to set up azure master key backend
     *     @type \CrazyGoat\Proto\Encryptionpb\GcpKms $gcp_kms
     *           optional, used to set up gcp master key backend
     *     @type \CrazyGoat\Proto\Encryptionpb\AwsKms $aws_kms
     *           optional, used to set up aws master key backend
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Encryptionpb::initOnce();
        parent::__construct($data);
    }

    /**
     * KMS vendor.
     *
     * Generated from protobuf field <code>string vendor = 1;</code>
     * @return string
     */
    public function getVendor()
    {
        return $this->vendor;
    }

    /**
     * KMS vendor.
     *
     * Generated from protobuf field <code>string vendor = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setVendor(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->vendor = $var;

        return $this;
    }

    /**
     * KMS key id.
     *
     * Generated from protobuf field <code>string key_id = 2;</code>
     * @return string
     */
    public function getKeyId()
    {
        return $this->key_id;
    }

    /**
     * KMS key id.
     *
     * Generated from protobuf field <code>string key_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setKeyId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->key_id = $var;

        return $this;
    }

    /**
     * KMS region.
     *
     * Generated from protobuf field <code>string region = 3;</code>
     * @return string
     */
    public function getRegion()
    {
        return $this->region;
    }

    /**
     * KMS region.
     *
     * Generated from protobuf field <code>string region = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setRegion(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->region = $var;

        return $this;
    }

    /**
     * KMS endpoint. Normally not needed.
     *
     * Generated from protobuf field <code>string endpoint = 4;</code>
     * @return string
     */
    public function getEndpoint()
    {
        return $this->endpoint;
    }

    /**
     * KMS endpoint. Normally not needed.
     *
     * Generated from protobuf field <code>string endpoint = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setEndpoint(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->endpoint = $var;

        return $this;
    }

    /**
     * optional, used to set up azure master key backend
     *
     * Generated from protobuf field <code>.encryptionpb.AzureKms azure_kms = 5;</code>
     * @return \CrazyGoat\Proto\Encryptionpb\AzureKms|null
     */
    public function getAzureKms()
    {
        return $this->azure_kms;
    }

    public function hasAzureKms()
    {
        return isset($this->azure_kms);
    }

    public function clearAzureKms()
    {
        unset($this->azure_kms);
    }

    /**
     * optional, used to set up azure master key backend
     *
     * Generated from protobuf field <code>.encryptionpb.AzureKms azure_kms = 5;</code>
     * @param \CrazyGoat\Proto\Encryptionpb\AzureKms $var
     * @return $this
     */
    public function setAzureKms(\CrazyGoat\Proto\Encryptionpb\AzureKms|null $var)
    {
        $this->azure_kms = $var;

        return $this;
    }

    /**
     * optional, used to set up gcp master key backend
     *
     * Generated from protobuf field <code>.encryptionpb.GcpKms gcp_kms = 6;</code>
     * @return \CrazyGoat\Proto\Encryptionpb\GcpKms|null
     */
    public function getGcpKms()
    {
        return $this->gcp_kms;
    }

    public function hasGcpKms()
    {
        return isset($this->gcp_kms);
    }

    public function clearGcpKms()
    {
        unset($this->gcp_kms);
    }

    /**
     * optional, used to set up gcp master key backend
     *
     * Generated from protobuf field <code>.encryptionpb.GcpKms gcp_kms = 6;</code>
     * @param \CrazyGoat\Proto\Encryptionpb\GcpKms $var
     * @return $this
     */
    public function setGcpKms(\CrazyGoat\Proto\Encryptionpb\GcpKms|null $var)
    {
        $this->gcp_kms = $var;

        return $this;
    }

    /**
     * optional, used to set up aws master key backend
     *
     * Generated from protobuf field <code>.encryptionpb.AwsKms aws_kms = 7;</code>
     * @return \CrazyGoat\Proto\Encryptionpb\AwsKms|null
     */
    public function getAwsKms()
    {
        return $this->aws_kms;
    }

    public function hasAwsKms()
    {
        return isset($this->aws_kms);
    }

    public function clearAwsKms()
    {
        unset($this->aws_kms);
    }

    /**
     * optional, used to set up aws master key backend
     *
     * Generated from protobuf field <code>.encryptionpb.AwsKms aws_kms = 7;</code>
     * @param \CrazyGoat\Proto\Encryptionpb\AwsKms $var
     * @return $this
     */
    public function setAwsKms(\CrazyGoat\Proto\Encryptionpb\AwsKms|null $var)
    {
        $this->aws_kms = $var;

        return $this;
    }

}

