<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: encryptionpb.proto

namespace CrazyGoat\Proto\Encryptionpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>encryptionpb.MasterKeyBased</code>
 */
class MasterKeyBased extends \Google\Protobuf\Internal\Message
{
    /**
     * encrypted data key with metadata
     *
     * Generated from protobuf field <code>repeated .encryptionpb.EncryptedContent data_key_encrypted_content = 1;</code>
     */
    private $data_key_encrypted_content;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CrazyGoat\Proto\Encryptionpb\EncryptedContent[] $data_key_encrypted_content
     *           encrypted data key with metadata
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Encryptionpb::initOnce();
        parent::__construct($data);
    }

    /**
     * encrypted data key with metadata
     *
     * Generated from protobuf field <code>repeated .encryptionpb.EncryptedContent data_key_encrypted_content = 1;</code>
     * @return RepeatedField<\CrazyGoat\Proto\Encryptionpb\EncryptedContent>
     */
    public function getDataKeyEncryptedContent()
    {
        return $this->data_key_encrypted_content;
    }

    /**
     * encrypted data key with metadata
     *
     * Generated from protobuf field <code>repeated .encryptionpb.EncryptedContent data_key_encrypted_content = 1;</code>
     * @param \CrazyGoat\Proto\Encryptionpb\EncryptedContent[] $var
     * @return $this
     */
    public function setDataKeyEncryptedContent(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \CrazyGoat\Proto\Encryptionpb\EncryptedContent::class);
        $this->data_key_encrypted_content = $arr;

        return $this;
    }

}

