<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kvrpcpb.proto

namespace CrazyGoat\Proto\Kvrpcpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>kvrpcpb.MvccLock</code>
 */
class MvccLock extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.kvrpcpb.Op type = 1;</code>
     */
    protected $type = 0;
    /**
     * Generated from protobuf field <code>uint64 start_ts = 2;</code>
     */
    protected $start_ts = 0;
    /**
     * Generated from protobuf field <code>bytes primary = 3;</code>
     */
    protected $primary = '';
    /**
     * Generated from protobuf field <code>bytes short_value = 4;</code>
     */
    protected $short_value = '';
    /**
     * Generated from protobuf field <code>uint64 ttl = 5;</code>
     */
    protected $ttl = 0;
    /**
     * Generated from protobuf field <code>uint64 for_update_ts = 6;</code>
     */
    protected $for_update_ts = 0;
    /**
     * Generated from protobuf field <code>uint64 txn_size = 7;</code>
     */
    protected $txn_size = 0;
    /**
     * Generated from protobuf field <code>bool use_async_commit = 8;</code>
     */
    protected $use_async_commit = false;
    /**
     * Generated from protobuf field <code>repeated bytes secondaries = 9;</code>
     */
    private $secondaries;
    /**
     * Generated from protobuf field <code>repeated uint64 rollback_ts = 10;</code>
     */
    private $rollback_ts;
    /**
     * Generated from protobuf field <code>uint64 last_change_ts = 11;</code>
     */
    protected $last_change_ts = 0;
    /**
     * Generated from protobuf field <code>uint64 versions_to_last_change = 12;</code>
     */
    protected $versions_to_last_change = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $type
     *     @type int|string $start_ts
     *     @type string $primary
     *     @type string $short_value
     *     @type int|string $ttl
     *     @type int|string $for_update_ts
     *     @type int|string $txn_size
     *     @type bool $use_async_commit
     *     @type string[] $secondaries
     *     @type int[]|string[] $rollback_ts
     *     @type int|string $last_change_ts
     *     @type int|string $versions_to_last_change
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Kvrpcpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.Op type = 1;</code>
     * @return int one of the values in {@see \CrazyGoat\Proto\Kvrpcpb\Op}
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.Op type = 1;</code>
     * @param int $var one of the values in {@see \CrazyGoat\Proto\Kvrpcpb\Op}
     * @return $this
     */
    public function setType(int $var)
    {
        GPBUtil::checkEnum($var, \CrazyGoat\Proto\Kvrpcpb\Op::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 start_ts = 2;</code>
     * @return int|string
     */
    public function getStartTs()
    {
        return $this->start_ts;
    }

    /**
     * Generated from protobuf field <code>uint64 start_ts = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStartTs(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->start_ts = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes primary = 3;</code>
     * @return string
     */
    public function getPrimary()
    {
        return $this->primary;
    }

    /**
     * Generated from protobuf field <code>bytes primary = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPrimary(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->primary = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes short_value = 4;</code>
     * @return string
     */
    public function getShortValue()
    {
        return $this->short_value;
    }

    /**
     * Generated from protobuf field <code>bytes short_value = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setShortValue(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->short_value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 ttl = 5;</code>
     * @return int|string
     */
    public function getTtl()
    {
        return $this->ttl;
    }

    /**
     * Generated from protobuf field <code>uint64 ttl = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTtl(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->ttl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 for_update_ts = 6;</code>
     * @return int|string
     */
    public function getForUpdateTs()
    {
        return $this->for_update_ts;
    }

    /**
     * Generated from protobuf field <code>uint64 for_update_ts = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setForUpdateTs(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->for_update_ts = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 txn_size = 7;</code>
     * @return int|string
     */
    public function getTxnSize()
    {
        return $this->txn_size;
    }

    /**
     * Generated from protobuf field <code>uint64 txn_size = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTxnSize(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->txn_size = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool use_async_commit = 8;</code>
     * @return bool
     */
    public function getUseAsyncCommit()
    {
        return $this->use_async_commit;
    }

    /**
     * Generated from protobuf field <code>bool use_async_commit = 8;</code>
     * @param bool $var
     * @return $this
     */
    public function setUseAsyncCommit(bool $var)
    {
        $this->use_async_commit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes secondaries = 9;</code>
     * @return RepeatedField<string>
     */
    public function getSecondaries()
    {
        return $this->secondaries;
    }

    /**
     * Generated from protobuf field <code>repeated bytes secondaries = 9;</code>
     * @param string[] $var
     * @return $this
     */
    public function setSecondaries(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->secondaries = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint64 rollback_ts = 10;</code>
     * @return RepeatedField<int>|RepeatedField<string>
     */
    public function getRollbackTs()
    {
        return $this->rollback_ts;
    }

    /**
     * Generated from protobuf field <code>repeated uint64 rollback_ts = 10;</code>
     * @param int[]|string[] $var
     * @return $this
     */
    public function setRollbackTs(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT64);
        $this->rollback_ts = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 last_change_ts = 11;</code>
     * @return int|string
     */
    public function getLastChangeTs()
    {
        return $this->last_change_ts;
    }

    /**
     * Generated from protobuf field <code>uint64 last_change_ts = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLastChangeTs(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->last_change_ts = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 versions_to_last_change = 12;</code>
     * @return int|string
     */
    public function getVersionsToLastChange()
    {
        return $this->versions_to_last_change;
    }

    /**
     * Generated from protobuf field <code>uint64 versions_to_last_change = 12;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVersionsToLastChange(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->versions_to_last_change = $var;

        return $this;
    }

}

