<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kvrpcpb.proto

namespace CrazyGoat\Proto\Kvrpcpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>kvrpcpb.RawCASRequest</code>
 */
class RawCASRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.kvrpcpb.Context context = 1;</code>
     */
    protected $context = null;
    /**
     * Generated from protobuf field <code>bytes key = 2;</code>
     */
    protected $key = '';
    /**
     * Generated from protobuf field <code>bytes value = 3;</code>
     */
    protected $value = '';
    /**
     * Generated from protobuf field <code>bool previous_not_exist = 4;</code>
     */
    protected $previous_not_exist = false;
    /**
     * Generated from protobuf field <code>bytes previous_value = 5;</code>
     */
    protected $previous_value = '';
    /**
     * Generated from protobuf field <code>string cf = 6;</code>
     */
    protected $cf = '';
    /**
     * Generated from protobuf field <code>uint64 ttl = 7;</code>
     */
    protected $ttl = 0;
    /**
     * If `delete` is true, the request is to delete the key when the comparison succeeds
     *
     * Generated from protobuf field <code>bool delete = 8;</code>
     */
    protected $delete = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CrazyGoat\Proto\Kvrpcpb\Context $context
     *     @type string $key
     *     @type string $value
     *     @type bool $previous_not_exist
     *     @type string $previous_value
     *     @type string $cf
     *     @type int|string $ttl
     *     @type bool $delete
     *           If `delete` is true, the request is to delete the key when the comparison succeeds
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Kvrpcpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.Context context = 1;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\Context|null
     */
    public function getContext()
    {
        return $this->context;
    }

    public function hasContext()
    {
        return isset($this->context);
    }

    public function clearContext()
    {
        unset($this->context);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.Context context = 1;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\Context $var
     * @return $this
     */
    public function setContext(\CrazyGoat\Proto\Kvrpcpb\Context|null $var)
    {
        $this->context = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes key = 2;</code>
     * @return string
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * Generated from protobuf field <code>bytes key = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setKey(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes value = 3;</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Generated from protobuf field <code>bytes value = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setValue(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool previous_not_exist = 4;</code>
     * @return bool
     */
    public function getPreviousNotExist()
    {
        return $this->previous_not_exist;
    }

    /**
     * Generated from protobuf field <code>bool previous_not_exist = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setPreviousNotExist(bool $var)
    {
        $this->previous_not_exist = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes previous_value = 5;</code>
     * @return string
     */
    public function getPreviousValue()
    {
        return $this->previous_value;
    }

    /**
     * Generated from protobuf field <code>bytes previous_value = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setPreviousValue(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->previous_value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string cf = 6;</code>
     * @return string
     */
    public function getCf()
    {
        return $this->cf;
    }

    /**
     * Generated from protobuf field <code>string cf = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setCf(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->cf = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 ttl = 7;</code>
     * @return int|string
     */
    public function getTtl()
    {
        return $this->ttl;
    }

    /**
     * Generated from protobuf field <code>uint64 ttl = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTtl(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->ttl = $var;

        return $this;
    }

    /**
     * If `delete` is true, the request is to delete the key when the comparison succeeds
     *
     * Generated from protobuf field <code>bool delete = 8;</code>
     * @return bool
     */
    public function getDelete()
    {
        return $this->delete;
    }

    /**
     * If `delete` is true, the request is to delete the key when the comparison succeeds
     *
     * Generated from protobuf field <code>bool delete = 8;</code>
     * @param bool $var
     * @return $this
     */
    public function setDelete(bool $var)
    {
        $this->delete = $var;

        return $this;
    }

}

