<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tikvpb.proto

namespace CrazyGoat\Proto\Tikvpb\BatchCommandsRequest;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>tikvpb.BatchCommandsRequest.Request</code>
 */
class Request extends \Google\Protobuf\Internal\Message
{
    protected $cmd;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CrazyGoat\Proto\Kvrpcpb\GetRequest $Get
     *     @type \CrazyGoat\Proto\Kvrpcpb\ScanRequest $Scan
     *     @type \CrazyGoat\Proto\Kvrpcpb\PrewriteRequest $Prewrite
     *     @type \CrazyGoat\Proto\Kvrpcpb\CommitRequest $Commit
     *     @type \CrazyGoat\Proto\Kvrpcpb\ImportRequest $Import
     *     @type \CrazyGoat\Proto\Kvrpcpb\CleanupRequest $Cleanup
     *     @type \CrazyGoat\Proto\Kvrpcpb\BatchGetRequest $BatchGet
     *     @type \CrazyGoat\Proto\Kvrpcpb\BatchRollbackRequest $BatchRollback
     *     @type \CrazyGoat\Proto\Kvrpcpb\ScanLockRequest $ScanLock
     *     @type \CrazyGoat\Proto\Kvrpcpb\ResolveLockRequest $ResolveLock
     *     @type \CrazyGoat\Proto\Kvrpcpb\GCRequest $GC
     *     @type \CrazyGoat\Proto\Kvrpcpb\DeleteRangeRequest $DeleteRange
     *     @type \CrazyGoat\Proto\Kvrpcpb\RawGetRequest $RawGet
     *     @type \CrazyGoat\Proto\Kvrpcpb\RawBatchGetRequest $RawBatchGet
     *     @type \CrazyGoat\Proto\Kvrpcpb\RawPutRequest $RawPut
     *     @type \CrazyGoat\Proto\Kvrpcpb\RawBatchPutRequest $RawBatchPut
     *     @type \CrazyGoat\Proto\Kvrpcpb\RawDeleteRequest $RawDelete
     *     @type \CrazyGoat\Proto\Kvrpcpb\RawBatchDeleteRequest $RawBatchDelete
     *     @type \CrazyGoat\Proto\Kvrpcpb\RawScanRequest $RawScan
     *     @type \CrazyGoat\Proto\Kvrpcpb\RawDeleteRangeRequest $RawDeleteRange
     *     @type \CrazyGoat\Proto\Kvrpcpb\RawBatchScanRequest $RawBatchScan
     *     @type \CrazyGoat\Proto\Coprocessor\Request $Coprocessor
     *     @type \CrazyGoat\Proto\Kvrpcpb\PessimisticLockRequest $PessimisticLock
     *     @type \CrazyGoat\Proto\Kvrpcpb\PessimisticRollbackRequest $PessimisticRollback
     *     @type \CrazyGoat\Proto\Kvrpcpb\CheckTxnStatusRequest $CheckTxnStatus
     *     @type \CrazyGoat\Proto\Kvrpcpb\TxnHeartBeatRequest $TxnHeartBeat
     *     @type \CrazyGoat\Proto\Kvrpcpb\CheckSecondaryLocksRequest $CheckSecondaryLocks
     *     @type \CrazyGoat\Proto\Kvrpcpb\RawCoprocessorRequest $RawCoprocessor
     *     @type \CrazyGoat\Proto\Kvrpcpb\FlashbackToVersionRequest $FlashbackToVersion
     *     @type \CrazyGoat\Proto\Kvrpcpb\PrepareFlashbackToVersionRequest $PrepareFlashbackToVersion
     *     @type \CrazyGoat\Proto\Kvrpcpb\FlushRequest $Flush
     *     @type \CrazyGoat\Proto\Kvrpcpb\BufferBatchGetRequest $BufferBatchGet
     *     @type \CrazyGoat\Proto\Kvrpcpb\GetHealthFeedbackRequest $GetHealthFeedback
     *     @type \CrazyGoat\Proto\Kvrpcpb\BroadcastTxnStatusRequest $BroadcastTxnStatus
     *     @type \CrazyGoat\Proto\Tikvpb\BatchCommandsEmptyRequest $Empty
     *           For some test cases.
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Tikvpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.GetRequest Get = 1;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\GetRequest|null
     */
    public function getGet()
    {
        return $this->readOneof(1);
    }

    public function hasGet()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.GetRequest Get = 1;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\GetRequest $var
     * @return $this
     */
    public function setGet(\CrazyGoat\Proto\Kvrpcpb\GetRequest|null $var)
    {
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.ScanRequest Scan = 2;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\ScanRequest|null
     */
    public function getScan()
    {
        return $this->readOneof(2);
    }

    public function hasScan()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.ScanRequest Scan = 2;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\ScanRequest $var
     * @return $this
     */
    public function setScan(\CrazyGoat\Proto\Kvrpcpb\ScanRequest|null $var)
    {
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.PrewriteRequest Prewrite = 3;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\PrewriteRequest|null
     */
    public function getPrewrite()
    {
        return $this->readOneof(3);
    }

    public function hasPrewrite()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.PrewriteRequest Prewrite = 3;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\PrewriteRequest $var
     * @return $this
     */
    public function setPrewrite(\CrazyGoat\Proto\Kvrpcpb\PrewriteRequest|null $var)
    {
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.CommitRequest Commit = 4;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\CommitRequest|null
     */
    public function getCommit()
    {
        return $this->readOneof(4);
    }

    public function hasCommit()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.CommitRequest Commit = 4;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\CommitRequest $var
     * @return $this
     */
    public function setCommit(\CrazyGoat\Proto\Kvrpcpb\CommitRequest|null $var)
    {
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.ImportRequest Import = 5;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\ImportRequest|null
     */
    public function getImport()
    {
        return $this->readOneof(5);
    }

    public function hasImport()
    {
        return $this->hasOneof(5);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.ImportRequest Import = 5;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\ImportRequest $var
     * @return $this
     */
    public function setImport(\CrazyGoat\Proto\Kvrpcpb\ImportRequest|null $var)
    {
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.CleanupRequest Cleanup = 6;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\CleanupRequest|null
     */
    public function getCleanup()
    {
        return $this->readOneof(6);
    }

    public function hasCleanup()
    {
        return $this->hasOneof(6);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.CleanupRequest Cleanup = 6;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\CleanupRequest $var
     * @return $this
     */
    public function setCleanup(\CrazyGoat\Proto\Kvrpcpb\CleanupRequest|null $var)
    {
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.BatchGetRequest BatchGet = 7;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\BatchGetRequest|null
     */
    public function getBatchGet()
    {
        return $this->readOneof(7);
    }

    public function hasBatchGet()
    {
        return $this->hasOneof(7);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.BatchGetRequest BatchGet = 7;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\BatchGetRequest $var
     * @return $this
     */
    public function setBatchGet(\CrazyGoat\Proto\Kvrpcpb\BatchGetRequest|null $var)
    {
        $this->writeOneof(7, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.BatchRollbackRequest BatchRollback = 8;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\BatchRollbackRequest|null
     */
    public function getBatchRollback()
    {
        return $this->readOneof(8);
    }

    public function hasBatchRollback()
    {
        return $this->hasOneof(8);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.BatchRollbackRequest BatchRollback = 8;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\BatchRollbackRequest $var
     * @return $this
     */
    public function setBatchRollback(\CrazyGoat\Proto\Kvrpcpb\BatchRollbackRequest|null $var)
    {
        $this->writeOneof(8, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.ScanLockRequest ScanLock = 9;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\ScanLockRequest|null
     */
    public function getScanLock()
    {
        return $this->readOneof(9);
    }

    public function hasScanLock()
    {
        return $this->hasOneof(9);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.ScanLockRequest ScanLock = 9;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\ScanLockRequest $var
     * @return $this
     */
    public function setScanLock(\CrazyGoat\Proto\Kvrpcpb\ScanLockRequest|null $var)
    {
        $this->writeOneof(9, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.ResolveLockRequest ResolveLock = 10;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\ResolveLockRequest|null
     */
    public function getResolveLock()
    {
        return $this->readOneof(10);
    }

    public function hasResolveLock()
    {
        return $this->hasOneof(10);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.ResolveLockRequest ResolveLock = 10;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\ResolveLockRequest $var
     * @return $this
     */
    public function setResolveLock(\CrazyGoat\Proto\Kvrpcpb\ResolveLockRequest|null $var)
    {
        $this->writeOneof(10, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.GCRequest GC = 11;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\GCRequest|null
     */
    public function getGC()
    {
        return $this->readOneof(11);
    }

    public function hasGC()
    {
        return $this->hasOneof(11);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.GCRequest GC = 11;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\GCRequest $var
     * @return $this
     */
    public function setGC(\CrazyGoat\Proto\Kvrpcpb\GCRequest|null $var)
    {
        $this->writeOneof(11, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.DeleteRangeRequest DeleteRange = 12;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\DeleteRangeRequest|null
     */
    public function getDeleteRange()
    {
        return $this->readOneof(12);
    }

    public function hasDeleteRange()
    {
        return $this->hasOneof(12);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.DeleteRangeRequest DeleteRange = 12;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\DeleteRangeRequest $var
     * @return $this
     */
    public function setDeleteRange(\CrazyGoat\Proto\Kvrpcpb\DeleteRangeRequest|null $var)
    {
        $this->writeOneof(12, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.RawGetRequest RawGet = 13;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\RawGetRequest|null
     */
    public function getRawGet()
    {
        return $this->readOneof(13);
    }

    public function hasRawGet()
    {
        return $this->hasOneof(13);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.RawGetRequest RawGet = 13;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\RawGetRequest $var
     * @return $this
     */
    public function setRawGet(\CrazyGoat\Proto\Kvrpcpb\RawGetRequest|null $var)
    {
        $this->writeOneof(13, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.RawBatchGetRequest RawBatchGet = 14;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\RawBatchGetRequest|null
     */
    public function getRawBatchGet()
    {
        return $this->readOneof(14);
    }

    public function hasRawBatchGet()
    {
        return $this->hasOneof(14);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.RawBatchGetRequest RawBatchGet = 14;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\RawBatchGetRequest $var
     * @return $this
     */
    public function setRawBatchGet(\CrazyGoat\Proto\Kvrpcpb\RawBatchGetRequest|null $var)
    {
        $this->writeOneof(14, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.RawPutRequest RawPut = 15;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\RawPutRequest|null
     */
    public function getRawPut()
    {
        return $this->readOneof(15);
    }

    public function hasRawPut()
    {
        return $this->hasOneof(15);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.RawPutRequest RawPut = 15;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\RawPutRequest $var
     * @return $this
     */
    public function setRawPut(\CrazyGoat\Proto\Kvrpcpb\RawPutRequest|null $var)
    {
        $this->writeOneof(15, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.RawBatchPutRequest RawBatchPut = 16;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\RawBatchPutRequest|null
     */
    public function getRawBatchPut()
    {
        return $this->readOneof(16);
    }

    public function hasRawBatchPut()
    {
        return $this->hasOneof(16);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.RawBatchPutRequest RawBatchPut = 16;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\RawBatchPutRequest $var
     * @return $this
     */
    public function setRawBatchPut(\CrazyGoat\Proto\Kvrpcpb\RawBatchPutRequest|null $var)
    {
        $this->writeOneof(16, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.RawDeleteRequest RawDelete = 17;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\RawDeleteRequest|null
     */
    public function getRawDelete()
    {
        return $this->readOneof(17);
    }

    public function hasRawDelete()
    {
        return $this->hasOneof(17);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.RawDeleteRequest RawDelete = 17;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\RawDeleteRequest $var
     * @return $this
     */
    public function setRawDelete(\CrazyGoat\Proto\Kvrpcpb\RawDeleteRequest|null $var)
    {
        $this->writeOneof(17, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.RawBatchDeleteRequest RawBatchDelete = 18;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\RawBatchDeleteRequest|null
     */
    public function getRawBatchDelete()
    {
        return $this->readOneof(18);
    }

    public function hasRawBatchDelete()
    {
        return $this->hasOneof(18);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.RawBatchDeleteRequest RawBatchDelete = 18;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\RawBatchDeleteRequest $var
     * @return $this
     */
    public function setRawBatchDelete(\CrazyGoat\Proto\Kvrpcpb\RawBatchDeleteRequest|null $var)
    {
        $this->writeOneof(18, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.RawScanRequest RawScan = 19;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\RawScanRequest|null
     */
    public function getRawScan()
    {
        return $this->readOneof(19);
    }

    public function hasRawScan()
    {
        return $this->hasOneof(19);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.RawScanRequest RawScan = 19;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\RawScanRequest $var
     * @return $this
     */
    public function setRawScan(\CrazyGoat\Proto\Kvrpcpb\RawScanRequest|null $var)
    {
        $this->writeOneof(19, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.RawDeleteRangeRequest RawDeleteRange = 20;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\RawDeleteRangeRequest|null
     */
    public function getRawDeleteRange()
    {
        return $this->readOneof(20);
    }

    public function hasRawDeleteRange()
    {
        return $this->hasOneof(20);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.RawDeleteRangeRequest RawDeleteRange = 20;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\RawDeleteRangeRequest $var
     * @return $this
     */
    public function setRawDeleteRange(\CrazyGoat\Proto\Kvrpcpb\RawDeleteRangeRequest|null $var)
    {
        $this->writeOneof(20, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.RawBatchScanRequest RawBatchScan = 21;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\RawBatchScanRequest|null
     */
    public function getRawBatchScan()
    {
        return $this->readOneof(21);
    }

    public function hasRawBatchScan()
    {
        return $this->hasOneof(21);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.RawBatchScanRequest RawBatchScan = 21;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\RawBatchScanRequest $var
     * @return $this
     */
    public function setRawBatchScan(\CrazyGoat\Proto\Kvrpcpb\RawBatchScanRequest|null $var)
    {
        $this->writeOneof(21, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.coprocessor.Request Coprocessor = 22;</code>
     * @return \CrazyGoat\Proto\Coprocessor\Request|null
     */
    public function getCoprocessor()
    {
        return $this->readOneof(22);
    }

    public function hasCoprocessor()
    {
        return $this->hasOneof(22);
    }

    /**
     * Generated from protobuf field <code>.coprocessor.Request Coprocessor = 22;</code>
     * @param \CrazyGoat\Proto\Coprocessor\Request $var
     * @return $this
     */
    public function setCoprocessor(\CrazyGoat\Proto\Coprocessor\Request|null $var)
    {
        $this->writeOneof(22, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.PessimisticLockRequest PessimisticLock = 23;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\PessimisticLockRequest|null
     */
    public function getPessimisticLock()
    {
        return $this->readOneof(23);
    }

    public function hasPessimisticLock()
    {
        return $this->hasOneof(23);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.PessimisticLockRequest PessimisticLock = 23;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\PessimisticLockRequest $var
     * @return $this
     */
    public function setPessimisticLock(\CrazyGoat\Proto\Kvrpcpb\PessimisticLockRequest|null $var)
    {
        $this->writeOneof(23, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.PessimisticRollbackRequest PessimisticRollback = 24;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\PessimisticRollbackRequest|null
     */
    public function getPessimisticRollback()
    {
        return $this->readOneof(24);
    }

    public function hasPessimisticRollback()
    {
        return $this->hasOneof(24);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.PessimisticRollbackRequest PessimisticRollback = 24;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\PessimisticRollbackRequest $var
     * @return $this
     */
    public function setPessimisticRollback(\CrazyGoat\Proto\Kvrpcpb\PessimisticRollbackRequest|null $var)
    {
        $this->writeOneof(24, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.CheckTxnStatusRequest CheckTxnStatus = 25;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\CheckTxnStatusRequest|null
     */
    public function getCheckTxnStatus()
    {
        return $this->readOneof(25);
    }

    public function hasCheckTxnStatus()
    {
        return $this->hasOneof(25);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.CheckTxnStatusRequest CheckTxnStatus = 25;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\CheckTxnStatusRequest $var
     * @return $this
     */
    public function setCheckTxnStatus(\CrazyGoat\Proto\Kvrpcpb\CheckTxnStatusRequest|null $var)
    {
        $this->writeOneof(25, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.TxnHeartBeatRequest TxnHeartBeat = 26;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\TxnHeartBeatRequest|null
     */
    public function getTxnHeartBeat()
    {
        return $this->readOneof(26);
    }

    public function hasTxnHeartBeat()
    {
        return $this->hasOneof(26);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.TxnHeartBeatRequest TxnHeartBeat = 26;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\TxnHeartBeatRequest $var
     * @return $this
     */
    public function setTxnHeartBeat(\CrazyGoat\Proto\Kvrpcpb\TxnHeartBeatRequest|null $var)
    {
        $this->writeOneof(26, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.CheckSecondaryLocksRequest CheckSecondaryLocks = 33;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\CheckSecondaryLocksRequest|null
     */
    public function getCheckSecondaryLocks()
    {
        return $this->readOneof(33);
    }

    public function hasCheckSecondaryLocks()
    {
        return $this->hasOneof(33);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.CheckSecondaryLocksRequest CheckSecondaryLocks = 33;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\CheckSecondaryLocksRequest $var
     * @return $this
     */
    public function setCheckSecondaryLocks(\CrazyGoat\Proto\Kvrpcpb\CheckSecondaryLocksRequest|null $var)
    {
        $this->writeOneof(33, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.RawCoprocessorRequest RawCoprocessor = 34;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\RawCoprocessorRequest|null
     */
    public function getRawCoprocessor()
    {
        return $this->readOneof(34);
    }

    public function hasRawCoprocessor()
    {
        return $this->hasOneof(34);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.RawCoprocessorRequest RawCoprocessor = 34;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\RawCoprocessorRequest $var
     * @return $this
     */
    public function setRawCoprocessor(\CrazyGoat\Proto\Kvrpcpb\RawCoprocessorRequest|null $var)
    {
        $this->writeOneof(34, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.FlashbackToVersionRequest FlashbackToVersion = 35;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\FlashbackToVersionRequest|null
     */
    public function getFlashbackToVersion()
    {
        return $this->readOneof(35);
    }

    public function hasFlashbackToVersion()
    {
        return $this->hasOneof(35);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.FlashbackToVersionRequest FlashbackToVersion = 35;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\FlashbackToVersionRequest $var
     * @return $this
     */
    public function setFlashbackToVersion(\CrazyGoat\Proto\Kvrpcpb\FlashbackToVersionRequest|null $var)
    {
        $this->writeOneof(35, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.PrepareFlashbackToVersionRequest PrepareFlashbackToVersion = 36;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\PrepareFlashbackToVersionRequest|null
     */
    public function getPrepareFlashbackToVersion()
    {
        return $this->readOneof(36);
    }

    public function hasPrepareFlashbackToVersion()
    {
        return $this->hasOneof(36);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.PrepareFlashbackToVersionRequest PrepareFlashbackToVersion = 36;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\PrepareFlashbackToVersionRequest $var
     * @return $this
     */
    public function setPrepareFlashbackToVersion(\CrazyGoat\Proto\Kvrpcpb\PrepareFlashbackToVersionRequest|null $var)
    {
        $this->writeOneof(36, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.FlushRequest Flush = 37;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\FlushRequest|null
     */
    public function getFlush()
    {
        return $this->readOneof(37);
    }

    public function hasFlush()
    {
        return $this->hasOneof(37);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.FlushRequest Flush = 37;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\FlushRequest $var
     * @return $this
     */
    public function setFlush(\CrazyGoat\Proto\Kvrpcpb\FlushRequest|null $var)
    {
        $this->writeOneof(37, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.BufferBatchGetRequest BufferBatchGet = 38;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\BufferBatchGetRequest|null
     */
    public function getBufferBatchGet()
    {
        return $this->readOneof(38);
    }

    public function hasBufferBatchGet()
    {
        return $this->hasOneof(38);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.BufferBatchGetRequest BufferBatchGet = 38;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\BufferBatchGetRequest $var
     * @return $this
     */
    public function setBufferBatchGet(\CrazyGoat\Proto\Kvrpcpb\BufferBatchGetRequest|null $var)
    {
        $this->writeOneof(38, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.GetHealthFeedbackRequest GetHealthFeedback = 39;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\GetHealthFeedbackRequest|null
     */
    public function getGetHealthFeedback()
    {
        return $this->readOneof(39);
    }

    public function hasGetHealthFeedback()
    {
        return $this->hasOneof(39);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.GetHealthFeedbackRequest GetHealthFeedback = 39;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\GetHealthFeedbackRequest $var
     * @return $this
     */
    public function setGetHealthFeedback(\CrazyGoat\Proto\Kvrpcpb\GetHealthFeedbackRequest|null $var)
    {
        $this->writeOneof(39, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.BroadcastTxnStatusRequest BroadcastTxnStatus = 40;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\BroadcastTxnStatusRequest|null
     */
    public function getBroadcastTxnStatus()
    {
        return $this->readOneof(40);
    }

    public function hasBroadcastTxnStatus()
    {
        return $this->hasOneof(40);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.BroadcastTxnStatusRequest BroadcastTxnStatus = 40;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\BroadcastTxnStatusRequest $var
     * @return $this
     */
    public function setBroadcastTxnStatus(\CrazyGoat\Proto\Kvrpcpb\BroadcastTxnStatusRequest|null $var)
    {
        $this->writeOneof(40, $var);

        return $this;
    }

    /**
     * For some test cases.
     *
     * Generated from protobuf field <code>.tikvpb.BatchCommandsEmptyRequest Empty = 255;</code>
     * @return \CrazyGoat\Proto\Tikvpb\BatchCommandsEmptyRequest|null
     */
    public function getEmpty()
    {
        return $this->readOneof(255);
    }

    public function hasEmpty()
    {
        return $this->hasOneof(255);
    }

    /**
     * For some test cases.
     *
     * Generated from protobuf field <code>.tikvpb.BatchCommandsEmptyRequest Empty = 255;</code>
     * @param \CrazyGoat\Proto\Tikvpb\BatchCommandsEmptyRequest $var
     * @return $this
     */
    public function setEmpty(\CrazyGoat\Proto\Tikvpb\BatchCommandsEmptyRequest|null $var)
    {
        $this->writeOneof(255, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getCmd()
    {
        return $this->whichOneof("cmd");
    }

}

