<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: import_sstpb.proto

namespace CrazyGoat\Proto\ImportSstpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>import_sstpb.AddPartitionRangeRequest</code>
 */
class AddPartitionRangeRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.import_sstpb.Range range = 1;</code>
     */
    protected $range = null;
    /**
     * the number of seconds this range is valid.
     *After this duration, if this range is still not removed by
     * `RemoveForcePartitionRange`, tikv will automically remove it. So the client
     * should set a big enough value to avoid auto cleanup. But in general, 1h
     * should be a big enough value. If its value is 0, tikv will auto adjust it to 3600(1h).
     *
     * Generated from protobuf field <code>uint64 ttl_seconds = 2;</code>
     */
    protected $ttl_seconds = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CrazyGoat\Proto\ImportSstpb\Range $range
     *     @type int|string $ttl_seconds
     *           the number of seconds this range is valid.
     *          After this duration, if this range is still not removed by
     *           `RemoveForcePartitionRange`, tikv will automically remove it. So the client
     *           should set a big enough value to avoid auto cleanup. But in general, 1h
     *           should be a big enough value. If its value is 0, tikv will auto adjust it to 3600(1h).
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\ImportSstpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.import_sstpb.Range range = 1;</code>
     * @return \CrazyGoat\Proto\ImportSstpb\Range|null
     */
    public function getRange()
    {
        return $this->range;
    }

    public function hasRange()
    {
        return isset($this->range);
    }

    public function clearRange()
    {
        unset($this->range);
    }

    /**
     * Generated from protobuf field <code>.import_sstpb.Range range = 1;</code>
     * @param \CrazyGoat\Proto\ImportSstpb\Range $var
     * @return $this
     */
    public function setRange(\CrazyGoat\Proto\ImportSstpb\Range|null $var)
    {
        $this->range = $var;

        return $this;
    }

    /**
     * the number of seconds this range is valid.
     *After this duration, if this range is still not removed by
     * `RemoveForcePartitionRange`, tikv will automically remove it. So the client
     * should set a big enough value to avoid auto cleanup. But in general, 1h
     * should be a big enough value. If its value is 0, tikv will auto adjust it to 3600(1h).
     *
     * Generated from protobuf field <code>uint64 ttl_seconds = 2;</code>
     * @return int|string
     */
    public function getTtlSeconds()
    {
        return $this->ttl_seconds;
    }

    /**
     * the number of seconds this range is valid.
     *After this duration, if this range is still not removed by
     * `RemoveForcePartitionRange`, tikv will automically remove it. So the client
     * should set a big enough value to avoid auto cleanup. But in general, 1h
     * should be a big enough value. If its value is 0, tikv will auto adjust it to 3600(1h).
     *
     * Generated from protobuf field <code>uint64 ttl_seconds = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTtlSeconds(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->ttl_seconds = $var;

        return $this;
    }

}

