<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: import_sstpb.proto

namespace CrazyGoat\Proto\ImportSstpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>import_sstpb.ApplyResponse</code>
 */
class ApplyResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The actual key range (after rewrite) of the downloaded file. The range is
     * inclusive in both ends.
     *
     * Generated from protobuf field <code>.import_sstpb.Range range = 1;</code>
     */
    protected $range = null;
    /**
     * Generated from protobuf field <code>.import_sstpb.Error error = 2;</code>
     */
    protected $error = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CrazyGoat\Proto\ImportSstpb\Range $range
     *           The actual key range (after rewrite) of the downloaded file. The range is
     *           inclusive in both ends.
     *     @type \CrazyGoat\Proto\ImportSstpb\Error $error
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\ImportSstpb::initOnce();
        parent::__construct($data);
    }

    /**
     * The actual key range (after rewrite) of the downloaded file. The range is
     * inclusive in both ends.
     *
     * Generated from protobuf field <code>.import_sstpb.Range range = 1;</code>
     * @return \CrazyGoat\Proto\ImportSstpb\Range|null
     */
    public function getRange()
    {
        return $this->range;
    }

    public function hasRange()
    {
        return isset($this->range);
    }

    public function clearRange()
    {
        unset($this->range);
    }

    /**
     * The actual key range (after rewrite) of the downloaded file. The range is
     * inclusive in both ends.
     *
     * Generated from protobuf field <code>.import_sstpb.Range range = 1;</code>
     * @param \CrazyGoat\Proto\ImportSstpb\Range $var
     * @return $this
     */
    public function setRange(\CrazyGoat\Proto\ImportSstpb\Range|null $var)
    {
        $this->range = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.import_sstpb.Error error = 2;</code>
     * @return \CrazyGoat\Proto\ImportSstpb\Error|null
     */
    public function getError()
    {
        return $this->error;
    }

    public function hasError()
    {
        return isset($this->error);
    }

    public function clearError()
    {
        unset($this->error);
    }

    /**
     * Generated from protobuf field <code>.import_sstpb.Error error = 2;</code>
     * @param \CrazyGoat\Proto\ImportSstpb\Error $var
     * @return $this
     */
    public function setError(\CrazyGoat\Proto\ImportSstpb\Error|null $var)
    {
        $this->error = $var;

        return $this;
    }

}

