<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: import_sstpb.proto

namespace CrazyGoat\Proto\ImportSstpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>import_sstpb.DownloadResponse</code>
 */
class DownloadResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The actual key range (after rewrite) of the downloaded SST. The range is
     * inclusive in both ends.
     *
     * Generated from protobuf field <code>.import_sstpb.Range range = 1;</code>
     */
    protected $range = null;
    /**
     * Whether the SST is empty. An empty SST is prohibited in TiKV, do not
     * ingest if this field is true.
     * (Deprecated, should be replaced by checking `length == 0` in the future)
     *
     * Generated from protobuf field <code>bool is_empty = 2;</code>
     */
    protected $is_empty = false;
    /**
     * Generated from protobuf field <code>.import_sstpb.Error error = 3;</code>
     */
    protected $error = null;
    /**
     * The CRC32 checksum of the rewritten SST file (implementation can return
     * zero, indicating the CRC32 was not calculated).
     *
     * Generated from protobuf field <code>uint32 crc32 = 4;</code>
     */
    protected $crc32 = 0;
    /**
     * The actual length of the rewritten SST file.
     *
     * Generated from protobuf field <code>uint64 length = 5;</code>
     */
    protected $length = 0;
    /**
     * This field only return when file-copy backup enabled.
     * Because it will merge many SST files in a download request.
     *
     * Generated from protobuf field <code>repeated .import_sstpb.SSTMeta ssts = 6;</code>
     */
    private $ssts;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CrazyGoat\Proto\ImportSstpb\Range $range
     *           The actual key range (after rewrite) of the downloaded SST. The range is
     *           inclusive in both ends.
     *     @type bool $is_empty
     *           Whether the SST is empty. An empty SST is prohibited in TiKV, do not
     *           ingest if this field is true.
     *           (Deprecated, should be replaced by checking `length == 0` in the future)
     *     @type \CrazyGoat\Proto\ImportSstpb\Error $error
     *     @type int $crc32
     *           The CRC32 checksum of the rewritten SST file (implementation can return
     *           zero, indicating the CRC32 was not calculated).
     *     @type int|string $length
     *           The actual length of the rewritten SST file.
     *     @type \CrazyGoat\Proto\ImportSstpb\SSTMeta[] $ssts
     *           This field only return when file-copy backup enabled.
     *           Because it will merge many SST files in a download request.
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\ImportSstpb::initOnce();
        parent::__construct($data);
    }

    /**
     * The actual key range (after rewrite) of the downloaded SST. The range is
     * inclusive in both ends.
     *
     * Generated from protobuf field <code>.import_sstpb.Range range = 1;</code>
     * @return \CrazyGoat\Proto\ImportSstpb\Range|null
     */
    public function getRange()
    {
        return $this->range;
    }

    public function hasRange()
    {
        return isset($this->range);
    }

    public function clearRange()
    {
        unset($this->range);
    }

    /**
     * The actual key range (after rewrite) of the downloaded SST. The range is
     * inclusive in both ends.
     *
     * Generated from protobuf field <code>.import_sstpb.Range range = 1;</code>
     * @param \CrazyGoat\Proto\ImportSstpb\Range $var
     * @return $this
     */
    public function setRange(\CrazyGoat\Proto\ImportSstpb\Range|null $var)
    {
        $this->range = $var;

        return $this;
    }

    /**
     * Whether the SST is empty. An empty SST is prohibited in TiKV, do not
     * ingest if this field is true.
     * (Deprecated, should be replaced by checking `length == 0` in the future)
     *
     * Generated from protobuf field <code>bool is_empty = 2;</code>
     * @return bool
     */
    public function getIsEmpty()
    {
        return $this->is_empty;
    }

    /**
     * Whether the SST is empty. An empty SST is prohibited in TiKV, do not
     * ingest if this field is true.
     * (Deprecated, should be replaced by checking `length == 0` in the future)
     *
     * Generated from protobuf field <code>bool is_empty = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsEmpty(bool $var)
    {
        $this->is_empty = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.import_sstpb.Error error = 3;</code>
     * @return \CrazyGoat\Proto\ImportSstpb\Error|null
     */
    public function getError()
    {
        return $this->error;
    }

    public function hasError()
    {
        return isset($this->error);
    }

    public function clearError()
    {
        unset($this->error);
    }

    /**
     * Generated from protobuf field <code>.import_sstpb.Error error = 3;</code>
     * @param \CrazyGoat\Proto\ImportSstpb\Error $var
     * @return $this
     */
    public function setError(\CrazyGoat\Proto\ImportSstpb\Error|null $var)
    {
        $this->error = $var;

        return $this;
    }

    /**
     * The CRC32 checksum of the rewritten SST file (implementation can return
     * zero, indicating the CRC32 was not calculated).
     *
     * Generated from protobuf field <code>uint32 crc32 = 4;</code>
     * @return int
     */
    public function getCrc32()
    {
        return $this->crc32;
    }

    /**
     * The CRC32 checksum of the rewritten SST file (implementation can return
     * zero, indicating the CRC32 was not calculated).
     *
     * Generated from protobuf field <code>uint32 crc32 = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setCrc32(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->crc32 = $var;

        return $this;
    }

    /**
     * The actual length of the rewritten SST file.
     *
     * Generated from protobuf field <code>uint64 length = 5;</code>
     * @return int|string
     */
    public function getLength()
    {
        return $this->length;
    }

    /**
     * The actual length of the rewritten SST file.
     *
     * Generated from protobuf field <code>uint64 length = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLength(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->length = $var;

        return $this;
    }

    /**
     * This field only return when file-copy backup enabled.
     * Because it will merge many SST files in a download request.
     *
     * Generated from protobuf field <code>repeated .import_sstpb.SSTMeta ssts = 6;</code>
     * @return RepeatedField<\CrazyGoat\Proto\ImportSstpb\SSTMeta>
     */
    public function getSsts()
    {
        return $this->ssts;
    }

    /**
     * This field only return when file-copy backup enabled.
     * Because it will merge many SST files in a download request.
     *
     * Generated from protobuf field <code>repeated .import_sstpb.SSTMeta ssts = 6;</code>
     * @param \CrazyGoat\Proto\ImportSstpb\SSTMeta[] $var
     * @return $this
     */
    public function setSsts(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \CrazyGoat\Proto\ImportSstpb\SSTMeta::class);
        $this->ssts = $arr;

        return $this;
    }

}

