<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: import_sstpb.proto

namespace CrazyGoat\Proto\ImportSstpb;

use UnexpectedValueException;

/**
 * Protobuf type <code>import_sstpb.DownloadRequestType</code>
 */
class DownloadRequestType
{
    /**
     * For the compatibility with old version of TiDBs
     *
     * Generated from protobuf enum <code>Legacy = 0;</code>
     */
    const Legacy = 0;
    /**
     * For the TiDBs with newer versions that support keyspace feature.
     *
     * Generated from protobuf enum <code>Keyspace = 1;</code>
     */
    const Keyspace = 1;

    private static $valueToName = [
        self::Legacy => 'Legacy',
        self::Keyspace => 'Keyspace',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

