<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: import_sstpb.proto

namespace CrazyGoat\Proto\ImportSstpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>import_sstpb.DuplicateDetectResponse</code>
 */
class DuplicateDetectResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.errorpb.Error region_error = 1;</code>
     */
    protected $region_error = null;
    /**
     * Generated from protobuf field <code>.import_sstpb.Error key_error = 2;</code>
     */
    protected $key_error = null;
    /**
     * The these keys will be in asc order (but commit time is in desc order),
     *  and the content is just like following:
     * [
     *   {key: "key1", value: "value11", commit_ts: 1005},
     *   {key: "key1", value: "value12", commit_ts: 1004},
     *   {key: "key1", value: "value13", commit_ts: 1001},
     *   {key: "key2", value: "value21", commit_ts: 1004},
     *   {key: "key2", value: "value22", commit_ts: 1002},
     *   ...
     * ]
     *
     * Generated from protobuf field <code>repeated .import_sstpb.KvPair pairs = 3;</code>
     */
    private $pairs;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CrazyGoat\Proto\Errorpb\Error $region_error
     *     @type \CrazyGoat\Proto\ImportSstpb\Error $key_error
     *     @type \CrazyGoat\Proto\ImportSstpb\KvPair[] $pairs
     *           The these keys will be in asc order (but commit time is in desc order),
     *            and the content is just like following:
     *           [
     *             {key: "key1", value: "value11", commit_ts: 1005},
     *             {key: "key1", value: "value12", commit_ts: 1004},
     *             {key: "key1", value: "value13", commit_ts: 1001},
     *             {key: "key2", value: "value21", commit_ts: 1004},
     *             {key: "key2", value: "value22", commit_ts: 1002},
     *             ...
     *           ]
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\ImportSstpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.errorpb.Error region_error = 1;</code>
     * @return \CrazyGoat\Proto\Errorpb\Error|null
     */
    public function getRegionError()
    {
        return $this->region_error;
    }

    public function hasRegionError()
    {
        return isset($this->region_error);
    }

    public function clearRegionError()
    {
        unset($this->region_error);
    }

    /**
     * Generated from protobuf field <code>.errorpb.Error region_error = 1;</code>
     * @param \CrazyGoat\Proto\Errorpb\Error $var
     * @return $this
     */
    public function setRegionError(\CrazyGoat\Proto\Errorpb\Error|null $var)
    {
        $this->region_error = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.import_sstpb.Error key_error = 2;</code>
     * @return \CrazyGoat\Proto\ImportSstpb\Error|null
     */
    public function getKeyError()
    {
        return $this->key_error;
    }

    public function hasKeyError()
    {
        return isset($this->key_error);
    }

    public function clearKeyError()
    {
        unset($this->key_error);
    }

    /**
     * Generated from protobuf field <code>.import_sstpb.Error key_error = 2;</code>
     * @param \CrazyGoat\Proto\ImportSstpb\Error $var
     * @return $this
     */
    public function setKeyError(\CrazyGoat\Proto\ImportSstpb\Error|null $var)
    {
        $this->key_error = $var;

        return $this;
    }

    /**
     * The these keys will be in asc order (but commit time is in desc order),
     *  and the content is just like following:
     * [
     *   {key: "key1", value: "value11", commit_ts: 1005},
     *   {key: "key1", value: "value12", commit_ts: 1004},
     *   {key: "key1", value: "value13", commit_ts: 1001},
     *   {key: "key2", value: "value21", commit_ts: 1004},
     *   {key: "key2", value: "value22", commit_ts: 1002},
     *   ...
     * ]
     *
     * Generated from protobuf field <code>repeated .import_sstpb.KvPair pairs = 3;</code>
     * @return RepeatedField<\CrazyGoat\Proto\ImportSstpb\KvPair>
     */
    public function getPairs()
    {
        return $this->pairs;
    }

    /**
     * The these keys will be in asc order (but commit time is in desc order),
     *  and the content is just like following:
     * [
     *   {key: "key1", value: "value11", commit_ts: 1005},
     *   {key: "key1", value: "value12", commit_ts: 1004},
     *   {key: "key1", value: "value13", commit_ts: 1001},
     *   {key: "key2", value: "value21", commit_ts: 1004},
     *   {key: "key2", value: "value22", commit_ts: 1002},
     *   ...
     * ]
     *
     * Generated from protobuf field <code>repeated .import_sstpb.KvPair pairs = 3;</code>
     * @param \CrazyGoat\Proto\ImportSstpb\KvPair[] $var
     * @return $this
     */
    public function setPairs(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \CrazyGoat\Proto\ImportSstpb\KvPair::class);
        $this->pairs = $arr;

        return $this;
    }

}

