<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: import_sstpb.proto

namespace CrazyGoat\Proto\ImportSstpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>import_sstpb.DuplicateDetectRequest</code>
 */
class DuplicateDetectRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.kvrpcpb.Context context = 1;</code>
     */
    protected $context = null;
    /**
     * Generated from protobuf field <code>bytes start_key = 2;</code>
     */
    protected $start_key = '';
    /**
     * Generated from protobuf field <code>bytes end_key = 3;</code>
     */
    protected $end_key = '';
    /**
     * Return only the keys found by scanning, not their values.
     *
     * Generated from protobuf field <code>bool key_only = 4;</code>
     */
    protected $key_only = false;
    /**
     * We only check the data whose timestamp is larger than `min_commit_ts`. `min_commit_ts` is exclueded.
     *
     * Generated from protobuf field <code>uint64 min_commit_ts = 5;</code>
     */
    protected $min_commit_ts = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CrazyGoat\Proto\Kvrpcpb\Context $context
     *     @type string $start_key
     *     @type string $end_key
     *     @type bool $key_only
     *           Return only the keys found by scanning, not their values.
     *     @type int|string $min_commit_ts
     *           We only check the data whose timestamp is larger than `min_commit_ts`. `min_commit_ts` is exclueded.
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\ImportSstpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.Context context = 1;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\Context|null
     */
    public function getContext()
    {
        return $this->context;
    }

    public function hasContext()
    {
        return isset($this->context);
    }

    public function clearContext()
    {
        unset($this->context);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.Context context = 1;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\Context $var
     * @return $this
     */
    public function setContext(\CrazyGoat\Proto\Kvrpcpb\Context|null $var)
    {
        $this->context = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes start_key = 2;</code>
     * @return string
     */
    public function getStartKey()
    {
        return $this->start_key;
    }

    /**
     * Generated from protobuf field <code>bytes start_key = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setStartKey(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->start_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes end_key = 3;</code>
     * @return string
     */
    public function getEndKey()
    {
        return $this->end_key;
    }

    /**
     * Generated from protobuf field <code>bytes end_key = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setEndKey(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->end_key = $var;

        return $this;
    }

    /**
     * Return only the keys found by scanning, not their values.
     *
     * Generated from protobuf field <code>bool key_only = 4;</code>
     * @return bool
     */
    public function getKeyOnly()
    {
        return $this->key_only;
    }

    /**
     * Return only the keys found by scanning, not their values.
     *
     * Generated from protobuf field <code>bool key_only = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setKeyOnly(bool $var)
    {
        $this->key_only = $var;

        return $this;
    }

    /**
     * We only check the data whose timestamp is larger than `min_commit_ts`. `min_commit_ts` is exclueded.
     *
     * Generated from protobuf field <code>uint64 min_commit_ts = 5;</code>
     * @return int|string
     */
    public function getMinCommitTs()
    {
        return $this->min_commit_ts;
    }

    /**
     * We only check the data whose timestamp is larger than `min_commit_ts`. `min_commit_ts` is exclueded.
     *
     * Generated from protobuf field <code>uint64 min_commit_ts = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMinCommitTs(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->min_commit_ts = $var;

        return $this;
    }

}

