<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: import_sstpb.proto

namespace CrazyGoat\Proto\ImportSstpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * For now it is just used for distinguishing the error of the request with the error
 * of gRPC, add more concrete types if it is necessary later.
 *
 * Generated from protobuf message <code>import_sstpb.Error</code>
 */
class Error extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string message = 1;</code>
     */
    protected $message = '';
    /**
     * We meet some internal errors of the store.
     *
     * Generated from protobuf field <code>.errorpb.Error store_error = 2;</code>
     */
    protected $store_error = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $message
     *     @type \CrazyGoat\Proto\Errorpb\Error $store_error
     *           We meet some internal errors of the store.
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\ImportSstpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string message = 1;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Generated from protobuf field <code>string message = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->message = $var;

        return $this;
    }

    /**
     * We meet some internal errors of the store.
     *
     * Generated from protobuf field <code>.errorpb.Error store_error = 2;</code>
     * @return \CrazyGoat\Proto\Errorpb\Error|null
     */
    public function getStoreError()
    {
        return $this->store_error;
    }

    public function hasStoreError()
    {
        return isset($this->store_error);
    }

    public function clearStoreError()
    {
        unset($this->store_error);
    }

    /**
     * We meet some internal errors of the store.
     *
     * Generated from protobuf field <code>.errorpb.Error store_error = 2;</code>
     * @param \CrazyGoat\Proto\Errorpb\Error $var
     * @return $this
     */
    public function setStoreError(\CrazyGoat\Proto\Errorpb\Error|null $var)
    {
        $this->store_error = $var;

        return $this;
    }

}

