<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: import_sstpb.proto

namespace CrazyGoat\Proto\ImportSstpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>import_sstpb.IngestResponse</code>
 */
class IngestResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.errorpb.Error error = 1;</code>
     */
    protected $error = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CrazyGoat\Proto\Errorpb\Error $error
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\ImportSstpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.errorpb.Error error = 1;</code>
     * @return \CrazyGoat\Proto\Errorpb\Error|null
     */
    public function getError()
    {
        return $this->error;
    }

    public function hasError()
    {
        return isset($this->error);
    }

    public function clearError()
    {
        unset($this->error);
    }

    /**
     * Generated from protobuf field <code>.errorpb.Error error = 1;</code>
     * @param \CrazyGoat\Proto\Errorpb\Error $var
     * @return $this
     */
    public function setError(\CrazyGoat\Proto\Errorpb\Error|null $var)
    {
        $this->error = $var;

        return $this;
    }

}

