<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: import_sstpb.proto

namespace CrazyGoat\Proto\ImportSstpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>import_sstpb.KVMeta</code>
 */
class KVMeta extends \Google\Protobuf\Internal\Message
{
    /**
     * The file name of the KV file.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * file offset, sometimes only need to get a part of data from the merged file
     *
     * Generated from protobuf field <code>uint64 range_offset = 11;</code>
     */
    protected $range_offset = 0;
    /**
     * file length for check.
     *
     * Generated from protobuf field <code>uint64 length = 2;</code>
     */
    protected $length = 0;
    /**
     * range length of the merged file, if it exists.
     *
     * Generated from protobuf field <code>uint64 range_length = 12;</code>
     */
    protected $range_length = 0;
    /**
     * tell us which cf should apply. WRITE_CF or DEFAULT_CF e.g.
     *
     * Generated from protobuf field <code>string cf = 3;</code>
     */
    protected $cf = '';
    /**
     * is_delete represents whether we should delete the kv in tikv.
     * it may not be too much delete file. only rollBack operation will generate delete kv file.
     *
     * Generated from protobuf field <code>bool is_delete = 4;</code>
     */
    protected $is_delete = false;
    /**
     * the key ts space being smaller than start_ts can be filter.
     *
     * Generated from protobuf field <code>uint64 start_ts = 10;</code>
     */
    protected $start_ts = 0;
    /**
     * the key ts space large than restore_ts can be filter.
     *
     * Generated from protobuf field <code>uint64 restore_ts = 5;</code>
     */
    protected $restore_ts = 0;
    /**
     * Generated from protobuf field <code>bytes start_key = 6;</code>
     */
    protected $start_key = '';
    /**
     * Generated from protobuf field <code>bytes end_key = 7;</code>
     */
    protected $end_key = '';
    /**
     * used for checksum when download kv file.
     *
     * Generated from protobuf field <code>bytes sha256 = 8;</code>
     */
    protected $sha256 = '';
    /**
     * the key ts space less than start_snapshot_ts can be filter.
     * Deprecated: this field 'start_snapshot_ts' is replaced by the field 'start_ts'.
     *
     * Generated from protobuf field <code>uint64 start_snapshot_ts = 9;</code>
     */
    protected $start_snapshot_ts = 0;
    /**
     * the compression type for the file.
     *
     * Generated from protobuf field <code>.backup.CompressionType compression_type = 13;</code>
     */
    protected $compression_type = 0;
    /**
     * encryption information of the kv file, not set if encryption is not enabled.
     *
     * Generated from protobuf field <code>.encryptionpb.FileEncryptionInfo file_encryption_info = 14;</code>
     */
    protected $file_encryption_info = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           The file name of the KV file.
     *     @type int|string $range_offset
     *           file offset, sometimes only need to get a part of data from the merged file
     *     @type int|string $length
     *           file length for check.
     *     @type int|string $range_length
     *           range length of the merged file, if it exists.
     *     @type string $cf
     *           tell us which cf should apply. WRITE_CF or DEFAULT_CF e.g.
     *     @type bool $is_delete
     *           is_delete represents whether we should delete the kv in tikv.
     *           it may not be too much delete file. only rollBack operation will generate delete kv file.
     *     @type int|string $start_ts
     *           the key ts space being smaller than start_ts can be filter.
     *     @type int|string $restore_ts
     *           the key ts space large than restore_ts can be filter.
     *     @type string $start_key
     *     @type string $end_key
     *     @type string $sha256
     *           used for checksum when download kv file.
     *     @type int|string $start_snapshot_ts
     *           the key ts space less than start_snapshot_ts can be filter.
     *           Deprecated: this field 'start_snapshot_ts' is replaced by the field 'start_ts'.
     *     @type int $compression_type
     *           the compression type for the file.
     *     @type \CrazyGoat\Proto\Encryptionpb\FileEncryptionInfo $file_encryption_info
     *           encryption information of the kv file, not set if encryption is not enabled.
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\ImportSstpb::initOnce();
        parent::__construct($data);
    }

    /**
     * The file name of the KV file.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * The file name of the KV file.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * file offset, sometimes only need to get a part of data from the merged file
     *
     * Generated from protobuf field <code>uint64 range_offset = 11;</code>
     * @return int|string
     */
    public function getRangeOffset()
    {
        return $this->range_offset;
    }

    /**
     * file offset, sometimes only need to get a part of data from the merged file
     *
     * Generated from protobuf field <code>uint64 range_offset = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRangeOffset(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->range_offset = $var;

        return $this;
    }

    /**
     * file length for check.
     *
     * Generated from protobuf field <code>uint64 length = 2;</code>
     * @return int|string
     */
    public function getLength()
    {
        return $this->length;
    }

    /**
     * file length for check.
     *
     * Generated from protobuf field <code>uint64 length = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLength(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->length = $var;

        return $this;
    }

    /**
     * range length of the merged file, if it exists.
     *
     * Generated from protobuf field <code>uint64 range_length = 12;</code>
     * @return int|string
     */
    public function getRangeLength()
    {
        return $this->range_length;
    }

    /**
     * range length of the merged file, if it exists.
     *
     * Generated from protobuf field <code>uint64 range_length = 12;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRangeLength(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->range_length = $var;

        return $this;
    }

    /**
     * tell us which cf should apply. WRITE_CF or DEFAULT_CF e.g.
     *
     * Generated from protobuf field <code>string cf = 3;</code>
     * @return string
     */
    public function getCf()
    {
        return $this->cf;
    }

    /**
     * tell us which cf should apply. WRITE_CF or DEFAULT_CF e.g.
     *
     * Generated from protobuf field <code>string cf = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCf(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->cf = $var;

        return $this;
    }

    /**
     * is_delete represents whether we should delete the kv in tikv.
     * it may not be too much delete file. only rollBack operation will generate delete kv file.
     *
     * Generated from protobuf field <code>bool is_delete = 4;</code>
     * @return bool
     */
    public function getIsDelete()
    {
        return $this->is_delete;
    }

    /**
     * is_delete represents whether we should delete the kv in tikv.
     * it may not be too much delete file. only rollBack operation will generate delete kv file.
     *
     * Generated from protobuf field <code>bool is_delete = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsDelete(bool $var)
    {
        $this->is_delete = $var;

        return $this;
    }

    /**
     * the key ts space being smaller than start_ts can be filter.
     *
     * Generated from protobuf field <code>uint64 start_ts = 10;</code>
     * @return int|string
     */
    public function getStartTs()
    {
        return $this->start_ts;
    }

    /**
     * the key ts space being smaller than start_ts can be filter.
     *
     * Generated from protobuf field <code>uint64 start_ts = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStartTs(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->start_ts = $var;

        return $this;
    }

    /**
     * the key ts space large than restore_ts can be filter.
     *
     * Generated from protobuf field <code>uint64 restore_ts = 5;</code>
     * @return int|string
     */
    public function getRestoreTs()
    {
        return $this->restore_ts;
    }

    /**
     * the key ts space large than restore_ts can be filter.
     *
     * Generated from protobuf field <code>uint64 restore_ts = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRestoreTs(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->restore_ts = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes start_key = 6;</code>
     * @return string
     */
    public function getStartKey()
    {
        return $this->start_key;
    }

    /**
     * Generated from protobuf field <code>bytes start_key = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setStartKey(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->start_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes end_key = 7;</code>
     * @return string
     */
    public function getEndKey()
    {
        return $this->end_key;
    }

    /**
     * Generated from protobuf field <code>bytes end_key = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setEndKey(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->end_key = $var;

        return $this;
    }

    /**
     * used for checksum when download kv file.
     *
     * Generated from protobuf field <code>bytes sha256 = 8;</code>
     * @return string
     */
    public function getSha256()
    {
        return $this->sha256;
    }

    /**
     * used for checksum when download kv file.
     *
     * Generated from protobuf field <code>bytes sha256 = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setSha256(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->sha256 = $var;

        return $this;
    }

    /**
     * the key ts space less than start_snapshot_ts can be filter.
     * Deprecated: this field 'start_snapshot_ts' is replaced by the field 'start_ts'.
     *
     * Generated from protobuf field <code>uint64 start_snapshot_ts = 9;</code>
     * @return int|string
     */
    public function getStartSnapshotTs()
    {
        return $this->start_snapshot_ts;
    }

    /**
     * the key ts space less than start_snapshot_ts can be filter.
     * Deprecated: this field 'start_snapshot_ts' is replaced by the field 'start_ts'.
     *
     * Generated from protobuf field <code>uint64 start_snapshot_ts = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStartSnapshotTs(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->start_snapshot_ts = $var;

        return $this;
    }

    /**
     * the compression type for the file.
     *
     * Generated from protobuf field <code>.backup.CompressionType compression_type = 13;</code>
     * @return int one of the values in {@see \CrazyGoat\Proto\Backup\CompressionType}
     */
    public function getCompressionType()
    {
        return $this->compression_type;
    }

    /**
     * the compression type for the file.
     *
     * Generated from protobuf field <code>.backup.CompressionType compression_type = 13;</code>
     * @param int $var one of the values in {@see \CrazyGoat\Proto\Backup\CompressionType}
     * @return $this
     */
    public function setCompressionType(int $var)
    {
        GPBUtil::checkEnum($var, \CrazyGoat\Proto\Backup\CompressionType::class);
        $this->compression_type = $var;

        return $this;
    }

    /**
     * encryption information of the kv file, not set if encryption is not enabled.
     *
     * Generated from protobuf field <code>.encryptionpb.FileEncryptionInfo file_encryption_info = 14;</code>
     * @return \CrazyGoat\Proto\Encryptionpb\FileEncryptionInfo|null
     */
    public function getFileEncryptionInfo()
    {
        return $this->file_encryption_info;
    }

    public function hasFileEncryptionInfo()
    {
        return isset($this->file_encryption_info);
    }

    public function clearFileEncryptionInfo()
    {
        unset($this->file_encryption_info);
    }

    /**
     * encryption information of the kv file, not set if encryption is not enabled.
     *
     * Generated from protobuf field <code>.encryptionpb.FileEncryptionInfo file_encryption_info = 14;</code>
     * @param \CrazyGoat\Proto\Encryptionpb\FileEncryptionInfo $var
     * @return $this
     */
    public function setFileEncryptionInfo(\CrazyGoat\Proto\Encryptionpb\FileEncryptionInfo|null $var)
    {
        $this->file_encryption_info = $var;

        return $this;
    }

}

