<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: import_sstpb.proto

namespace CrazyGoat\Proto\ImportSstpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>import_sstpb.MultiIngestRequest</code>
 */
class MultiIngestRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.kvrpcpb.Context context = 1;</code>
     */
    protected $context = null;
    /**
     * Generated from protobuf field <code>repeated .import_sstpb.SSTMeta ssts = 2;</code>
     */
    private $ssts;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CrazyGoat\Proto\Kvrpcpb\Context $context
     *     @type \CrazyGoat\Proto\ImportSstpb\SSTMeta[] $ssts
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\ImportSstpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.Context context = 1;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\Context|null
     */
    public function getContext()
    {
        return $this->context;
    }

    public function hasContext()
    {
        return isset($this->context);
    }

    public function clearContext()
    {
        unset($this->context);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.Context context = 1;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\Context $var
     * @return $this
     */
    public function setContext(\CrazyGoat\Proto\Kvrpcpb\Context|null $var)
    {
        $this->context = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .import_sstpb.SSTMeta ssts = 2;</code>
     * @return RepeatedField<\CrazyGoat\Proto\ImportSstpb\SSTMeta>
     */
    public function getSsts()
    {
        return $this->ssts;
    }

    /**
     * Generated from protobuf field <code>repeated .import_sstpb.SSTMeta ssts = 2;</code>
     * @param \CrazyGoat\Proto\ImportSstpb\SSTMeta[] $var
     * @return $this
     */
    public function setSsts(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \CrazyGoat\Proto\ImportSstpb\SSTMeta::class);
        $this->ssts = $arr;

        return $this;
    }

}

