<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: import_sstpb.proto

namespace CrazyGoat\Proto\ImportSstpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>import_sstpb.RawWriteBatch</code>
 */
class RawWriteBatch extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 ttl = 1;</code>
     */
    protected $ttl = 0;
    /**
     * Generated from protobuf field <code>repeated .import_sstpb.Pair pairs = 2;</code>
     */
    private $pairs;
    /**
     * To be compatible with the key encoding of API V2.
     * This field should be generated from the client instead of the server,
     * since the message will be send to all the replicas of a region.
     * Otherwise, the underlying data generated by the server would be inconsistent which is hard to scale
     * for other features like MVCC over RawKV.
     *
     * Generated from protobuf field <code>uint64 ts = 3;</code>
     */
    protected $ts = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $ttl
     *     @type \CrazyGoat\Proto\ImportSstpb\Pair[] $pairs
     *     @type int|string $ts
     *           To be compatible with the key encoding of API V2.
     *           This field should be generated from the client instead of the server,
     *           since the message will be send to all the replicas of a region.
     *           Otherwise, the underlying data generated by the server would be inconsistent which is hard to scale
     *           for other features like MVCC over RawKV.
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\ImportSstpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 ttl = 1;</code>
     * @return int|string
     */
    public function getTtl()
    {
        return $this->ttl;
    }

    /**
     * Generated from protobuf field <code>uint64 ttl = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTtl(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->ttl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .import_sstpb.Pair pairs = 2;</code>
     * @return RepeatedField<\CrazyGoat\Proto\ImportSstpb\Pair>
     */
    public function getPairs()
    {
        return $this->pairs;
    }

    /**
     * Generated from protobuf field <code>repeated .import_sstpb.Pair pairs = 2;</code>
     * @param \CrazyGoat\Proto\ImportSstpb\Pair[] $var
     * @return $this
     */
    public function setPairs(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \CrazyGoat\Proto\ImportSstpb\Pair::class);
        $this->pairs = $arr;

        return $this;
    }

    /**
     * To be compatible with the key encoding of API V2.
     * This field should be generated from the client instead of the server,
     * since the message will be send to all the replicas of a region.
     * Otherwise, the underlying data generated by the server would be inconsistent which is hard to scale
     * for other features like MVCC over RawKV.
     *
     * Generated from protobuf field <code>uint64 ts = 3;</code>
     * @return int|string
     */
    public function getTs()
    {
        return $this->ts;
    }

    /**
     * To be compatible with the key encoding of API V2.
     * This field should be generated from the client instead of the server,
     * since the message will be send to all the replicas of a region.
     * Otherwise, the underlying data generated by the server would be inconsistent which is hard to scale
     * for other features like MVCC over RawKV.
     *
     * Generated from protobuf field <code>uint64 ts = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTs(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->ts = $var;

        return $this;
    }

}

