<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: import_sstpb.proto

namespace CrazyGoat\Proto\ImportSstpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * A rewrite rule is applied on the *encoded* keys (the internal storage
 * representation).
 *
 * Generated from protobuf message <code>import_sstpb.RewriteRule</code>
 */
class RewriteRule extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes old_key_prefix = 1;</code>
     */
    protected $old_key_prefix = '';
    /**
     * Generated from protobuf field <code>bytes new_key_prefix = 2;</code>
     */
    protected $new_key_prefix = '';
    /**
     * (Optional) Rewrite all keys in the range to use this timestamp.
     *
     * Generated from protobuf field <code>uint64 new_timestamp = 3;</code>
     */
    protected $new_timestamp = 0;
    /**
     * (Optional) Skip keys with timestamps greater than this during download, useful for compacted SST backups.
     *
     * Generated from protobuf field <code>uint64 ignore_after_timestamp = 4;</code>
     */
    protected $ignore_after_timestamp = 0;
    /**
     * (Optional) Skip write CF keys with timestamps less than this during download. Default CF keys are preserved.
     *
     * Generated from protobuf field <code>uint64 ignore_before_timestamp = 5;</code>
     */
    protected $ignore_before_timestamp = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $old_key_prefix
     *     @type string $new_key_prefix
     *     @type int|string $new_timestamp
     *           (Optional) Rewrite all keys in the range to use this timestamp.
     *     @type int|string $ignore_after_timestamp
     *           (Optional) Skip keys with timestamps greater than this during download, useful for compacted SST backups.
     *     @type int|string $ignore_before_timestamp
     *           (Optional) Skip write CF keys with timestamps less than this during download. Default CF keys are preserved.
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\ImportSstpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes old_key_prefix = 1;</code>
     * @return string
     */
    public function getOldKeyPrefix()
    {
        return $this->old_key_prefix;
    }

    /**
     * Generated from protobuf field <code>bytes old_key_prefix = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOldKeyPrefix(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->old_key_prefix = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes new_key_prefix = 2;</code>
     * @return string
     */
    public function getNewKeyPrefix()
    {
        return $this->new_key_prefix;
    }

    /**
     * Generated from protobuf field <code>bytes new_key_prefix = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNewKeyPrefix(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->new_key_prefix = $var;

        return $this;
    }

    /**
     * (Optional) Rewrite all keys in the range to use this timestamp.
     *
     * Generated from protobuf field <code>uint64 new_timestamp = 3;</code>
     * @return int|string
     */
    public function getNewTimestamp()
    {
        return $this->new_timestamp;
    }

    /**
     * (Optional) Rewrite all keys in the range to use this timestamp.
     *
     * Generated from protobuf field <code>uint64 new_timestamp = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setNewTimestamp(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->new_timestamp = $var;

        return $this;
    }

    /**
     * (Optional) Skip keys with timestamps greater than this during download, useful for compacted SST backups.
     *
     * Generated from protobuf field <code>uint64 ignore_after_timestamp = 4;</code>
     * @return int|string
     */
    public function getIgnoreAfterTimestamp()
    {
        return $this->ignore_after_timestamp;
    }

    /**
     * (Optional) Skip keys with timestamps greater than this during download, useful for compacted SST backups.
     *
     * Generated from protobuf field <code>uint64 ignore_after_timestamp = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setIgnoreAfterTimestamp(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->ignore_after_timestamp = $var;

        return $this;
    }

    /**
     * (Optional) Skip write CF keys with timestamps less than this during download. Default CF keys are preserved.
     *
     * Generated from protobuf field <code>uint64 ignore_before_timestamp = 5;</code>
     * @return int|string
     */
    public function getIgnoreBeforeTimestamp()
    {
        return $this->ignore_before_timestamp;
    }

    /**
     * (Optional) Skip write CF keys with timestamps less than this during download. Default CF keys are preserved.
     *
     * Generated from protobuf field <code>uint64 ignore_before_timestamp = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setIgnoreBeforeTimestamp(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->ignore_before_timestamp = $var;

        return $this;
    }

}

