<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: import_sstpb.proto

namespace CrazyGoat\Proto\ImportSstpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>import_sstpb.SuspendImportRPCRequest</code>
 */
class SuspendImportRPCRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * whether to suspend new imports.
     *
     * Generated from protobuf field <code>bool should_suspend_imports = 1;</code>
     */
    protected $should_suspend_imports = false;
    /**
     * the duration of import service suspension
     * when should_deny_imports is false,
     * this won't take effect.
     *
     * Generated from protobuf field <code>uint64 duration_in_secs = 2;</code>
     */
    protected $duration_in_secs = 0;
    /**
     * The identifier for the caller.
     *
     * Generated from protobuf field <code>string caller = 3;</code>
     */
    protected $caller = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $should_suspend_imports
     *           whether to suspend new imports.
     *     @type int|string $duration_in_secs
     *           the duration of import service suspension
     *           when should_deny_imports is false,
     *           this won't take effect.
     *     @type string $caller
     *           The identifier for the caller.
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\ImportSstpb::initOnce();
        parent::__construct($data);
    }

    /**
     * whether to suspend new imports.
     *
     * Generated from protobuf field <code>bool should_suspend_imports = 1;</code>
     * @return bool
     */
    public function getShouldSuspendImports()
    {
        return $this->should_suspend_imports;
    }

    /**
     * whether to suspend new imports.
     *
     * Generated from protobuf field <code>bool should_suspend_imports = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setShouldSuspendImports(bool $var)
    {
        $this->should_suspend_imports = $var;

        return $this;
    }

    /**
     * the duration of import service suspension
     * when should_deny_imports is false,
     * this won't take effect.
     *
     * Generated from protobuf field <code>uint64 duration_in_secs = 2;</code>
     * @return int|string
     */
    public function getDurationInSecs()
    {
        return $this->duration_in_secs;
    }

    /**
     * the duration of import service suspension
     * when should_deny_imports is false,
     * this won't take effect.
     *
     * Generated from protobuf field <code>uint64 duration_in_secs = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDurationInSecs(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->duration_in_secs = $var;

        return $this;
    }

    /**
     * The identifier for the caller.
     *
     * Generated from protobuf field <code>string caller = 3;</code>
     * @return string
     */
    public function getCaller()
    {
        return $this->caller;
    }

    /**
     * The identifier for the caller.
     *
     * Generated from protobuf field <code>string caller = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCaller(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->caller = $var;

        return $this;
    }

}

