<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: import_sstpb.proto

namespace CrazyGoat\Proto\ImportSstpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>import_sstpb.SuspendImportRPCResponse</code>
 */
class SuspendImportRPCResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The last state before this RPC.
     *
     * Generated from protobuf field <code>bool already_suspended = 1;</code>
     */
    protected $already_suspended = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $already_suspended
     *           The last state before this RPC.
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\ImportSstpb::initOnce();
        parent::__construct($data);
    }

    /**
     * The last state before this RPC.
     *
     * Generated from protobuf field <code>bool already_suspended = 1;</code>
     * @return bool
     */
    public function getAlreadySuspended()
    {
        return $this->already_suspended;
    }

    /**
     * The last state before this RPC.
     *
     * Generated from protobuf field <code>bool already_suspended = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setAlreadySuspended(bool $var)
    {
        $this->already_suspended = $var;

        return $this;
    }

}

