<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: import_sstpb.proto

namespace CrazyGoat\Proto\ImportSstpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>import_sstpb.SwitchModeRequest</code>
 */
class SwitchModeRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.import_sstpb.SwitchMode mode = 1;</code>
     */
    protected $mode = 0;
    /**
     * Generated from protobuf field <code>repeated .import_sstpb.Range ranges = 2;</code>
     */
    private $ranges;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $mode
     *     @type \CrazyGoat\Proto\ImportSstpb\Range[] $ranges
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\ImportSstpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.import_sstpb.SwitchMode mode = 1;</code>
     * @return int one of the values in {@see \CrazyGoat\Proto\ImportSstpb\SwitchMode}
     */
    public function getMode()
    {
        return $this->mode;
    }

    /**
     * Generated from protobuf field <code>.import_sstpb.SwitchMode mode = 1;</code>
     * @param int $var one of the values in {@see \CrazyGoat\Proto\ImportSstpb\SwitchMode}
     * @return $this
     */
    public function setMode(int $var)
    {
        GPBUtil::checkEnum($var, \CrazyGoat\Proto\ImportSstpb\SwitchMode::class);
        $this->mode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .import_sstpb.Range ranges = 2;</code>
     * @return RepeatedField<\CrazyGoat\Proto\ImportSstpb\Range>
     */
    public function getRanges()
    {
        return $this->ranges;
    }

    /**
     * Generated from protobuf field <code>repeated .import_sstpb.Range ranges = 2;</code>
     * @param \CrazyGoat\Proto\ImportSstpb\Range[] $var
     * @return $this
     */
    public function setRanges(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \CrazyGoat\Proto\ImportSstpb\Range::class);
        $this->ranges = $arr;

        return $this;
    }

}

