<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: import_sstpb.proto

namespace CrazyGoat\Proto\ImportSstpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>import_sstpb.WriteRequest</code>
 */
class WriteRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.kvrpcpb.Context context = 3;</code>
     */
    protected $context = null;
    protected $chunk;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CrazyGoat\Proto\ImportSstpb\SSTMeta $meta
     *     @type \CrazyGoat\Proto\ImportSstpb\WriteBatch $batch
     *     @type \CrazyGoat\Proto\Kvrpcpb\Context $context
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\ImportSstpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.import_sstpb.SSTMeta meta = 1;</code>
     * @return \CrazyGoat\Proto\ImportSstpb\SSTMeta|null
     */
    public function getMeta()
    {
        return $this->readOneof(1);
    }

    public function hasMeta()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.import_sstpb.SSTMeta meta = 1;</code>
     * @param \CrazyGoat\Proto\ImportSstpb\SSTMeta $var
     * @return $this
     */
    public function setMeta(\CrazyGoat\Proto\ImportSstpb\SSTMeta|null $var)
    {
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.import_sstpb.WriteBatch batch = 2;</code>
     * @return \CrazyGoat\Proto\ImportSstpb\WriteBatch|null
     */
    public function getBatch()
    {
        return $this->readOneof(2);
    }

    public function hasBatch()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.import_sstpb.WriteBatch batch = 2;</code>
     * @param \CrazyGoat\Proto\ImportSstpb\WriteBatch $var
     * @return $this
     */
    public function setBatch(\CrazyGoat\Proto\ImportSstpb\WriteBatch|null $var)
    {
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.Context context = 3;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\Context|null
     */
    public function getContext()
    {
        return $this->context;
    }

    public function hasContext()
    {
        return isset($this->context);
    }

    public function clearContext()
    {
        unset($this->context);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.Context context = 3;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\Context $var
     * @return $this
     */
    public function setContext(\CrazyGoat\Proto\Kvrpcpb\Context|null $var)
    {
        $this->context = $var;

        return $this;
    }

    /**
     * @return string
     */
    public function getChunk()
    {
        return $this->whichOneof("chunk");
    }

}

